const Config = {
  Debug: false,
  Store: {
    Url: "https://discord.com/invite/QBE6kKCBTF",
    ButtonText: "Entrar Em contato",
    Title: "Feito por Lisa",
    Description: "Projeto sem fins lucrativos.",
  },
  Security: {
    DisableRightClick: true,
    DisableTextSelection: true,
    DisableShortcuts: true,
    BlackScreenOnPrint: true,
    BlackScreenDuration: 500,
  },
  Messages: {
    PrintWarning: "Captura de tela não permitida!",
    DRMFailure:
      "Licença inválida ou domínio não autorizado. Entre em contato com o administrador.",
  },
  DRM: {
    Enabled: false,
    AllowedDomains: ["localhost", "127.0.0.1", "lisavcode.github.io"],
    OwnerName: "Lisa",
    EnableDebuggerLoop: false,
  },
  TrainerUI: {
    UnitaryText: "Custo Unitário",
    EstimateText: "Custo Estimado",
    IngredientsText: "Requisitos",
    CustomText: "Valor Fixo",
    TotalText: "Total de Moedas",
    EmptyIngredientsText: "Nenhum requisito",
    InfoNoPrice: "Informação",
  },
  Orders: {
    NewTitle: "Nova Encomenda",
    EditTitle: "Editar Encomenda",
    AlertEmptyProducts: "Adicione pelo menos um produto!",
    ConfirmDelete: "Apagar esta encomenda permanentemente?",
    ConfirmRestore:
      "Substituir todas as encomendas atuais por {count} do arquivo?",
    FileInvalid: "Arquivo inválido.",
    FileError: "Erro ao ler arquivo JSON.",
    RestoreSuccess: "Restaurado com sucesso!",
  },
  PriceHistory: {
    UpdatedBadgeText: "⚡ Atualizado",
    UpdatedTooltip: "O preço oficial mudou. Clique para ver detalhes.",
    ModalTitle: "Histórico de Preço",
    LabelAntigo: "Antigo",
    LabelAtual: "Atual",
    LabelCustomizado: "Seu Preço",
    BtnReset: "Resetar para Atual",
    BtnFechar: "Fechar",
    ResetToast: "Preço resetado para o valor atual!",
  },
  Taverna: {
    SearchPlaceholder: "Buscar item...",
    QuantityPlaceholder: "Qtd",
    CustomPriceLabel: "Meu Preço",
    TotalLabel: "Total",
    PriceLabel: "Preço",
    Carrinho: {
      Title: "Carrinho",
      AddToast: "Adicionado ao carrinho!",
      ClearConfirm: "Limpar o carrinho?",
      ClearBtn: "Limpar Venda",
      ConfirmBtn: "Confirmar",
      EmptyMsg: "Carrinho vazio.",
      TotalLabel: "Total da Venda",
      RemoveTitle: "Remover item",
    },
  },
  Auth: {
    InvalidTokenMessage: "Código de acesso inválido.",
    AccessDeniedTitle: "Acesso Restrito",
    InputPlaceholder: "Cole seu código de acesso aqui",
    SubmitBtn: "Acessar",
    DeniedPage: "acesso-negado.html",
  },
  EditCard: {
    Title: "Editar Item",
    TabPromocao: "Promoção",
    TabPrecoBase: "Preço Base",
    PromocaoLabel: "Preço de Promoção (Bz)",
    PromocaoHint: "Define Meu Preço temporário. Pode ser abaixo do mínimo.",
    MinLabel: "Preço Mínimo (Bz)",
    MaxLabel: "Preço Máximo (Bz)",
    SaveBtn: "Salvar",
    CancelBtn: "Cancelar",
    SavedToast: "Alterações salvas!",
    ResetBtn: "Resetar",
    ResetToast: "Preços resetados para os valores originais!",
  },
};
