const tavernaData = {
  drakenthal: [
    // COMIDAS (com carne)
    { cat: "Comidas", name: "Espeto do Lenhador", preco: 8, promocao: 0 },
    {
      cat: "Comidas",
      name: "Ensopado Rubro de Drakenthal",
      preco: 12,
      promocao: 0,
    },
    {
      cat: "Comidas",
      name: "Peixe Branco à Moda de Drakenthal",
      preco: 12,
      promocao: 0,
    },

    // COMIDAS (sem carne)
    {
      cat: "Comidas",
      name: "Pastel de Cogumelo Rústico",
      preco: 12,
      promocao: 0,
    },
    {
      cat: "Comidas",
      name: "Caldeirão de Repolhos do Vilarejo",
      preco: 12,
      promocao: 0,
    },

    // SOBREMESAS
    { cat: "Sobremesas", name: "Sorvete de Melancia", preco: 12, promocao: 0 },
    {
      cat: "Sobremesas",
      name: "Pudim das Rosas Silvestres",
      preco: 14,
      promocao: 0,
    },

    // BEBIDAS (sem álcool)
    { cat: "Bebidas", name: "Bebida da Camponesa", preco: 8, promocao: 0 },
    {
      cat: "Bebidas",
      name: "Café Cremoso do Continente",
      preco: 12,
      promocao: 0,
    },

    // BEBIDAS (com álcool)
    { cat: "Bebidas", name: "Licor Dourado de Avelãs", preco: 12, promocao: 0 },
    {
      cat: "Bebidas",
      name: "Sangria Rubra da Feira Velha",
      preco: 13,
      promocao: 0,
    },
    {
      cat: "Bebidas",
      name: "Vinho Jovem das Vinhas Verdes",
      preco: 10,
      promocao: 0,
    },
    {
      cat: "Bebidas",
      name: "Cerveja do Forte Ferreiro",
      preco: 12,
      promocao: 0,
    },
    {
      cat: "Bebidas",
      name: "Espumante das Colinas Reais",
      preco: 15,
      promocao: 0,
    },
  ],
  eldenrock: [
    {
      cat: "Comidas",
      name: "Guisado dos Guardiões",
      descricao: "Teragon's Heart",
      preco: 18,
      promocao: 15,
    },
    {
      cat: "Comidas",
      name: "Torta Outonal de Teria",
      descricao: "Especialidade da Estação",
      preco: 18,
      promocao: 15,
    },
    { cat: "Comidas", name: "Assado de Umbraluz", preco: 10, promocao: 0 },
    { cat: "Comidas", name: "Tiras de Bezerro", preco: 10, promocao: 0 },
    {
      cat: "Comidas",
      name: "Pedregulhos de Ouro",
      descricao: "Batatas Rústicas",
      preco: 12,
      promocao: 0,
    },
    {
      cat: "Comidas",
      name: "Pão de Casca de Carvalho",
      preco: 10,
      promocao: 0,
    },
    { cat: "Comidas", name: "Raízes de Âmbar", preco: 10, promocao: 0 },
    { cat: "Comidas", name: "Torta de Thalóris", preco: 10, promocao: 0 },
    { cat: "Bebidas", name: "Infusão Paz de Teria", preco: 10, promocao: 0 },
    { cat: "Bebidas", name: "Leite de Amêndoas", preco: 10, promocao: 0 },
    { cat: "Bebidas", name: "Orvalho de Miati", preco: 10, promocao: 0 },
    { cat: "Bebidas", name: "Néctar de Umbraluz", preco: 10, promocao: 0 },
    { cat: "Bebidas", name: "Chá das Montanhas", preco: 10, promocao: 0 },
    {
      cat: "Bebidas",
      name: "Hidromel da Centelha",
      preco: 10,
      promocao: 0,
      tag: "Favorito da Casa",
    },
    { cat: "Bebidas", name: "Cerveja de Raiz", preco: 10, promocao: 0 },
  ],
  skallheim: [
    {
      cat: "Promoções",
      name: "Kanelbullar com Kaffe ou Koldskål",
      preco: 35,
      promocao: 28,
    },
    { cat: "Promoções", name: "Far I Kat com Olut", preco: 22, promocao: 18 },
    {
      cat: "Promoções",
      name: "Skause de Skallheim com Mjød",
      preco: 30,
      promocao: 23,
    },
    {
      cat: "Comidas",
      name: "Skause de Skallheim",
      descricao: "Carne de Porco Temperada",
      preco: 15,
      promocao: 0,
      tag: "Prato da Casa",
    },
    {
      cat: "Comidas",
      name: "Fisk stuvad i öl",
      descricao: "Peixe com Cerveja",
      preco: 14,
      promocao: 0,
      tag: "Prato da Casa",
    },
    {
      cat: "Comidas",
      name: "Kanelbullar",
      descricao: "Pão com Canela",
      preco: 18,
      promocao: 0,
    },
    {
      cat: "Comidas",
      name: "Grønnsaker med honning",
      descricao: "Legumes com Mel",
      preco: 9,
      promocao: 0,
    },
    {
      cat: "Comidas",
      name: "Far I Kat",
      descricao: "Carne com Repolho",
      preco: 9,
      promocao: 0,
    },
    {
      cat: "Comidas",
      name: "Gravlax",
      descricao: "Sopa de Peixe",
      preco: 9,
      promocao: 0,
    },
    {
      cat: "Comidas",
      name: "Syltede Sild",
      descricao: "Carne de Porco Acebolada",
      preco: 14,
      promocao: 0,
    },
    {
      cat: "Comidas",
      name: "Blåbärssoppa",
      descricao: "Sopa de Mirtilo",
      preco: 8,
      promocao: 0,
    },
    {
      cat: "Bebidas",
      name: "Mjød",
      descricao: "Hidromel",
      preco: 10,
      promocao: 0,
    },
    { cat: "Bebidas", name: "Vinho de Frutas", preco: 12, promocao: 0 },
    {
      cat: "Bebidas",
      name: "Olut",
      descricao: "Cerveja",
      preco: 10,
      promocao: 0,
    },
    { cat: "Bebidas", name: "Aquavit", preco: 10, promocao: 0 },
    {
      cat: "Bebidas",
      name: "Koldskål",
      descricao: "Bebida de cacau gelado",
      preco: 12,
      promocao: 0,
    },
    {
      cat: "Bebidas",
      name: "Myntate",
      descricao: "Chá de Hortelã",
      preco: 8,
      promocao: 0,
    },
    { cat: "Bebidas", name: "Kaffe", preco: 9, promocao: 0 },
  ],
};
