dataByProfession.alquimista = [
  {"name":"Óleo","min":2,"max":3,"cat":"BÁSICOS","era":1,"ingredients":[]},
  {"name":"Sangue","min":3,"max":3,"cat":"BÁSICOS","era":1,"ingredients":[{"qty":1,"item":"Carne Humana"}]},
  {"name":"Essência Brilhante","min":8,"max":9,"cat":"BÁSICOS","era":1,"ingredients":[{"qty":10,"item":"Grude Brilhante"},{"qty":2,"item":"Folhas de Babosa"}]},
  {"name":"Qualquer Crustáceos","min":2,"max":3,"cat":"BÁSICOS","era":1,"ingredients":[]},
  {"name":"Peixes","min":2,"max":3,"cat":"BÁSICOS","era":1,"ingredients":[]},
  {"name":"Peixes (Atributos)","min":4,"max":5,"cat":"BÁSICOS","era":1,"ingredients":[]},
  {"name":"Vulcan Bee","min":2,"max":2,"cat":"BÁSICOS","era":1,"ingredients":[]},
  {"name":"Folhas de Babosa","min":0.5,"max":0.7,"cat":"BÁSICOS","era":1,"ingredients":[]},
  {"name":"Incenso","min":8,"max":9,"cat":"BÁSICOS","era":1,"ingredients":[{"qty":2,"item":"Mdeira Resinada"}]},
  {"name":"Osso Maculado","min":27,"max":33,"cat":"BÁSICOS","era":2,"ingredients":[{"qty":1,"item":"Pó de Mácula"},{"qty":20,"item":"Osso"}]},
  {"name":"Consolidador de Pedras","min":2,"max":2,"cat":"BÁSICOS","era":2,"ingredients":[{"qty":2,"item":"Resina"},{"qty":6,"item":"Fibra"}]},
  {"name":"Poção de brânquia de peixe","min":317,"max":380,"cat":"BÁSICOS","era":3,"ingredients":[{"qty":1,"item":"Fish Gill Potion"},{"qty":2,"item":"Base Alquímica"},{"qty":1,"item":"Pós de Lótus Negra"},{"qty":1,"item":"Escama de Dagon"}]},
  {"name":"Rocha Maculada","min":15,"max":17,"cat":"BÁSICOS","era":3,"ingredients":[{"qty":2,"item":"Pedra"},{"qty":1,"item":"Icor"},{"qty":1,"item":"Sangue de Demônio"}]},
  {"name":"Farinha de Ossos","min":1,"max":2,"cat":"BÁSICOS","era":1,"ingredients":[{"qty":1,"item":"Osso"}]},
  {"name":"Pó de Fogobruxo","min":31,"max":37,"cat":"BÁSICOS","era":2,"ingredients":[{"qty":8,"item":"Enxofre"},{"qty":2,"item":"Essência Brilhante"}]},
  {"name":"Base Alquímica","min":9,"max":10,"cat":"BÁSICOS","era":2,"ingredients":[{"qty":2,"item":"Pó de Prata"},{"qty":1,"item":"Pó de Ouro"},{"qty":2,"item":"Icor"}]},
  {"name":"Fogaço","min":3,"max":3,"cat":"BÁSICOS","era":2,"ingredients":[{"qty":1,"item":"Enxofre"},{"qty":2,"item":"Piche"}]},
  {"name":"Joia de Rádio","min":80,"max":96,"cat":"BÁSICOS","era":2,"ingredients":[{"qty":10,"item":"Cristal"},{"qty":3,"item":"Base Alquímica"},{"qty":1,"item":"Pó de Fogobruxo"}]},
  {"name":"Pó de Ouro","min":2,"max":2,"cat":"BÁSICOS","era":2,"ingredients":[{"qty":1,"item":"Barra de Ouro"}]},
  {"name":"Pó de Prata","min":1,"max":2,"cat":"BÁSICOS","era":2,"ingredients":[{"qty":1,"item":"Barra de Prata"}]},
  {"name":"Dracopólvora","min":89,"max":107,"cat":"BÁSICOS","era":3,"ingredients":[{"qty":2,"item":"Sangue de Demônio"},{"qty":12,"item":"Fogaço"},{"qty":5,"item":"Enxofre"},{"qty":25,"item":"Cristal"}]},
  {"name":"Ataduras Rudimentares","min":0.91,"max":1,"cat":"BÁSICOS","era":1,"ingredients":[{"qty":7,"item":"Fibra Vegetal"},{"qty":3,"item":"Linen clothes"}]},
  {"name":"Ataduras de Cura","min":46,"max":55,"cat":"BÁSICOS","era":1,"ingredients":[{"qty":10,"item":"Couro"},{"qty":10,"item":"Folhas de Babosa"},{"qty":10,"item":"Linen clothes"}]},
  {"name":"Atadura Anestesiante","min":83,"max":99,"cat":"BÁSICOS","era":2,"ingredients":[{"qty":10,"item":"Couro"},{"qty":20,"item":"Folhas de Babosa"},{"qty":1,"item":"Base Alquímica"},{"qty":25,"item":"Linen clothes"}]},
  {"name":"Ataduras Bloqueadoras","min":156,"max":187,"cat":"BÁSICOS","era":2,"ingredients":[{"qty":10,"item":"Seda"},{"qty":30,"item":"Folhas de Babosa"},{"qty":10,"item":"Base Alquímica"}]},
  {"name":"Ataduras com Infusão","min":416,"max":499,"cat":"BÁSICOS","era":3,"ingredients":[{"qty":10,"item":"Seda"},{"qty":30,"item":"Folhas de Babosa"},{"qty":10,"item":"Base Alquímica"},{"qty":1,"item":"Escama de Dagon"}]},
  {"name":"Adubo","min":8,"max":9,"cat":"BÁSICOS","era":1,"ingredients":[{"qty":5,"item":"Fibra Vegetal"},{"qty":4,"item":"Farinha de Osso"},{"qty":2,"item":"Carne Podre"}]},
  {"name":"Adubo Potente","min":32,"max":38,"cat":"BÁSICOS","era":2,"ingredients":[{"qty":2,"item":"Cinzas Cruas"},{"qty":2,"item":"Sangue"},{"qty":2,"item":"Adubo"}]},
  {"name":"Tiny potion bottle","min":3,"max":3,"cat":"BÁSICOS","era":1,"ingredients":[{"qty":2,"item":"Vidros"}]},
  {"name":"Small potion bottle","min":7,"max":9,"cat":"BÁSICOS","era":1,"ingredients":[{"qty":5,"item":"Vidros"}]},
  {"name":"Potion bottle","min":13,"max":16,"cat":"BÁSICOS","era":1,"ingredients":[{"qty":10,"item":"Vidros"}]},
  {"name":"Large potion bottle","min":33,"max":39,"cat":"BÁSICOS","era":1,"ingredients":[{"qty":25,"item":"Vidros"}]},
  {"name":"Huge potion bottle","min":66,"max":78,"cat":"BÁSICOS","era":1,"ingredients":[{"qty":50,"item":"Vidros"}]},
  {"name":"Azure Essence","min":5,"max":6,"cat":"BÁSICOS","era":1,"ingredients":[{"qty":5,"item":"Cristal"},{"qty":2,"item":"Flax Flower"}]},
  {"name":"Qualquer Planta","min":0.5,"max":1,"cat":"BÁSICOS","era":1,"ingredients":[]},
  {"name":"Cogumelo Esporoso","min":0.5,"max":1,"cat":"BÁSICOS","era":1,"ingredients":[]},
  {"name":"Grude Brilhante","min":0.5,"max":1,"cat":"BÁSICOS","era":1,"ingredients":[]},
  {"name":"Bitter Crinilla Dust","min":2,"max":3,"cat":"BÁSICOS","era":1,"ingredients":[{"qty":1,"item":"Crinilla Dust"}]},
  {"name":"Blue Bell Dust","min":2,"max":3,"cat":"BÁSICOS","era":1,"ingredients":[{"qty":1,"item":"Blue Bell"}]},
  {"name":"Dragonfern Dust","min":2,"max":3,"cat":"BÁSICOS","era":1,"ingredients":[{"qty":1,"item":"Dragonfern"}]},
  {"name":"Qualquer Lótus","min":1,"max":2,"cat":"BÁSICOS","era":1,"ingredients":[]},
  {"name":"Flor de Lótus Negra","min":4,"max":6,"cat":"BÁSICOS","era":1,"ingredients":[]},
  {"name":"Flor de Lótus Dourada","min":10,"max":15,"cat":"BÁSICOS","era":1,"ingredients":[]},
  {"name":"Flor de Lótus Gélida","min":8,"max":10,"cat":"BÁSICOS","era":1,"ingredients":[]},
  {"name":"Pós de Lótus","min":2,"max":3,"cat":"BÁSICOS","era":1,"ingredients":[{"qty":1,"item":"Qualquer Lótus"}]},
  {"name":"Pós de Lótus Negra","min":5,"max":6,"cat":"BÁSICOS","era":1,"ingredients":[{"qty":1,"item":"Lótus Negra"}]},
  {"name":"Pós de Lótus Dourada","min":13,"max":16,"cat":"BÁSICOS","era":1,"ingredients":[{"qty":1,"item":"Lótus Dourada"}]},
  {"name":"Pós de Lótus Gélida","min":10,"max":12,"cat":"BÁSICOS","era":1,"ingredients":[{"qty":1,"item":"Lótus Gélida"}]},
  {"name":"Firebloom","min":10,"max":15,"cat":"BÁSICOS","era":1,"ingredients":[]},
  {"name":"Shadow Flower Dust","min":6,"max":6,"cat":"BÁSICOS","era":1,"ingredients":[{"qty":3,"item":"Shadow Flower"}]},
  {"name":"Elarikan Dust","min":117,"max":140,"cat":"BÁSICOS","era":4,"ingredients":[{"qty":8,"item":"Unstable Substance"},{"qty":12,"item":"Widow's Leaf"},{"qty":1,"item":"Pós de Lótus Negra"}]},
  {"name":"Ink","min":20,"max":23,"cat":"AOC AVANÇADOS","era":1,"ingredients":[{"qty":5,"item":"Óleo"},{"qty":5,"item":"Icor"}]},
  {"name":"Arcane Essence","min":25,"max":30,"cat":"AOC AVANÇADOS","era":2,"ingredients":[{"qty":2,"item":"Sapphire Shard"},{"qty":5,"item":"Aurora Herb"},{"qty":2,"item":"Blue Bell Dust"},{"qty":3,"item":"Dragonfern Dust"}]},
  {"name":"Astral WaterSkin","min":936,"max":1124,"cat":"AOC AVANÇADOS","era":1,"ingredients":[{"qty":1,"item":"Odre"},{"qty":15,"item":"Moon Dust"},{"qty":25,"item":"Mystical Dust"}]},
  {"name":"Blessing of Keldora","min":46,"max":55,"cat":"AOC AVANÇADOS","era":2,"ingredients":[{"qty":1,"item":"Glândula Volátil"},{"qty":3,"item":"Sangue de Demônio"},{"qty":5,"item":"Aurora Herb"}]},
  {"name":"(Warpaint) Ashura's Blessing","min":871,"max":1045,"cat":"AOC AVANÇADOS","era":2,"ingredients":[{"qty":5,"item":"Arcane Essence"},{"qty":60,"item":"Moon Dust"},{"qty":10,"item":"Ink"}]},
  {"name":"Stormcaller's Breathing Potion","min":14,"max":17,"cat":"AOC AVANÇADOS","era":2,"ingredients":[{"qty":15,"item":"Calathuia Plant"},{"qty":7,"item":"Dragonfern Plant"}]},
  {"name":"Fragment of Demise","min":203,"max":243,"cat":"AOC AVANÇADOS","era":4,"ingredients":[{"qty":2,"item":"Pós de Lótus Negra"},{"qty":3,"item":"Flor de Lótus Dourada"},{"qty":20,"item":"Dragonfern Dust"},{"qty":30,"item":"Sangue"}]},
  {"name":"Fragment of Fury","min":195,"max":234,"cat":"AOC AVANÇADOS","era":4,"ingredients":[{"qty":2,"item":"Lótus Carmesim"},{"qty":3,"item":"Sangue de Demônio"},{"qty":50,"item":"Gelo Preto"},{"qty":2,"item":"Rocha Dourada"}]},
  {"name":"Fragment of Purity","min":131,"max":158,"cat":"AOC AVANÇADOS","era":4,"ingredients":[{"qty":2,"item":"Flor de Lótus Gélida"},{"qty":30,"item":"Bitter Crinilla Dust"},{"qty":8,"item":"Blue Bell Plant"},{"qty":3,"item":"Rocha Prateada"}]},
  {"name":"Crescent Water","min":35,"max":42,"cat":"AOC AVANÇADOS","era":4,"ingredients":[{"qty":5,"item":"Fragment of Purity"},{"qty":3,"item":"Vulcan Bee"},{"qty":20,"item":"Lunar Hemp"},{"qty":3,"item":"Blue Bell Dust"}]},
  {"name":"(Potion) Soul Essence - Lesser","min":15,"max":18,"cat":"POÇÕES CONSUMÍVEL","era":1,"ingredients":[{"qty":1,"item":"Azure Essence"},{"qty":1,"item":"Tiny Potion Bottle"}]},
  {"name":"(Potion) Soul Essence","min":34,"max":41,"cat":"POÇÕES CONSUMÍVEL","era":1,"ingredients":[{"qty":3,"item":"Azure Essence"},{"qty":10,"item":"Folhas de Babosa"},{"qty":1,"item":"Small Potion Bottle"}]},
  {"name":"(Potion) Soul Essence - Potent","min":99,"max":119,"cat":"POÇÕES CONSUMÍVEL","era":1,"ingredients":[{"qty":6,"item":"Azure Essence"},{"qty":30,"item":"Folhas de Babosa"},{"qty":1,"item":"Potion Bottle"},{"qty":3,"item":"Shadow Flower Dust"}]},
  {"name":"(Potion) Soul Essence - Enhanced","min":186,"max":223,"cat":"POÇÕES CONSUMÍVEL","era":1,"ingredients":[{"qty":10,"item":"Azure Essence"},{"qty":60,"item":"Folhas de Babosa"},{"qty":1,"item":"Large Potion Bottle"},{"qty":6,"item":"Shadow Flower Dust"}]},
  {"name":"(Potion) Soul Essence - Powerful","min":326,"max":391,"cat":"POÇÕES CONSUMÍVEL","era":1,"ingredients":[{"qty":15,"item":"Azure Essence"},{"qty":100,"item":"Folhas de Babosa"},{"qty":1,"item":"Huge Potion Bottle"},{"qty":10,"item":"Shadow Flower Dust"}]},
  {"name":"(Potion) Soul Essence - Mystical","min":1145,"max":1374,"cat":"POÇÕES CONSUMÍVEL","era":1,"ingredients":[{"qty":100,"item":"Azure Essence"},{"qty":150,"item":"Folhas de Babosa"},{"qty":1,"item":"Huge Potion Bottle"},{"qty":40,"item":"Shadow Flower Dust"}]},
  {"name":"Poção de Lótus Amarela","min":13,"max":16,"cat":"POÇÕES CONSUMÍVEL","era":1,"ingredients":[{"qty":10,"item":"Flor de Lótus Amarela"}]},
  {"name":"Skill Potion","min":10,"max":12,"cat":"POÇÕES CONSUMÍVEL","era":1,"ingredients":[{"qty":15,"item":"Grude Brilhante"}]},
  {"name":"Poção de Fôlego","min":61,"max":73,"cat":"POÇÕES CONSUMÍVEL","era":1,"ingredients":[{"qty":1,"item":"Orbe de Água"},{"qty":5,"item":"Essência Brilhante"}]},
  {"name":"Curativo Violeta","min":39,"max":47,"cat":"POÇÕES CONSUMÍVEL","era":1,"ingredients":[{"qty":10,"item":"Glândula de Veneno de Serpente"}]},
  {"name":"Poção da Memória Bestial","min":46,"max":56,"cat":"POÇÕES CONSUMÍVEL","era":2,"ingredients":[{"qty":1,"item":"Frasco de Vidro com Água"},{"qty":3,"item":"Flor de Lótus Amarela"},{"qty":10,"item":"Cinzas Cruas"},{"qty":3,"item":"Sangue"}]},
  {"name":"Poção do Aprendizado Natural","min":41,"max":50,"cat":"POÇÕES CONSUMÍVEL","era":2,"ingredients":[{"qty":1,"item":"Frasco de Vidro com Água"},{"qty":3,"item":"Flor de Lótus Amarela"},{"qty":10,"item":"Cinzas Cruas"},{"qty":3,"item":"Pó de Osso"}]},
  {"name":"Elixir de Veemência","min":94,"max":112,"cat":"POÇÕES CONSUMÍVEL","era":2,"ingredients":[{"qty":1,"item":"Frasco de Vidro"},{"qty":2,"item":"Base Alquímica"},{"qty":5,"item":"Pós de Lótus (Carmesim)"},{"qty":5,"item":"Pós de Lótus Gélida"}]},
  {"name":"Demon's Bane","min":35,"max":42,"cat":"POÇÕES CONSUMÍVEL","era":2,"ingredients":[{"qty":2,"item":"Sangue de Demônio"},{"qty":1,"item":"Rocha Prateada"}]},
  {"name":"Poção de Atributo","min":23,"max":27,"cat":"POÇÕES CONSUMÍVEL","era":2,"ingredients":[{"qty":1,"item":"Frasco de Vidro"},{"qty":1,"item":"Base Alquímica"},{"qty":2,"item":"Pós de Lótus (Variedade)"}]},
  {"name":"Poção de Branquia de Peixe","min":23,"max":27,"cat":"POÇÕES CONSUMÍVEL","era":2,"ingredients":[{"qty":1,"item":"Frasco de Vidro"},{"qty":1,"item":"Base Alquímica"},{"qty":1,"item":"Pós de Lótus (Púrpura)"},{"qty":1,"item":"Pós de Lótus (Carmesim)"}]},
  {"name":"Poção de Dote","min":25,"max":30,"cat":"POÇÕES CONSUMÍVEL","era":2,"ingredients":[{"qty":1,"item":"Frasco de Vidro"},{"qty":1,"item":"Base Alquímica"},{"qty":3,"item":"Pós de Lótus (Cinzenta)"}]},
  {"name":"Poção Lótus Dourada","min":44,"max":52,"cat":"POÇÕES CONSUMÍVEL","era":2,"ingredients":[{"qty":1,"item":"Frasco de Vidro"},{"qty":2,"item":"Flor de Lótus Dourada"},{"qty":1,"item":"Base Alquímica"}]},
  {"name":"Poção de Lótus Gélida","min":38,"max":46,"cat":"POÇÕES CONSUMÍVEL","era":2,"ingredients":[{"qty":1,"item":"Frasco de Vidro"},{"qty":2,"item":"Flor de Lótus Gélida"},{"qty":1,"item":"Base Alquímica"}]},
  {"name":"Poção de Lótus Negra","min":33,"max":40,"cat":"POÇÕES CONSUMÍVEL","era":2,"ingredients":[{"qty":1,"item":"Frasco de Vidro"},{"qty":3,"item":"Pós de Lótus Negra"},{"qty":1,"item":"Base Alquímica"}]},
  {"name":"Poção Lótus Púrpura","min":25,"max":30,"cat":"POÇÕES CONSUMÍVEL","era":2,"ingredients":[{"qty":1,"item":"Frasco de Vidro"},{"qty":3,"item":"Pós de Lótus (Púrpura)"},{"qty":1,"item":"Base Alquímica"}]},
  {"name":"Blessing of Keldora","min":46,"max":55,"cat":"POÇÕES CONSUMÍVEL","era":3,"ingredients":[{"qty":1,"item":"Glândula Volátil"},{"qty":3,"item":"Sangue de Demônio"},{"qty":5,"item":"Aurora Herb"}]},
  {"name":"Tonic of Enchanced Preservation","min":329,"max":395,"cat":"POÇÕES CONSUMÍVEL","era":3,"ingredients":[{"qty":1,"item":"Chifre de Dragão"},{"qty":30,"item":"Icor"},{"qty":2,"item":"Rocha Dourada"},{"qty":10,"item":"Mushroon"}]},
  {"name":"Extrato de Babosa Fraco","min":2,"max":2,"cat":"POÇÃO BABOSA","era":1,"ingredients":[{"qty":3,"item":"Folhas de Babosa"}]},
  {"name":"Extrato de Babosa","min":7,"max":8,"cat":"POÇÃO BABOSA","era":1,"ingredients":[{"qty":10,"item":"Folhas de Babosa"}]},
  {"name":"Aloe Seed Extract","min":52,"max":62,"cat":"POÇÃO BABOSA","era":1,"ingredients":[{"qty":40,"item":"Sementes de Babosa"}]},
  {"name":"Extrato de Babosa Concentrado","min":38,"max":46,"cat":"POÇÃO BABOSA","era":2,"ingredients":[{"qty":30,"item":"Folhas de Babosa"},{"qty":10,"item":"Água Purificada"},{"qty":10,"item":"Grude Brilhante"}]},
  {"name":"Extrato de Babosa Puro","min":99,"max":118,"cat":"POÇÃO BABOSA","era":2,"ingredients":[{"qty":50,"item":"Folhas de Babosa"},{"qty":13,"item":"Água Purificada"},{"qty":5,"item":"Essência Brilhante"}]},
  {"name":"Mystical Healing Potion","min":166,"max":199,"cat":"POÇÃO BABOSA","era":2,"ingredients":[{"qty":15,"item":"Mystical Dust"},{"qty":15,"item":"Lunar Hemp"},{"qty":20,"item":"Calathuia Plant"},{"qty":1,"item":"Potion Common Small"}]},
  {"name":"Extrato de Babosa Imbuído","min":229,"max":275,"cat":"POÇÃO BABOSA","era":3,"ingredients":[{"qty":50,"item":"Folhas de Babosa"},{"qty":13,"item":"Essência Brilhante"},{"qty":100,"item":"Grude Brilhante"}]},
  {"name":"Potion Common Small","min":3,"max":3,"cat":"POÇÕES MATERIAL","era":1,"ingredients":[{"qty":2,"item":"Vidro"}]},
  {"name":"Potion Common Medium","min":6,"max":7,"cat":"POÇÕES MATERIAL","era":1,"ingredients":[{"qty":4,"item":"Vidro"}]},
  {"name":"Potion Common Large","min":9,"max":10,"cat":"POÇÕES MATERIAL","era":1,"ingredients":[{"qty":6,"item":"Vidro"}]},
  {"name":"Mystical Potion","min":266,"max":320,"cat":"POÇÕES MATERIAL","era":3,"ingredients":[{"qty":25,"item":"Mystical Dust"},{"qty":12,"item":"Lunar Hemp"},{"qty":1,"item":"Sapphire"},{"qty":1,"item":"Potion Common Medium"}]},
  {"name":"Demon Blood Potion","min":1014,"max":1217,"cat":"POÇÕES MATERIAL","era":4,"ingredients":[{"qty":30,"item":"Sangue de Demônio"},{"qty":5,"item":"Dracopólvora"},{"qty":14,"item":"Vulcan Bee"},{"qty":1,"item":"Potion Common Medium"}]},
  {"name":"Potion Liquid of Elarikan","min":1112,"max":1334,"cat":"POÇÕES MATERIAL","era":4,"ingredients":[{"qty":25,"item":"Unstable Substance"},{"qty":1,"item":"Emerald"},{"qty":5,"item":"Elarikan Powder"},{"qty":1,"item":"Potion Common Medium"}]},
  {"name":"Death Whisper Potion","min":49229,"max":59075,"cat":"POÇÕES MATERIAL","era":6,"ingredients":[{"qty":1,"item":"Xarium"},{"qty":5,"item":"Mystical Potion"},{"qty":5,"item":"Demon Blood Potion"},{"qty":5,"item":"Potion Liquid of Elarikan"}]},
  {"name":"Moon Dust","min":6,"max":7,"cat":"POWDER","era":2,"ingredients":[{"qty":4,"item":"Lunar Hemp"},{"qty":3,"item":"Calathuia Plant"},{"qty":2,"item":"Widow's Leaf"}]},
  {"name":"Mystical Dust","min":7,"max":9,"cat":"POWDER","era":2,"ingredients":[{"qty":6,"item":"Mysthical Plant"},{"qty":5,"item":"Aurora Herb"}]},
  {"name":"Elarikan Powder","min":117,"max":140,"cat":"POWDER","era":4,"ingredients":[{"qty":8,"item":"Unstable Substance"},{"qty":12,"item":"Widow's Leaf"},{"qty":1,"item":"Pós de Lótus Negra"}]},
  {"name":"Clareador de Tintas","min":13,"max":16,"cat":"TINTURAS","era":1,"ingredients":[{"qty":1,"item":"Frasco de Vidro"},{"qty":5,"item":"Osso"}]},
  {"name":"Escurecedor de Tintas","min":8,"max":10,"cat":"TINTURAS","era":1,"ingredients":[{"qty":1,"item":"Frasco de Vidro"},{"qty":3,"item":"Piche"}]},
  {"name":"Pincel de Tinta","min":8,"max":9,"cat":"TINTURAS","era":1,"ingredients":[{"qty":5,"item":"Pelos"},{"qty":3,"item":"Galho"},{"qty":3,"item":"Fibra Vegetal"}]},
  {"name":"Tintura Básica","min":9,"max":11,"cat":"TINTURAS","era":1,"ingredients":[{"qty":1,"item":"Frasco de Vidro"},{"qty":1,"item":"Item Básico"}]},
  {"name":"Tintura Básica Clara","min":29,"max":34,"cat":"TINTURAS","era":1,"ingredients":[{"qty":1,"item":"Tintura Básica"},{"qty":1,"item":"Clareador de Tintas"}]},
  {"name":"Tintura Básica Escura","min":23,"max":27,"cat":"TINTURAS","era":1,"ingredients":[{"qty":1,"item":"Tintura Básica"},{"qty":1,"item":"Escurecedor de Tintas"}]},
  {"name":"Tintura Preta","min":19,"max":23,"cat":"TINTURAS","era":1,"ingredients":[{"qty":1,"item":"Frasco de Vidro"},{"qty":5,"item":"Óleo"}]},
  {"name":"Tintura Branca","min":14,"max":17,"cat":"TINTURAS","era":2,"ingredients":[{"qty":1,"item":"Frasco de Vidro"},{"qty":3,"item":"Cinzas Cruas"}]},
  {"name":"Silver Dye","min":23,"max":28,"cat":"TINTURAS","era":2,"ingredients":[{"qty":1,"item":"Frasco de Vidro"},{"qty":10,"item":"Pó de Prata"}]},
  {"name":"Gold Dye","min":32,"max":38,"cat":"TINTURAS","era":2,"ingredients":[{"qty":1,"item":"Frasco de Vidro"},{"qty":10,"item":"Pó de Ouro"}]},
  {"name":"Enchanted Basic Glow (Blue, Green, Orange, Pink, Purple, Red, Yellow)","min":138,"max":166,"cat":"TINTURAS","era":2,"ingredients":[{"qty":1,"item":"Tintura Básica"},{"qty":1,"item":"Tintura Básica Escura"},{"qty":3,"item":"Arcane Essence"}]},
  {"name":"Enchanted Teal Glow","min":163,"max":196,"cat":"TINTURAS","era":2,"ingredients":[{"qty":1,"item":"Tintura Básica Clara"},{"qty":1,"item":"Tintura Básica Escura"},{"qty":3,"item":"Arcane Essence"}]},
  {"name":"Anour Hill Gold","min":24,"max":29,"cat":"TINTURAS FACÇÕES","era":1,"ingredients":[{"qty":1,"item":"Flor de Lótus Amarela"},{"qty":1,"item":"Tintura Amarelo-escuro"},{"qty":1,"item":"Tintura Amarelo-claro"}]},
  {"name":"Anour Hill Red","min":12,"max":15,"cat":"TINTURAS FACÇÕES","era":1,"ingredients":[{"qty":1,"item":"Uncut Ruby"},{"qty":1,"item":"Tintura Vermelho-escuro"}]},
  {"name":"Arkanvail Teal","min":23,"max":28,"cat":"TINTURAS FACÇÕES","era":1,"ingredients":[{"qty":1,"item":"Tintura Azul-claro"},{"qty":1,"item":"Tintura Azul"}]},
  {"name":"Bush Green","min":23,"max":28,"cat":"TINTURAS FACÇÕES","era":1,"ingredients":[{"qty":2,"item":"Tintura Verde"}]},
  {"name":"Cold Embrace Black","min":12,"max":15,"cat":"TINTURAS FACÇÕES","era":1,"ingredients":[{"qty":1,"item":"Flor-cinzenta Lupinus"},{"qty":1,"item":"Tintura Cinza-escuro"}]},
  {"name":"Cold Embrance Purple","min":31,"max":37,"cat":"TINTURAS FACÇÕES","era":1,"ingredients":[{"qty":1,"item":"Tintura Azul-escuro"},{"qty":1,"item":"Uncut Sapphire"}]},
  {"name":"Crystal White","min":54,"max":65,"cat":"TINTURAS FACÇÕES","era":1,"ingredients":[{"qty":1,"item":"Clareador de Tintas"},{"qty":1,"item":"Tintura Cinza-claro"}]},
  {"name":"Elven Purple","min":12,"max":15,"cat":"TINTURAS FACÇÕES","era":1,"ingredients":[{"qty":1,"item":"Mandrágora Falsa"},{"qty":1,"item":"Tintura Roxa"}]},
  {"name":"Felgarth Gray","min":12,"max":15,"cat":"TINTURAS FACÇÕES","era":1,"ingredients":[{"qty":1,"item":"Flor-cinzenta Lupinus"},{"qty":1,"item":"Tintura Cinza"}]},
  {"name":"Jade Green","min":19,"max":23,"cat":"TINTURAS FACÇÕES","era":1,"ingredients":[{"qty":1,"item":"Tintura Verde-claro"},{"qty":1,"item":"Moon Dust"}]},
  {"name":"Kronyxium Black","min":12,"max":15,"cat":"TINTURAS FACÇÕES","era":1,"ingredients":[{"qty":1,"item":"Flor-cinzenta Lupinus"},{"qty":1,"item":"Tintura Cinza-escuro"}]},
  {"name":"Lutaran Purple","min":23,"max":28,"cat":"TINTURAS FACÇÕES","era":1,"ingredients":[{"qty":1,"item":"Tintura Roxo-escuro"},{"qty":1,"item":"Tintura Magenta-escuro"}]},
  {"name":"Princess Pink","min":23,"max":28,"cat":"TINTURAS FACÇÕES","era":1,"ingredients":[{"qty":1,"item":"Tintura Roxo-claro"},{"qty":1,"item":"Tintura Magenta"}]},
  {"name":"Sky Blue","min":23,"max":28,"cat":"TINTURAS FACÇÕES","era":1,"ingredients":[{"qty":2,"item":"Tintura Azul"}]},
  {"name":"Skyan Blue","min":23,"max":28,"cat":"TINTURAS FACÇÕES","era":1,"ingredients":[{"qty":1,"item":"Tintura Azul"},{"qty":1,"item":"Tintura Azul-escuro"}]},
  {"name":"Stormhold Blue","min":31,"max":37,"cat":"TINTURAS FACÇÕES","era":1,"ingredients":[{"qty":1,"item":"Tintura Azul"},{"qty":1,"item":"Uncut Sapphire"}]},
  {"name":"Stormhold White","min":12,"max":15,"cat":"TINTURAS FACÇÕES","era":1,"ingredients":[{"qty":1,"item":"Flor-cinzenta Lupinus"},{"qty":1,"item":"Tintura Cinza-claro"}]},
  {"name":"Vanghoul Brown","min":23,"max":28,"cat":"TINTURAS FACÇÕES","era":1,"ingredients":[{"qty":1,"item":"Tintura Marrom"},{"qty":1,"item":"Tintura Marrom-escuro"}]},
  {"name":"Vanghoul Brown","min":8,"max":10,"cat":"TINTURAS FACÇÕES","era":2,"ingredients":[{"qty":1,"item":"Flor-cinzenta Lupinus"},{"qty":1,"item":"Moon Dust"}]},
  {"name":"Elvanor Arcane","min":45,"max":54,"cat":"TINTURAS FACÇÕES","era":2,"ingredients":[{"qty":1,"item":"Mandrágora Falsa"},{"qty":1,"item":"Tintura Roxa"},{"qty":1,"item":"Arcane Essence"}]},
  {"name":"Sanguis","min":207,"max":248,"cat":"TINTURAS FACÇÕES","era":3,"ingredients":[{"qty":5,"item":"Sangue de Demônio"},{"qty":1,"item":"Blood of the Devil Bear"},{"qty":1,"item":"Tintura Vermelha"}]},
  {"name":"Plague Green","min":25,"max":30,"cat":"TINTURAS FACÇÕES","era":4,"ingredients":[{"qty":1,"item":"Tintura Verde"},{"qty":1,"item":"Unstable Substance"}]},
  {"name":"Orbe de Água","min":8,"max":9,"cat":"ORBES","era":1,"ingredients":[{"qty":1,"item":"Frasco de Vidro"},{"qty":1,"item":"Icor"}]},
  {"name":"Orbe de Fogo Demoníaco","min":30,"max":35,"cat":"ORBES","era":1,"ingredients":[{"qty":1,"item":"Orbe de Água"},{"qty":5,"item":"Glândula Volátil"}]},
  {"name":"Orbe de Lótus Púrpura","min":24,"max":29,"cat":"ORBES","era":1,"ingredients":[{"qty":1,"item":"Orbe de Água"},{"qty":2,"item":"Flor de Lótus Negra"},{"qty":3,"item":"Flor de Lótus Púrpura"}]},
  {"name":"Orbe Gasosa","min":17,"max":20,"cat":"ORBES","era":1,"ingredients":[{"qty":1,"item":"Orbe de Água"},{"qty":10,"item":"Cogumelo Esporoso"}]},
  {"name":"Orbe Oleosa","min":13,"max":16,"cat":"ORBES","era":1,"ingredients":[{"qty":1,"item":"Orbe de Água"},{"qty":5,"item":"Piche"}]},
  {"name":"Tatuagens Básicas","min":23,"max":28,"cat":"PINTURAS","era":1,"ingredients":[{"qty":1,"item":"Rolo de Papiro"},{"qty":1,"item":"Pincel de Tinta"},{"qty":1,"item":"Tinta Básica"}]},
  {"name":"Tatuagens com carvão","min":12,"max":14,"cat":"PINTURAS","era":1,"ingredients":[{"qty":1,"item":"Rolo de Papiro"},{"qty":1,"item":"Pincel de Tinta"},{"qty":1,"item":"Carvão"}]},
  {"name":"Tatuagens com sangue","min":15,"max":18,"cat":"PINTURAS","era":1,"ingredients":[{"qty":1,"item":"Rolo de Papiro"},{"qty":1,"item":"Pincel de Tinta"},{"qty":1,"item":"Sangue"}]},
  {"name":"Tatuagens com Icor","min":13,"max":15,"cat":"PINTURAS","era":1,"ingredients":[{"qty":1,"item":"Rolo de Papiro"},{"qty":1,"item":"Pincel de Tinta"},{"qty":1,"item":"Icor"}]},
  {"name":"Tatuagens com Piche","min":12,"max":14,"cat":"PINTURAS","era":1,"ingredients":[{"qty":1,"item":"Rolo de Papiro"},{"qty":1,"item":"Pincel de Tinta"},{"qty":1,"item":"Piche"}]},
  {"name":"Tatuagens com Tintura Básica Clara","min":48,"max":58,"cat":"PINTURAS","era":1,"ingredients":[{"qty":1,"item":"Rolo de Papiro"},{"qty":1,"item":"Pincel de Tinta"},{"qty":1,"item":"Tintura Básica Clara"}]},
  {"name":"Tatuagens com Tintura Básica Escura","min":41,"max":49,"cat":"PINTURAS","era":1,"ingredients":[{"qty":1,"item":"Rolo de Papiro"},{"qty":1,"item":"Pincel de Tinta"},{"qty":1,"item":"Tintura Básica Escura"}]},
  {"name":"Tatuagens do Exiles Extreme","min":183,"max":219,"cat":"PINTURAS","era":1,"ingredients":[{"qty":5,"item":"Rolo de Papiro"},{"qty":5,"item":"Pincel de Tinta"},{"qty":5,"item":"Tintura Preta"}]},
  {"name":"Tatuagens de Siptah","min":183,"max":219,"cat":"PINTURAS","era":1,"ingredients":[{"qty":5,"item":"Rolo de Papiro"},{"qty":5,"item":"Pincel de Tinta"},{"qty":5,"item":"Tintura Preta"}]},
  {"name":"Tatuagens com cinza crua","min":14,"max":17,"cat":"PINTURAS","era":2,"ingredients":[{"qty":1,"item":"Rolo de Papiro"},{"qty":1,"item":"Pincel de Tinta"},{"qty":1,"item":"Cinzas cruas"}]},
  {"name":"Tatuagens Atributos","min":255,"max":306,"cat":"PINTURAS","era":3,"ingredients":[{"qty":1,"item":"Rolo de Papiro"},{"qty":1,"item":"Pincel de Tinta"},{"qty":1,"item":"Tinta Básica"},{"qty":2,"item":"Dracopólvora"}]},
  {"name":"Yamatai","min":78,"max":94,"cat":"FORRAGENS","era":1,"ingredients":[{"qty":1,"item":"Gororoba"},{"qty":1,"item":"Flor de Lótus Amarela"},{"qty":2,"item":"Folhas de Babosa"}]},
  {"name":"Turaniana","min":78,"max":94,"cat":"FORRAGENS","era":1,"ingredients":[{"qty":1,"item":"Gororoba"},{"qty":1,"item":"Flor de Lótus Amarela"},{"qty":2,"item":"Folhas de Babosa"}]},
  {"name":"Picta","min":146,"max":175,"cat":"FORRAGENS","era":1,"ingredients":[{"qty":1,"item":"Gororoba"},{"qty":1,"item":"Sangue"},{"qty":2,"item":"Osso"}]},
  {"name":"Mascote Enfeitiçada/Saborosa","min":78,"max":94,"cat":"FORRAGENS","era":1,"ingredients":[{"qty":1,"item":"Gororoba"},{"qty":1,"item":"Flor de Lótus Amarela"},{"qty":2,"item":"Folhas de Babosa"}]},
  {"name":"Poitain","min":78,"max":94,"cat":"FORRAGENS","era":1,"ingredients":[{"qty":1,"item":"Gororoba"},{"qty":1,"item":"Flor de Lótus Amarela"},{"qty":2,"item":"Folhas de Babosa"}]},
  {"name":"Óleo da Abundância","min":377,"max":452,"cat":"ÓLEOS","era":3,"ingredients":[{"qty":5,"item":"Fragmento do Poder"},{"qty":20,"item":"Óleo"}]},
  {"name":"Óleo da Agônia","min":377,"max":452,"cat":"ÓLEOS","era":3,"ingredients":[{"qty":5,"item":"Fragmento do Poder"},{"qty":20,"item":"Óleo"}]},
  {"name":"Óleo da Concussão","min":377,"max":452,"cat":"ÓLEOS","era":3,"ingredients":[{"qty":5,"item":"Fragmento do Poder"},{"qty":20,"item":"Óleo"}]},
  {"name":"Óleo de Equilíbrio","min":377,"max":452,"cat":"ÓLEOS","era":3,"ingredients":[{"qty":5,"item":"Fragmento do Poder"},{"qty":20,"item":"Óleo"}]},
  {"name":"Óleo de Penetração","min":377,"max":452,"cat":"ÓLEOS","era":3,"ingredients":[{"qty":5,"item":"Fragmento do Poder"},{"qty":20,"item":"Óleo"}]},
  {"name":"Veneno da Rainha-Escorpião","min":69,"max":83,"cat":"TÓXINAS","era":2,"ingredients":[{"qty":1,"item":"Glândula de Peçonha da Rainha-Escorpião"}]},
  {"name":"Veneno do Terror das Dunas","min":28,"max":33,"cat":"TÓXINAS","era":2,"ingredients":[{"qty":1,"item":"Glândula de Toxina do Terror das Dunas"}]},
  {"name":"Acid Toxin","min":45,"max":54,"cat":"TÓXINAS","era":"X","ingredients":[{"qty":1,"item":"Frasco de Vidro"},{"qty":3,"item":"Base Alquímica"},{"qty":1,"item":"Glândula de Toxina do Terror das Dunas"}]},
  {"name":"Bleeding Toxin","min":45,"max":54,"cat":"TÓXINAS","era":"X","ingredients":[{"qty":1,"item":"Frasco de Vidro"},{"qty":3,"item":"Base Alquímica"},{"qty":1,"item":"Glândula de Toxina do Terror das Dunas"}]},
  {"name":"Corrupting Toxin","min":217,"max":261,"cat":"TÓXINAS","era":"X","ingredients":[{"qty":1,"item":"Frasco de Vidro"},{"qty":3,"item":"Base Alquímica"},{"qty":5,"item":"Osso Maculado"}]},
  {"name":"Dead Bane Toxin","min":41,"max":49,"cat":"TÓXINAS","era":"X","ingredients":[{"qty":1,"item":"Frasco de Vidro"},{"qty":3,"item":"Base Alquímica"},{"qty":1,"item":"Pó de Mácula"}]},
  {"name":"Drunkard's Toxin","min":53,"max":63,"cat":"TÓXINAS","era":"X","ingredients":[{"qty":1,"item":"Frasco de Vidro"},{"qty":3,"item":"Base Alquímica"},{"qty":20,"item":"Lúpulo"}]},
  {"name":"Fish Gill Potion","min":23,"max":27,"cat":"TÓXINAS","era":"X","ingredients":[{"qty":1,"item":"Frasco de Vidro"},{"qty":1,"item":"Base Alquímica"},{"qty":1,"item":"Pós de Lótus (Púrpura)"},{"qty":1,"item":"Pós de Lótus (Carmesim)"}]},
  {"name":"Heatstroke Toxin","min":66,"max":79,"cat":"TÓXINAS","era":"X","ingredients":[{"qty":1,"item":"Frasco de Vidro"},{"qty":3,"item":"Base Alquímica"},{"qty":20,"item":"Enxofre"}]},
  {"name":"Sundering Toxin","min":111,"max":133,"cat":"TÓXINAS","era":"X","ingredients":[{"qty":1,"item":"Frasco de Vidro"},{"qty":3,"item":"Base Alquímica"},{"qty":2,"item":"Pó de Fogobruxo"}]},
  {"name":"Frostbite Toxin","min":92,"max":110,"cat":"TÓXINAS","era":"X","ingredients":[{"qty":1,"item":"Frasco de Vidro"},{"qty":3,"item":"Base Alquímica"},{"qty":20,"item":"Gelo Preto"}]},
  {"name":"Jarro Explosivo","min":160,"max":192,"cat":"EXPLOSIVOS","era":3,"ingredients":[{"qty":1,"item":"Jarra de Argila"},{"qty":5,"item":"Piche"},{"qty":1,"item":"Dracopólvora"}]},
  {"name":"Armadilha Explosiva","min":252,"max":303,"cat":"EXPLOSIVOS","era":3,"ingredients":[{"qty":20,"item":"Barra de Ferro"},{"qty":20,"item":"Galho"},{"qty":1,"item":"Jarro Explosivo"},{"qty":20,"item":"Enxofre"}]},
  {"name":"Armadilha de Vapor","min":252,"max":303,"cat":"EXPLOSIVOS","era":3,"ingredients":[{"qty":20,"item":"Barra de Ferro"},{"qty":20,"item":"Galho"},{"qty":1,"item":"Jarro Explosivo"},{"qty":20,"item":"Icor"}]},
  {"name":"Barragem de Fogo Demoniaco","min":85,"max":102,"cat":"EXPLOSIVOS","era":3,"ingredients":[{"qty":2,"item":"Jarro Explosivo"},{"qty":10,"item":"Barbante"}]},
  {"name":"Elarikan Plague Barrage","min":84500,"max":101400,"cat":"PLAGUE","era":6,"ingredients":[{"qty":1,"item":"Kronyxium Steel Bar"},{"qty":1,"item":"Xarium Metal Bar"},{"qty":40,"item":"Unstable Substance"},{"qty":10,"item":"Potion Liquid of Elarikan"}]},
  {"name":"Elarikan Plague (MOD)","min":4186,"max":5023,"cat":"PLAGUE","era":6,"ingredients":[{"qty":250,"item":"Unstable Substance"},{"qty":1,"item":"Amethyst Shard"},{"qty":25,"item":"Firebloom"},{"qty":5,"item":"Dracopólvora"}]},
  {"name":"Essence of Binding","min":299,"max":359,"cat":"PLAGUE","era":6,"ingredients":[{"qty":300,"item":"Obsidiana"},{"qty":25,"item":"Icor"},{"qty":30,"item":"Bitter Crinilla Plant"},{"qty":10,"item":"Firebloom"}]},
  {"name":"Plague Crystal","min":3392,"max":4071,"cat":"PLAGUE","era":6,"ingredients":[{"qty":1,"item":"Titanium Alloy"},{"qty":2,"item":"Potion Liquid of Elarikan"},{"qty":35,"item":"Unstable Substance"},{"qty":1,"item":"Topaz"}]},
  {"name":"Runic Enchantment","min":4995,"max":5994,"cat":"PLAGUE","era":6,"ingredients":[{"qty":1,"item":"Tonic of Enchanced Preservation"},{"qty":5,"item":"Dracopólvora"},{"qty":15,"item":"Fragment of Demise"},{"qty":50,"item":"Cobalt Ore"}]},
  {"name":"Elarikan Plague Barrel","min":88909,"max":106690,"cat":"PLAGUE","era":6,"ingredients":[{"qty":1,"item":"Kronyxium Steel Bar"},{"qty":1,"item":"Xarium Metal Bar"},{"qty":30,"item":"Onyx Composite"},{"qty":12,"item":"Potion Liquid of Elarikan"}]},
  {"name":"Elarikan Plague Mine","min":43295,"max":51954,"cat":"PLAGUE","era":6,"ingredients":[{"qty":1,"item":"Kronyxium Steel Bar"},{"qty":5,"item":"Potion Liquid of Elarikan"},{"qty":10,"item":"Reforço de Aço"}]},
  {"name":"Plague Bracket Torch","min":14,"max":16,"cat":"PLAGUE","era":6,"ingredients":[{"qty":3,"item":"Madeira Moldada"},{"qty":3,"item":"Reforço de Ferro"}]},
  {"name":"Plague Brazier","min":14,"max":16,"cat":"PLAGUE","era":6,"ingredients":[{"qty":7,"item":"Reforço de Ferro"}]}
];
