dataByProfession.artesao = [

  // =================
  // BASE
  // =================
  { name: "Corda Rígida", min: 115, max: 161, cat: "Base", era: 1 },
  { name: "Empunhadura de Arma", min: 90, max: 126, cat: "Base", era: 1 },
  { name: "Madeira Moldada", min: 2, max: 3, cat: "Base", era: 1 },
  { name: "Madeira Resinada", min: 3, max: 5, cat: "Base", era: 1 },

  // =================
  // CONSTRUÇÕES / UTILIDADES
  // =================
  { name: "Elevador", min: 85, max: 102, cat: "Construção", era: 1 },
  { name: "Ladder, Wall Mounted", min: 9, max: 10, cat: "Construção", era: 1 },
  { name: "Training Dummy", min: 10, max: 12, cat: "Construção", era: 1 },
  { name: "Elevador Rápido", min: 468, max: 562, cat: "Construção", era: 2 },
  { name: "Armadilha para Mariscos Aprimorada", min: 659, max: 791, cat: "Construção", era: 3 },
  { name: "Armadilha para Peixes Aprimorada", min: 659, max: 791, cat: "Construção", era: 3 },
  { name: "Armored Taming Stall", min: 850, max: 1020, cat: "Construção", era: 3 },
  { name: "Ponte Levadica", min: 579, max: 695, cat: "Construção", era: 3 },

  // =================
  // ARCOS
  // =================
  { name: "Arco DLC", min: 6, max: 8, cat: "Arcos", era: 1 },
  { name: "Arco Hirciniano", min: 254, max: 304, cat: "Arcos", era: 2 },
  { name: "Arco Hirciniano Leve", min: 115, max: 138, cat: "Arcos", era: 1 },
  { name: "Arco Antigo", min: 392, max: 471, cat: "Arcos", era: 2 },
  { name: "Arco de Aço Reforçado", min: 96, max: 115, cat: "Arcos", era: 3 },
  { name: "Arco de Osso de Dragão", min: 2038, max: 2445, cat: "Arcos", era: 4 },
  { name: "Arco Khari", min: 4038, max: 4845, cat: "Arcos", era: 4 },
  { name: "Arco Épico DLC", min: 303, max: 363, cat: "Arcos", era: 4 },

  // =================
  // FLECHAS
  // =================
  { name: "Flecha Abismal (10x)", min: 53, max: 64, cat: "Flechas", era: 1 },
  { name: "Flecha Arredondada (10x)", min: 10, max: 11, cat: "Flechas", era: 1 },
  { name: "Flecha com Ponta de Ferro (10x)", min: 10, max: 12, cat: "Flechas", era: 1 },
  { name: "Flecha de Luz (10x)", min: 76, max: 91, cat: "Flechas", era: 1 },
  { name: "Flecha de Cura (10x)", min: 196, max: 236, cat: "Flechas", era: 1 },
  { name: "Flecha de gás Tóxico (10x)", min: 39, max: 47, cat: "Flechas", era: 1 },
  { name: "Flecha de Aço (10x)", min: 27, max: 32, cat: "Flechas", era: 2 },
  { name: "Flecha de Navalha (10x)", min: 31, max: 37, cat: "Flechas", era: 2 },
  { name: "Flechas de Marfim (10x)", min: 99, max: 119, cat: "Flechas", era: 2 },
  { name: "Armor Penetrating Darts (10x)", min: 75, max: 90, cat: "Flechas", era: 2 },
  { name: "Rupture Darts (10x)", min: 117, max: 141, cat: "Flechas", era: 2 },
  { name: "Poison Dart (10x)", min: 144, max: 173, cat: "Flechas", era: 2 },
  { name: "Flecha de Piche (5x)", min: 49, max: 58, cat: "Flechas", era: 1 },
  { name: "Flecha osso de dragão (10x)", min: 106, max: 128, cat: "Flechas", era: 4 },
  { name: "Flecha de Aço Reforçado (10x)", min: 43, max: 52, cat: "Flechas", era: 3 },
  { name: "Flecha Explosiva (10x)", min: 184, max: 221, cat: "Flechas", era: 4 },
  { name: "Flecha dos Homens-Serpente (10x)", min: 209, max: 251, cat: "Flechas", era: 2 },
  { name: "Flecha de Metal das Estrelas (10x)", min: 74, max: 89, cat: "Flechas", era: 4 },
  { name: "Flecha de Obsidiana (10x)", min: 80, max: 95, cat: "Flechas", era: 4 },

  // =================
  // DECORAÇÕES / MOBÍLIA
  // =================
  { name: "Bookshelf, Basic", min: 126, max: 152, cat: "Decoração", era: 1 },
  { name: "Bookshelf, Large", min: 505, max: 606, cat: "Decoração", era: 1 },
  { name: "Bookshelf, Long / Tall", min: 253, max: 303, cat: "Decoração", era: 1 },
  { name: "Bar Counter, Corner / Small", min: 86, max: 104, cat: "Decoração", era: 1 },
  { name: "Bar Counter, Large", min: 144, max: 173, cat: "Decoração", era: 1 },
  { name: "Iron Serving", min: 13, max: 15, cat: "Decoração", era: 1 },
  { name: "Journal Row, Half", min: 350, max: 420, cat: "Decoração", era: 1 },
  { name: "Journal Row, Long", min: 700, max: 840, cat: "Decoração", era: 1 },
  { name: "Journal Row, Short", min: 140, max: 168, cat: "Decoração", era: 1 },
  { name: "Journal Standing", min: 35, max: 42, cat: "Decoração", era: 1 },

  { name: "Khitan Bed Pillow", min: 100, max: 120, cat: "Decoração", era: 1 },
  { name: "Large Hide Rug", min: 250, max: 300, cat: "Decoração", era: 1 },
  { name: "Large Keg", min: 60, max: 72, cat: "Decoração", era: 1 },
  { name: "Large Red Rug", min: 9, max: 11, cat: "Decoração", era: 1 },
  { name: "Long Warhorn", min: 35, max: 42, cat: "Decoração", era: 1 },
  { name: "Nomad's Tent", min: 160, max: 192, cat: "Decoração", era: 1 },
  { name: "Pillow", min: 23, max: 27, cat: "Decoração", era: 1 },
  { name: "Balcão de Taverna (Quina/Reto)", min: 154, max: 185, cat: "Decoração", era: 1 },
  { name: "Balcão Pequeno de Taverna", min: 51, max: 62, cat: "Decoração", era: 1 },
  { name: "Scroll Stack, Pile", min: 38, max: 45, cat: "Decoração", era: 1 },
  { name: "Scroll Stack, Short", min: 70, max: 84, cat: "Decoração", era: 1 },
  { name: "Scroll Stack, Tall", min: 75, max: 90, cat: "Decoração", era: 1 },
  { name: "Simple Desk", min: 94, max: 113, cat: "Decoração", era: 1 },
  { name: "Small Cimmerian Hut", min: 10, max: 12, cat: "Decoração", era: 1 },
  { name: "Bed Pillow", min: 100, max: 120, cat: "Decoração", era: 1 },
  { name: "Tall Stool", min: 20, max: 24, cat: "Decoração", era: 1 },
  { name: "Tavern Bar", min: 263, max: 315, cat: "Decoração", era: 1 },
  { name: "Tavern Counter", min: 75, max: 90, cat: "Decoração", era: 1 },
  { name: "Tavern Shelf", min: 75, max: 90, cat: "Decoração", era: 1 },
  { name: "Tent Decor", min: 19, max: 23, cat: "Decoração", era: 1 },
  { name: "Thrall Dressing Room", min: 20, max: 24, cat: "Decoração", era: 1 },
  { name: "Town Sign", min: 15, max: 18, cat: "Decoração", era: 1 },
  { name: "Trader's Tent", min: 160, max: 192, cat: "Decoração", era: 1 },
  { name: "Vanity", min: 20, max: 24, cat: "Decoração", era: 1 },
  { name: "Wet Barrel", min: 20, max: 24, cat: "Decoração", era: 1 },
  { name: "Wooden Serving", min: 3, max: 3, cat: "Decoração", era: 1 },
  { name: "Alvo de Arquearia", min: 30, max: 36, cat: "Decoração", era: 1 },
  { name: "Armário", min: 36, max: 44, cat: "Decoração", era: 1 },
  { name: "Banco", min: 10, max: 12, cat: "Decoração", era: 1 },
  { name: "Banco de Madeira, Tora", min: 20, max: 24, cat: "Decoração", era: 1 },
  { name: "Banco Pequeno, Banquinho", min: 5, max: 6, cat: "Decoração", era: 1 },
  { name: "Bandeira da Estígia", min: 157, max: 188, cat: "Decoração", era: 1 },
  { name: "Bandeira do Dragão", min: 170, max: 204, cat: "Decoração", era: 1 },
  { name: "Banquinho de Barril", min: 4, max: 4, cat: "Decoração", era: 1 },
  { name: "Banquinho Quadrado, Redondo, Trançado", min: 20, max: 24, cat: "Decoração", era: 1 },
  { name: "Barril", min: 10, max: 12, cat: "Decoração", era: 1 },
  { name: "Barril Madeira Moldada", min: 20, max: 24, cat: "Decoração", era: 1 },
  { name: "Barril de Cerveja", min: 20, max: 24, cat: "Decoração", era: 1 },
  { name: "Barril Pequeno", min: 15, max: 18, cat: "Decoração", era: 1 },
  { name: "Berrante", min: 60, max: 72, cat: "Decoração", era: 1 },
  { name: "Berrante de Marfim", min: 75, max: 90, cat: "Decoração", era: 1 },
  { name: "Boneco Chop-Chop", min: 2, max: 2, cat: "Decoração", era: 1 },
  { name: "Bookcase (1)-(5)", min: 50, max: 60, cat: "Decoração", era: 1 },
  { name: "Braserio Cimeriano Ferro Parede", min: 25, max: 30, cat: "Decoração", era: 1 },

  { name: "Braserio Estigiano", min: 51, max: 62, cat: "Decoração", era: 1 },
  { name: "Braserio Estigiano Tripode", min: 65, max: 78, cat: "Decoração", era: 1 },
  { name: "Braserio Milenar", min: 31, max: 38, cat: "Decoração", era: 1 },
  { name: "Braserio Suspenso", min: 25, max: 30, cat: "Decoração", era: 1 },
  { name: "Bule de Chá", min: 25, max: 30, cat: "Decoração", era: 1 },
  { name: "Cadeira, Confortável, Madeira", min: 20, max: 24, cat: "Decoração", era: 1 },
  { name: "Caixote", min: 100, max: 120, cat: "Decoração", era: 1 },
  { name: "Caldeirão", min: 51, max: 62, cat: "Decoração", era: 1 },
  { name: "Cama, Dobrada, Estigiana", min: 29, max: 35, cat: "Decoração", era: 1 },
  { name: "Cama Dupla", min: 39, max: 47, cat: "Decoração", era: 1 },
  { name: "Cama Luxuosa", min: 29, max: 35, cat: "Decoração", era: 1 },
  { name: "Caneca de Ferro", min: 3, max: 3, cat: "Decoração", era: 1 },
  { name: "Caneco", min: 3, max: 3, cat: "Decoração", era: 1 },
  { name: "Caneco de Ferro", min: 6, max: 8, cat: "Decoração", era: 1 },
  { name: "Carrinho de Mão", min: 74, max: 89, cat: "Decoração", era: 1 },
  { name: "Carroça", min: 230, max: 276, cat: "Decoração", era: 1 },
  { name: "Carroça com Barris", min: 338, max: 405, cat: "Decoração", era: 1 },
  { name: "Castiçal", min: 12, max: 15, cat: "Decoração", era: 1 },
  { name: "Peça de Xadrez", min: 13, max: 15, cat: "Decoração", era: 1 },
  { name: "Cesto", min: 5, max: 6, cat: "Decoração", era: 1 },
  { name: "Cesto de Vinhos", min: 65, max: 78, cat: "Decoração", era: 1 },
  { name: "Chifre de Marfim para Beber", min: 25, max: 30, cat: "Decoração", era: 1 },
  { name: "Chifre para Beber", min: 75, max: 90, cat: "Decoração", era: 1 },
  { name: "Cocho de Comida", min: 125, max: 150, cat: "Decoração", era: 1 },
  { name: "Cocho de Água", min: 113, max: 135, cat: "Decoração", era: 1 },
  { name: "Cortinas", min: 260, max: 312, cat: "Decoração", era: 1 },
  { name: "Cuia de Ferro", min: 6, max: 8, cat: "Decoração", era: 1 },
  { name: "Cuia de Madeira", min: 3, max: 3, cat: "Decoração", era: 1 },
  { name: "Cuia Decorativa", min: 8, max: 9, cat: "Decoração", era: 1 },
  { name: "Decantador de Ferro", min: 6, max: 8, cat: "Decoração", era: 1 },
  { name: "Diário", min: 35, max: 42, cat: "Decoração", era: 1 },
  { name: "Estandarte de Guerra", min: 170, max: 204, cat: "Decoração", era: 1 },
  { name: "Estande Grande", min: 208, max: 249, cat: "Decoração", era: 1 },
  { name: "Estante de Vinhos", min: 65, max: 78, cat: "Decoração", era: 1 },
  { name: "Estátua Valéria, Conan, Subotai", min: 8, max: 9, cat: "Decoração", era: 1 },
  { name: "Estátua de Cervo", min: 15, max: 18, cat: "Decoração", era: 1 },
  { name: "Estátua Valéria, Conan, Subotai (Grande)", min: 50, max: 60, cat: "Decoração", era: 1 },
  { name: "Estátua de Culto Setita", min: 75, max: 90, cat: "Decoração", era: 1 },
  { name: "Estátua de Lobo", min: 43, max: 51, cat: "Decoração", era: 1 },
  { name: "Gaiola", min: 25, max: 30, cat: "Decoração", era: 1 },
  { name: "Gaiola Grande", min: 50, max: 60, cat: "Decoração", era: 1 },
  { name: "Gongo", min: 35, max: 42, cat: "Decoração", era: 1 },
  { name: "Jardineira Decorativa", min: 4, max: 4, cat: "Decoração", era: 1 },
  { name: "Jarra de Argila", min: 31, max: 38, cat: "Decoração", era: 1 },
  { name: "Jarra de Argila Estigiana", min: 6, max: 8, cat: "Decoração", era: 1 },
  { name: "Jarra de Argila Estigiana (Pequena)", min: 5, max: 5, cat: "Decoração", era: 1 },
  { name: "Jarra de Argila Grande", min: 13, max: 15, cat: "Decoração", era: 1 },
  { name: "Jarra de Ferro", min: 6, max: 8, cat: "Decoração", era: 1 },
  { name: "Jarra de Metal Estigiano", min: 25, max: 30, cat: "Decoração", era: 1 },
  { name: "Jarro de Cerâmica", min: 13, max: 15, cat: "Decoração", era: 1 },
  { name: "Lamparina de Parede", min: 34, max: 40, cat: "Decoração", era: 1 },
  { name: "Large Serving Keg", min: 119, max: 143, cat: "Decoração", era: 1 },
  { name: "Mesa, Retangular, Baixa", min: 20, max: 24, cat: "Decoração", era: 1 },
  { name: "Mesa Longa", min: 40, max: 48, cat: "Decoração", era: 1 },
  { name: "Mesa de Barril", min: 152, max: 182, cat: "Decoração", era: 1 },
  { name: "Mesa de Barril (Pequena)", min: 52, max: 62, cat: "Decoração", era: 1 },
  { name: "Mesa dos Observadores", min: 10, max: 12, cat: "Decoração", era: 1 },
  { name: "Mesa Estigiana, Redonda", min: 20, max: 24, cat: "Decoração", era: 1 },
  { name: "Monte de Feno", min: 50, max: 60, cat: "Decoração", era: 1 },
  { name: "Mortarium, Panela de Ferro", min: 25, max: 30, cat: "Decoração", era: 1 },
  { name: "Water Jug", min: 13, max: 15, cat: "Decoração", era: 1 },
  { name: "Dado de Osso", min: 3, max: 3, cat: "Decoração", era: 1 },
  { name: "Parchment Scroll", min: 3, max: 3, cat: "Decoração", era: 1 },
  { name: "Passarela de Pedra", min: 5, max: 6, cat: "Decoração", era: 1 },
  { name: "Pilha de Toras", min: 38, max: 45, cat: "Decoração", era: 1 },
  { name: "Pilha Pequena de Feno", min: 13, max: 15, cat: "Decoração", era: 1 },
  { name: "Pintura", min: 150, max: 180, cat: "Decoração", era: 1 },
  { name: "Placa Vertical (Conhecimento)", min: 79, max: 95, cat: "Decoração", era: 1 },
  { name: "Placa de Madeira, Parede", min: 15, max: 18, cat: "Decoração", era: 1 },
  { name: "Placa de Rocha", min: 19, max: 23, cat: "Decoração", era: 1 },
  { name: "Pote de Ferro", min: 25, max: 30, cat: "Decoração", era: 1 },
  { name: "Poço d'Água", min: 685, max: 822, cat: "Decoração", era: 1 },
  { name: "Prateleira", min: 10, max: 12, cat: "Decoração", era: 1 },
  { name: "Prato de Ferro", min: 6, max: 8, cat: "Decoração", era: 1 },
  { name: "Prato Estigiano", min: 5, max: 6, cat: "Decoração", era: 1 },
  { name: "Rebolo Decorativo", min: 88, max: 105, cat: "Decoração", era: 1 },
  { name: "Recado", min: 1, max: 1, cat: "Decoração", era: 1 },
  { name: "Recado com Faca, Flecha", min: 3, max: 3, cat: "Decoração", era: 1 },
  { name: "Roda de Carroça", min: 19, max: 23, cat: "Decoração", era: 1 },
  { name: "Rodapé de Ferro para Exibição", min: 225, max: 270, cat: "Decoração", era: 1 },
  { name: "Rolo de Papiro", min: 1, max: 2, cat: "Decoração", era: 1 },
  { name: "Sinos de Ventos de Darfar", min: 60, max: 72, cat: "Decoração", era: 1 },
  { name: "Sinos de Ventos de Darfar Grandes", min: 85, max: 102, cat: "Decoração", era: 1 },
  { name: "Small Serving Keg", min: 20, max: 24, cat: "Decoração", era: 1 },
  { name: "Suporte de Barris", min: 410, max: 492, cat: "Decoração", era: 1 },
  { name: "Suporte de Escudo", min: 11, max: 14, cat: "Decoração", era: 1 },
  { name: "Suporte para 3 Armas", min: 25, max: 30, cat: "Decoração", era: 1 },
  { name: "Suporte para 1 Armas", min: 18, max: 21, cat: "Decoração", era: 1 },
  { name: "Suporte para Vinhos", min: 38, max: 45, cat: "Decoração", era: 1 },
  { name: "Tabuleiro de Reis", min: 88, max: 105, cat: "Decoração", era: 1 },
  { name: "Tambor", min: 74, max: 89, cat: "Decoração", era: 1 },
  { name: "Tambor da Estígia", min: 29, max: 35, cat: "Decoração", era: 1 },
  { name: "Tampa de Barril", min: 1, max: 1, cat: "Decoração", era: 1 },
  { name: "Tapete, Estigiano", min: 8, max: 9, cat: "Decoração", era: 1 },

  { name: "Tapete de Couro", min: 15, max: 18, cat: "Decoração", era: 1 },
  { name: "Tapete Grande", min: 9, max: 11, cat: "Decoração", era: 1 },
  { name: "Tapeçaria", min: 152, max: 183, cat: "Decoração", era: 1 },
  { name: "Tapeçaria (Couro)", min: 129, max: 155, cat: "Decoração", era: 1 },

  { name: "Taxidermia de Alce / Cervo / Gazela / Kudu", min: 113, max: 135, cat: "Decoração", era: 1 },
  { name: "Taxidermia de Aranha", min: 400, max: 480, cat: "Decoração", era: 1 },
  { name: "Taxidermia de Avestruz / Bico-de-Sapato", min: 140, max: 168, cat: "Decoração", era: 1 },
  { name: "Taxidermia de Bode Montês", min: 125, max: 150, cat: "Decoração", era: 1 },
  { name: "Taxidermia de Crocodilo / Komodo", min: 388, max: 465, cat: "Decoração", era: 1 },
  { name: "Taxidermia de Demônio-Morcego", min: 575, max: 690, cat: "Decoração", era: 1 },
  { name: "Taxidermia de Dente-de-Sabre / Jaguar", min: 325, max: 390, cat: "Decoração", era: 1 },
  { name: "Taxidermia de Diabrete", min: 125, max: 150, cat: "Decoração", era: 1 },
  { name: "Taxidermia de Escorpião", min: 299, max: 358, cat: "Decoração", era: 1 },
  { name: "Taxidermia de Gorila", min: 535, max: 642, cat: "Decoração", era: 1 },
  { name: "Taxidermia de Hiena", min: 300, max: 360, cat: "Decoração", era: 1 },
  { name: "Taxidermia de Ieti", min: 171, max: 205, cat: "Decoração", era: 1 },
  { name: "Taxidermia de Javali", min: 138, max: 165, cat: "Decoração", era: 1 },
  { name: "Taxidermia de Leão", min: 138, max: 165, cat: "Decoração", era: 1 },
  { name: "Taxidermia de Lobo", min: 311, max: 373, cat: "Decoração", era: 1 },
  { name: "Taxidermia de Lombo-Grosso", min: 265, max: 318, cat: "Decoração", era: 1 },
  { name: "Taxidermia de Pantera / Tigre", min: 325, max: 390, cat: "Decoração", era: 1 },
  { name: "Taxidermia de Rei-Alce", min: 538, max: 645, cat: "Decoração", era: 1 },
  { name: "Taxidermia de Rochifre", min: 63, max: 75, cat: "Decoração", era: 1 },
  { name: "Taxidermia de Salamandra", min: 363, max: 435, cat: "Decoração", era: 1 },
  { name: "Taxidermia de Terror das Dunas", min: 300, max: 360, cat: "Decoração", era: 1 },
  { name: "Taxidermia de Urso", min: 563, max: 675, cat: "Decoração", era: 1 },

  { name: "Tecido Sombrado Vermelho", min: 170, max: 204, cat: "Decoração", era: 1 },
  { name: "Tela Dobrável", min: 45, max: 54, cat: "Decoração", era: 1 },
  { name: "Tenda Simples", min: 21, max: 25, cat: "Decoração", era: 1 },
  { name: "Tocha de Parede / Vertical Brilhante", min: 26, max: 31, cat: "Decoração", era: 1 },
  { name: "Toco, Velas", min: 10, max: 12, cat: "Decoração", era: 1 },
  { name: "Travesseiro", min: 23, max: 27, cat: "Decoração", era: 1 },

  { name: "Troféu de Peixe", min: 10, max: 12, cat: "Decoração", era: 1 },
  { name: "Troféu Básico", min: 80, max: 96, cat: "Decoração", era: 1 },
  { name: "Troféu Médio", min: 378, max: 453, cat: "Decoração", era: 1 },

  { name: "Vaso de Cerâmica", min: 6, max: 8, cat: "Decoração", era: 1 },

  { name: "Giant Skull Decoration", min: 68, max: 81, cat: "Decoração", era: 2 },
  { name: "Mini Vault", min: 5360, max: 6432, cat: "Decoração", era: 2 },
  { name: "Cata-Vento", min: 210, max: 252, cat: "Decoração", era: 2 },
  { name: "Cofre", min: 6918, max: 8301, cat: "Decoração", era: 2 },
  { name: "Decoração de Filhote de Lombo-Grosso", min: 2528, max: 3034, cat: "Decoração", era: 2 },
  { name: "Grande Poço d'Água", min: 12113, max: 14535, cat: "Decoração", era: 2 },
  { name: "Incinerator", min: 38, max: 45, cat: "Decoração", era: 2 },
  { name: "Inkpot and Quill (1)-(6)", min: 152, max: 183, cat: "Decoração", era: 2 },
  { name: "Lareira", min: 449, max: 538, cat: "Decoração", era: 2 },
  { name: "Tocha de Parede / Vertical de Rádio", min: 269, max: 323, cat: "Decoração", era: 2 },
  { name: "Tocha de Parede / Vertical de Fogobuxo", min: 83, max: 100, cat: "Decoração", era: 2 },
  { name: "Troféu Avançado", min: 2505, max: 3006, cat: "Decoração", era: 2 },
  { name: "Trono, Atlante, Leonino", min: 1416, max: 1699, cat: "Decoração", era: 2 },
  { name: "Águas Regeneradoras", min: 276, max: 332, cat: "Decoração", era: 2 },

  { name: "Ancient Book", min: 305, max: 366, cat: "Decoração", era: 3 },
  { name: "Leather-Bound Book", min: 305, max: 366, cat: "Decoração", era: 3 },
  { name: "Standing Book (1)-(6)", min: 305, max: 366, cat: "Decoração", era: 3 },
  { name: "Open Book (1)-(2)", min: 305, max: 366, cat: "Decoração", era: 3 },
  { name: "Ornate Book", min: 320, max: 384, cat: "Decoração", era: 3 },
  { name: "Giant's Chest", min: 779, max: 935, cat: "Decoração", era: 3 },
  { name: "Crânio de Metal Decorativo", min: 230, max: 276, cat: "Decoração", era: 3 },
  { name: "Estátua de Homem-Serpente", min: 489, max: 587, cat: "Decoração", era: 3 },
  { name: "Estátua de Fratricida", min: 489, max: 587, cat: "Decoração", era: 3 },
  { name: "Ovo Petrificado", min: 489, max: 587, cat: "Decoração", era: 3 },
  { name: "Troféu Raro", min: 5005, max: 6006, cat: "Decoração", era: 3 },
  { name: "Trono de Skelos", min: 853, max: 1024, cat: "Decoração", era: 3 },
  { name: "Fornalha Melhorada (Forno)", min: 491, max: 589, cat: "Decoração", era: 3 },

    { name: "Cama Nemediana", min: 39, max: 47, cat: "Decoração", era: 1 },
  { name: "Tapete Nemediano", min: 3, max: 4, cat: "Decoração", era: 1 },
  { name: "Cadeira Nemediana", min: 8, max: 10, cat: "Decoração", era: 1 },
  { name: "Bandeira Nemediana", min: 63, max: 75, cat: "Decoração", era: 1 },
  { name: "Estatueta Nemediana", min: 2, max: 2, cat: "Decoração", era: 1 },
  { name: "Estátua de Jabalí Nemediana", min: 10, max: 12, cat: "Decoração", era: 1 },
  { name: "Mesa Nemediana", min: 8, max: 10, cat: "Decoração", era: 1 },
  { name: "Relevo Nemediano", min: 8, max: 10, cat: "Decoração", era: 1 },
  { name: "Mortário Nemediano", min: 3, max: 3, cat: "Decoração", era: 1 },
  { name: "Estante de Livros Nemediana", min: 16, max: 19, cat: "Decoração", era: 1 },
  { name: "Maço de Papéis", min: 10, max: 12, cat: "Decoração", era: 1 },
  { name: "Gongo Nemediano", min: 14, max: 17, cat: "Decoração", era: 1 },
  { name: "Diário Nemediano", min: 14, max: 17, cat: "Decoração", era: 1 },
  { name: "Pergaminho Nemediano", min: 14, max: 17, cat: "Decoração", era: 1 },
  { name: "Lareira Nemediana", min: 179, max: 215, cat: "Decoração", era: 2 },

  { name: "Estátua Turaniana", min: 18, max: 21, cat: "Decoração", era: 1 },
  { name: "Brasero Turaniano", min: 38, max: 45, cat: "Decoração", era: 1 },
  { name: "Luminária de Pé Turaniana", min: 38, max: 45, cat: "Decoração", era: 1 },
  { name: "Caneca Turaniana", min: 3, max: 3, cat: "Decoração", era: 1 },
  { name: "Jarra Turaniana", min: 13, max: 15, cat: "Decoração", era: 1 },
  { name: "Luminária Suspensa Turaniana", min: 38, max: 45, cat: "Decoração", era: 1 },
  { name: "Banco Turaniano", min: 20, max: 24, cat: "Decoração", era: 1 },

  { name: "Brasero Khitaniano", min: 25, max: 30, cat: "Decoração", era: 1 },
  { name: "Gato de Jade", min: 6, max: 8, cat: "Decoração", era: 1 },
  { name: "Caldeirão de Ferro", min: 25, max: 30, cat: "Decoração", era: 1 },
  { name: "Assento de Madeira Khitaniano", min: 10, max: 12, cat: "Decoração", era: 1 },
  { name: "Pote Khitaniano", min: 25, max: 30, cat: "Decoração", era: 1 },
  { name: "Zheng Khitaniano", min: 170, max: 204, cat: "Decoração", era: 1 },
  { name: "Mesa Khitaniana", min: 10, max: 12, cat: "Decoração", era: 1 },

{ name: "Biombo Dobrável Khitaniano", min: 170, max: 204, cat: "DLC", era: 1 },
  { name: "Ídolo Dragão Khitaniano", min: 19, max: 23, cat: "DLC", era: 1 },
  { name: "Apoio para Pés Khitaniano", min: 10, max: 12, cat: "DLC", era: 1 },
  { name: "Tapeçaria Khitaniana", min: 170, max: 204, cat: "DLC", era: 1 },
  { name: "Lâmpada Khitaniana", min: 8, max: 9, cat: "DLC", era: 1 },
  { name: "Tambor Khitaniano", min: 55, max: 66, cat: "DLC", era: 1 },
  { name: "Tapete Khitaniano", min: 11, max: 14, cat: "DLC", era: 1 },
  { name: "Cadeira Khitaniana", min: 10, max: 12, cat: "DLC", era: 1 },
  { name: "Vaso Khitaniano", min: 25, max: 30, cat: "DLC", era: 1 },
  { name: "Estátua de Legionário Khitaniana", min: 52, max: 62, cat: "DLC", era: 2 },

  { name: "Biombo Dobrável Aquiloniano", min: 40, max: 48, cat: "DLC", era: 1 },
  { name: "Cama de Solteiro Ornamentada", min: 29, max: 35, cat: "DLC", era: 1 },
  { name: "Penteadeira Aquiloniana", min: 21, max: 25, cat: "DLC", era: 1 },
  { name: "Brasero Aquiloniano", min: 74, max: 89, cat: "DLC", era: 1 },
  { name: "Brasero Aquiloniano (Pequeno)", min: 19, max: 23, cat: "DLC", era: 1 },
  { name: "Cadeira de Conselheiro Aquiloniana", min: 70, max: 84, cat: "DLC", era: 1 },
  { name: "Cadeira Aquiloniana", min: 35, max: 42, cat: "DLC", era: 1 },
  { name: "Cadeira Aquiloniana (Luxo)", min: 44, max: 53, cat: "DLC", era: 1 },
  { name: "Divã Aquiloniano", min: 30, max: 36, cat: "DLC", era: 1 },
  { name: "Escrivaninha Aquiloniana", min: 40, max: 48, cat: "DLC", era: 1 },
  { name: "Bandeira Aquiloniana", min: 157, max: 188, cat: "DLC", era: 1 },
  { name: "Harpa", min: 60, max: 72, cat: "DLC", era: 1 },
  { name: "Jarro Aquiloniano", min: 13, max: 15, cat: "DLC", era: 1 },
  { name: "Estátua Aquiloniana (Pequena)", min: 25, max: 30, cat: "DLC", era: 1 },
  { name: "Estátua Aquiloniana (Média)", min: 38, max: 45, cat: "DLC", era: 1 },
  { name: "Estátua Aquiloniana (Grande)", min: 63, max: 75, cat: "DLC", era: 1 },
  { name: "Mesa Aquiloniana", min: 30, max: 36, cat: "DLC", era: 1 },
  { name: "Tocha de Parede Aquiloniana", min: 9, max: 11, cat: "DLC", era: 1 },
  { name: "Tapete Aquiloniano", min: 150, max: 180, cat: "DLC", era: 1 },

  { name: "Cama Argossiana", min: 29, max: 35, cat: "DLC", era: 1 },
  { name: "Brasero Argossiano", min: 19, max: 23, cat: "DLC", era: 1 },
  { name: "Cadeira Argossiana", min: 20, max: 24, cat: "DLC", era: 1 },
  { name: "Escrivaninha Argossiana", min: 40, max: 48, cat: "DLC", era: 1 },
  { name: "Bandeira Argossiana", min: 157, max: 188, cat: "DLC", era: 1 },
  { name: "Estátua Argossiana", min: 13, max: 15, cat: "DLC", era: 1 },
  { name: "Mesa Argossiana", min: 20, max: 24, cat: "DLC", era: 1 },
  { name: "Tocha de Parede Argossiana", min: 9, max: 11, cat: "DLC", era: 1 },
  { name: "Tapete Argossiano", min: 8, max: 9, cat: "DLC", era: 1 },
  { name: "Tapeçaria Argossiana", min: 11, max: 14, cat: "DLC", era: 1 },
  { name: "Fonte Argossiana", min: 1009, max: 1211, cat: "DLC", era: 1 },

  { name: "(Garden) Bitter Crinila", min: 185, max: 222, cat: "Feito na Mão", era: 1 },
  { name: "(Garden) Blue Bell", min: 185, max: 222, cat: "Feito na Mão", era: 1 },
  { name: "(Garden) Dragonfern", min: 185, max: 222, cat: "Feito na Mão", era: 1 },
  { name: "(Garden) Forestry", min: 130, max: 156, cat: "Feito na Mão", era: 1 },
  { name: "(Planter) Indoor", min: 185, max: 222, cat: "Feito na Mão", era: 1 },
  { name: "(Planter) Outdoor", min: 185, max: 222, cat: "Feito na Mão", era: 1 },
  { name: "(Planter) Temple", min: 130, max: 156, cat: "Feito na Mão", era: 1 },

  { name: "Armadilha para Mariscos", min: 58, max: 69, cat: "Feito na Mão", era: 1 },
  { name: "Armadilha para Peixes", min: 58, max: 69, cat: "Feito na Mão", era: 1 },
  { name: "Caixa de Madeira", min: 34, max: 41, cat: "Feito na Mão", era: 1 },
  { name: "Chicken Coop", min: 400, max: 480, cat: "Feito na Mão", era: 1 },
  { name: "Compost Box", min: 16, max: 20, cat: "Feito na Mão", era: 1 },
  { name: "Composteira", min: 100, max: 120, cat: "Feito na Mão", era: 1 },
  { name: "Crude Hanging Planter", min: 10, max: 12, cat: "Feito na Mão", era: 1 },
  { name: "Eggs Incubator", min: 50, max: 60, cat: "Feito na Mão", era: 1 },
  { name: "Eggs Sorter", min: 40, max: 48, cat: "Feito na Mão", era: 1 },
  { name: "Estandarte de Batalha", min: 325, max: 390, cat: "Feito na Mão", era: 1 },
  { name: "Flechas da Forja do Vazio (10x)", min: 5, max: 6, cat: "Feito na Mão", era: 1 },
  { name: "Grand Chest", min: 188, max: 225, cat: "Feito na Mão", era: 1 },
  { name: "Hanging Planter", min: 49, max: 59, cat: "Feito na Mão", era: 1 },
  { name: "Jardineira", min: 225, max: 270, cat: "Feito na Mão", era: 1 },
  { name: "Jardineira Rudimentar", min: 69, max: 83, cat: "Feito na Mão", era: 1 },
  { name: "Large Chest, Baú Grande", min: 94, max: 113, cat: "Feito na Mão", era: 1 },
  { name: "Palco", min: 3, max: 3, cat: "Feito na Mão", era: 1 },
  { name: "Palco Brilhante", min: 10, max: 12, cat: "Feito na Mão", era: 1 },
  { name: "Simple Water Capture", min: 11, max: 14, cat: "Feito na Mão", era: 1 },
  { name: "Standing Skull Torch", min: 5, max: 6, cat: "Feito na Mão", era: 1 },
  { name: "Straw Mannequin", min: 9, max: 11, cat: "Feito na Mão", era: 1 },
  { name: "Tocha de Encaixe", min: 3, max: 4, cat: "Feito na Mão", era: 1 },
  { name: "Tocha Protegida", min: 16, max: 20, cat: "Feito na Mão", era: 1 },
  { name: "Tocha Vertical", min: 5, max: 6, cat: "Feito na Mão", era: 1 },
  { name: "Water Bucket", min: 58, max: 69, cat: "Feito na Mão", era: 1 },
  { name: "Wooden Shelf 1, 2, 3", min: 6, max: 8, cat: "Feito na Mão", era: 1 },
  { name: "Written Note", min: 1, max: 2, cat: "Feito na Mão", era: 1 },

  { name: "Cage Pen", min: 1337, max: 1605, cat: "Feito na Mão", era: 2 },
  { name: "Strongbox", min: 435, max: 522, cat: "Feito na Mão", era: 2 },
  { name: "Improved Hanging Planter", min: 155, max: 186, cat: "Feito na Mão", era: 2 },
  { name: "Jardineira Melhorada", min: 1340, max: 1608, cat: "Feito na Mão", era: 2 },

  { name: "Sala do Mapa", min: 9070, max: 10884, cat: "Feito na Mão", era: 3 },
  { name: "Caixa de Preservação", min: 444, max: 532, cat: "Feito na Mão", era: 3 },

  { name: "Caixa de Preservação Aprimorada", min: 860, max: 1032, cat: "Feito na Mão", era: 4 },

  { name: "Árbor", min: 358, max: 429, cat: "Bench", era: 1 },
  { name: "Bonsai Tree", min: 8, max: 10, cat: "Bench", era: 1 },
  { name: "Bonsai Tree (Large)", min: 8, max: 10, cat: "Bench", era: 1 },
  { name: "Calyx Krater", min: 8, max: 9, cat: "Bench", era: 1 },
  { name: "Coniferous Tree (Potted)", min: 463, max: 555, cat: "Bench", era: 1 },
  { name: "Árvore Decorativa", min: 138, max: 165, cat: "Bench", era: 1 },
  { name: "Decorative Bush", min: 159, max: 191, cat: "Bench", era: 1 },
  { name: "Garden Box, Sandstone", min: 202, max: 242, cat: "Bench", era: 1 },
  { name: "Garden Box, Stonebrick", min: 266, max: 319, cat: "Bench", era: 1 },
  { name: "Garden Wedge, Sandstone", min: 105, max: 126, cat: "Bench", era: 1 },

  { name: "Garden Wedge, Stonebrick", min: 135, max: 162, cat: "Horticultura", era: 1 },
  { name: "Hanging Plant", min: 19, max: 23, cat: "Horticultura", era: 1 },
  { name: "Ivy", min: 8, max: 9, cat: "Horticultura", era: 1 },
  { name: "Large Flower Pot / Stamnos / Urn", min: 8, max: 9, cat: "Horticultura", era: 1 },
  { name: "Large Tree", min: 484, max: 581, cat: "Horticultura", era: 1 },
  { name: "Medium Tree", min: 321, max: 385, cat: "Horticultura", era: 1 },
  { name: "Mushroom Box", min: 10, max: 12, cat: "Horticultura", era: 1 },
  { name: "Mushroom Box (Large)", min: 214, max: 257, cat: "Horticultura", era: 1 },
  { name: "Planter", min: 69, max: 83, cat: "Horticultura", era: 1 },
  { name: "Small Flower Pot", min: 4, max: 5, cat: "Horticultura", era: 1 },
  { name: "Small Tree", min: 159, max: 191, cat: "Horticultura", era: 1 },
  { name: "Trellis", min: 53, max: 63, cat: "Horticultura", era: 1 },
  { name: "Wall Planter", min: 30, max: 36, cat: "Horticultura", era: 1 },
  { name: "Water Planter", min: 94, max: 113, cat: "Horticultura", era: 1 },

  { name: "Garden Box, Insulated Wood", min: 516, max: 620, cat: "Horticultura", era: 2 },
  { name: "Garden Box, Reinforced Stone", min: 448, max: 537, cat: "Horticultura", era: 2 },
  { name: "Garden Wedge, Insulated Wood", min: 420, max: 504, cat: "Horticultura", era: 2 },
  { name: "Garden Wedge, Reinforced Stone", min: 249, max: 298, cat: "Horticultura", era: 2 },
  { name: "Garden Wedge, Black Ice", min: 235, max: 282, cat: "Horticultura", era: 3 },
  { name: "Garden Box, Black Ice", min: 423, max: 508, cat: "Horticultura", era: 3 },

  { name: "(Statue) Horse", min: 69, max: 83, cat: "Woodwork", era: 1 },
  { name: "Apothecary Counter", min: 50, max: 60, cat: "Woodwork", era: 1 },
  { name: "Apothecary Shelf", min: 90, max: 108, cat: "Woodwork", era: 1 },
  { name: "Arbor", min: 75, max: 90, cat: "Woodwork", era: 1 },
  { name: "Axe Decor", min: 41, max: 50, cat: "Woodwork", era: 1 },
  { name: "Banner (Bandeira)", min: 10, max: 12, cat: "Woodwork", era: 1 },
  { name: "Banner Large", min: 40, max: 48, cat: "Woodwork", era: 1 },
  { name: "Banner Medium", min: 25, max: 30, cat: "Woodwork", era: 1 },
  { name: "Banner Small", min: 10, max: 12, cat: "Woodwork", era: 1 },

  { name: "Bed Fancy", min: 240, max: 288, cat: "Woodwork", era: 1 },
  { name: "Bed Old", min: 100, max: 120, cat: "Woodwork", era: 1 },
  { name: "Boar Corpse", min: 403, max: 483, cat: "Woodwork", era: 1 },
  { name: "Bonfire", min: 18, max: 21, cat: "Woodwork", era: 1 },
  { name: "Book A-B-C", min: 244, max: 293, cat: "Woodwork", era: 1 },
  { name: "Bookshelf A Large", min: 400, max: 480, cat: "Woodwork", era: 1 },
  { name: "Bookshelf A-B", min: 200, max: 240, cat: "Woodwork", era: 1 },
  { name: "Brazier", min: 26, max: 32, cat: "Woodwork", era: 1 },
  { name: "Bucket", min: 45, max: 54, cat: "Woodwork", era: 1 },
  { name: "Cabinet", min: 50, max: 60, cat: "Woodwork", era: 1 },
  { name: "Collection of Scrolls", min: 731, max: 878, cat: "Woodwork", era: 1 },
  { name: "Corpse Guts", min: 400, max: 480, cat: "Woodwork", era: 1 },
  { name: "Covered Trap", min: 495, max: 594, cat: "Woodwork", era: 1 },
  { name: "Crafting Table", min: 30, max: 36, cat: "Woodwork", era: 1 },
  { name: "Death/Frost Fire", min: 19, max: 23, cat: "Woodwork", era: 1 },
  { name: "Desk", min: 40, max: 48, cat: "Woodwork", era: 1 },
  { name: "Desk Chair", min: 30, max: 36, cat: "Woodwork", era: 1 },
  { name: "Elegant Bench", min: 125, max: 150, cat: "Woodwork", era: 1 },
  { name: "Elegant Bookshelf A", min: 225, max: 270, cat: "Woodwork", era: 1 },
  { name: "Elegant Bookshelf B & C", min: 250, max: 300, cat: "Woodwork", era: 1 },
  { name: "Elegant Stool", min: 25, max: 30, cat: "Woodwork", era: 1 },
  { name: "Engraved Barrel", min: 48, max: 57, cat: "Woodwork", era: 1 },
  { name: "Extravagant Potion Bottle", min: 6, max: 8, cat: "Woodwork", era: 1 },
  { name: "Extravagant Potion Bottle Small", min: 4, max: 5, cat: "Woodwork", era: 1 },
  { name: "Feather Pen", min: 3, max: 3, cat: "Woodwork", era: 1 },
  { name: "Fine Rug", min: 35, max: 42, cat: "Woodwork", era: 1 },
  { name: "Frost Fire Standing Torch", min: 33, max: 39, cat: "Woodwork", era: 1 },
  { name: "Gazelle Corpse", min: 403, max: 483, cat: "Woodwork", era: 1 },
  { name: "Herb Cabinet", min: 60, max: 72, cat: "Woodwork", era: 1 },
  { name: "Herb Bins", min: 40, max: 48, cat: "Woodwork", era: 1 },
  { name: "High Chair", min: 25, max: 30, cat: "Woodwork", era: 1 },
  { name: "Keg", min: 243, max: 291, cat: "Woodwork", era: 1 },
  { name: "Large Bowl", min: 15, max: 18, cat: "Woodwork", era: 1 },
  { name: "Large Hide Rug", min: 38, max: 45, cat: "Woodwork", era: 1 },
  { name: "Lattice", min: 40, max: 48, cat: "Woodwork", era: 1 },
  { name: "Lattice Pattern", min: 30, max: 36, cat: "Woodwork", era: 1 },
  { name: "Lattice Small", min: 20, max: 24, cat: "Woodwork", era: 1 },
  { name: "Magister's Storage Chest", min: 31, max: 38, cat: "Woodwork", era: 1 },
  { name: "Mammoth Skull", min: 75, max: 90, cat: "Woodwork", era: 1 },
  { name: "Old Chair", min: 35, max: 42, cat: "Woodwork", era: 1 },
  { name: "Old Shelf", min: 15, max: 18, cat: "Woodwork", era: 1 },
  { name: "Old Table", min: 75, max: 90, cat: "Woodwork", era: 1 },
  { name: "Ornate Bench", min: 25, max: 30, cat: "Woodwork", era: 1 },
  { name: "Ornate Bookshelf A", min: 75, max: 90, cat: "Woodwork", era: 1 },
  { name: "Ornate Bookshelf B", min: 100, max: 120, cat: "Woodwork", era: 1 },
  { name: "Ornate Chair", min: 25, max: 30, cat: "Woodwork", era: 1 },
  { name: "Ornate End Table A & B", min: 25, max: 30, cat: "Woodwork", era: 1 },
  { name: "Ornate High Chair", min: 50, max: 60, cat: "Woodwork", era: 1 },
  { name: "Ornate Shelf", min: 125, max: 150, cat: "Woodwork", era: 1 },
  { name: "Ornate Table A & B", min: 125, max: 150, cat: "Woodwork", era: 1 },
  { name: "Ornate Table C & D", min: 150, max: 180, cat: "Woodwork", era: 1 },
  { name: "Ornate Wall Shelf", min: 25, max: 30, cat: "Woodwork", era: 1 },
  { name: "Ornate Weapon Rack", min: 100, max: 120, cat: "Woodwork", era: 1 },
  { name: "Pepper (Qualquer um)", min: 125, max: 150, cat: "Woodwork", era: 1 },
  { name: "Personal Journal", min: 4, max: 5, cat: "Woodwork", era: 1 },
  { name: "Protected Brazier", min: 56, max: 68, cat: "Woodwork", era: 1 },
  { name: "Rhino Corpse", min: 403, max: 483, cat: "Woodwork", era: 1 },
  { name: "Round Rug", min: 25, max: 30, cat: "Woodwork", era: 1 },
  { name: "Rug", min: 35, max: 42, cat: "Woodwork", era: 1 },
  { name: "Scholar Bed", min: 175, max: 210, cat: "Woodwork", era: 1 },
  { name: "Scribe Table", min: 75, max: 90, cat: "Woodwork", era: 1 },
  { name: "Scroll A-F", min: 244, max: 293, cat: "Woodwork", era: 1 },
  { name: "Shadow Throne", min: 329, max: 395, cat: "Woodwork", era: 1 },
  { name: "Shelf", min: 125, max: 150, cat: "Woodwork", era: 1 },
  { name: "Shipwreck A-F", min: 125, max: 150, cat: "Woodwork", era: 1 },
  { name: "Shrine of Mitra", min: 559, max: 671, cat: "Woodwork", era: 1 },
  { name: "Shrine of Kildora", min: 559, max: 671, cat: "Woodwork", era: 1 },

  { name: "Small Bowl", min: 10, max: 12, cat: "Working Bench", era: 1 },
  { name: "Spirit Fire Bracket Torch", min: 47, max: 56, cat: "Working Bench", era: 1 },
  { name: "Spirit Fire Standing Torch", min: 55, max: 65, cat: "Working Bench", era: 1 },
  { name: "Step Stool", min: 15, max: 18, cat: "Working Bench", era: 1 },
  { name: "Stone Column", min: 110, max: 132, cat: "Working Bench", era: 1 },
  { name: "Stone Wall", min: 138, max: 165, cat: "Working Bench", era: 1 },
  { name: "Stormhold Large Carpet", min: 150, max: 180, cat: "Working Bench", era: 1 },
  { name: "Temple Torch", min: 8, max: 9, cat: "Working Bench", era: 1 },
  { name: "The Ascension Call / The Iron Warhorn", min: 198, max: 237, cat: "Working Bench", era: 1 },
  { name: "Wall Hide Rug", min: 53, max: 63, cat: "Working Bench", era: 1 },
  { name: "Wall Lantern", min: 30, max: 36, cat: "Working Bench", era: 1 },
  { name: "Wall Shelf", min: 15, max: 18, cat: "Working Bench", era: 1 },
  { name: "Wall Shelf Small", min: 10, max: 12, cat: "Working Bench", era: 1 },
  { name: "Wall Skull A B C", min: 75, max: 90, cat: "Working Bench", era: 1 },
  { name: "Wardrobe", min: 288, max: 345, cat: "Working Bench", era: 1 },
  { name: "Warhorn", min: 135, max: 162, cat: "Working Bench", era: 1 },
  { name: "White Oak Chair", min: 30, max: 36, cat: "Working Bench", era: 1 },
  { name: "White Oak Wardrobe", min: 150, max: 180, cat: "Working Bench", era: 1 },

  { name: "(Statue) Lion Shadow Inazayus Uthar", min: 183, max: 219, cat: "Working Bench", era: 2 },
  { name: "(Statue) Empyrus Knight", min: 512, max: 614, cat: "Working Bench", era: 2 },
  { name: "(Statue) Errynya", min: 732, max: 878, cat: "Working Bench", era: 2 },
  { name: "(Statue) Frost Hound", min: 294, max: 353, cat: "Working Bench", era: 2 },
  { name: "(Statue) Kyloth", min: 2167, max: 2601, cat: "Working Bench", era: 2 },
  { name: "(Statue) Moon Leopard", min: 256, max: 307, cat: "Working Bench", era: 2 },
  { name: "(Statue) Yezvaron", min: 431, max: 517, cat: "Working Bench", era: 2 },

  { name: "(Trophy) Avançado", min: 2500, max: 3000, cat: "Working Bench", era: 2 },
  { name: "Ancient Lockbox", min: 1423, max: 1708, cat: "Working Bench", era: 2 },
  { name: "Barrel", min: 276, max: 331, cat: "Working Bench", era: 2 },
  { name: "Council Throne", min: 836, max: 1003, cat: "Working Bench", era: 2 },
  { name: "Covenant Wall Lantern", min: 103, max: 124, cat: "Working Bench", era: 2 },
  { name: "Damned Throne", min: 245, max: 294, cat: "Working Bench", era: 2 },
  { name: "Old Chest", min: 260, max: 312, cat: "Working Bench", era: 2 },
  { name: "Solid Cage", min: 201, max: 241, cat: "Working Bench", era: 2 },
  { name: "Statue of Theron", min: 7327, max: 8792, cat: "Working Bench", era: 2 },
  { name: "Temple Candlestick", min: 1262, max: 1515, cat: "Working Bench", era: 2 },
  { name: "Temple Statue", min: 189, max: 227, cat: "Working Bench", era: 2 },
  { name: "Tomb of Essari", min: 105, max: 126, cat: "Working Bench", era: 2 },
  { name: "Tombstone A B C D", min: 73, max: 88, cat: "Working Bench", era: 2 },
  { name: "Tombstone E", min: 146, max: 176, cat: "Working Bench", era: 2 },
  { name: "Wall Chains", min: 107, max: 128, cat: "Working Bench", era: 2 },
  { name: "White Throne", min: 907, max: 1088, cat: "Working Bench", era: 2 },

  { name: "(Statue) Arxeous", min: 2900, max: 3480, cat: "Working Bench", era: 3 },
  { name: "(Statue) Scargath", min: 4486, max: 5383, cat: "Working Bench", era: 3 },
  { name: "(Statue) Scourge Rabbit", min: 922, max: 1106, cat: "Working Bench", era: 3 },
  { name: "(Trophy) Lendário", min: 7500, max: 9000, cat: "Working Bench", era: 3 },
  { name: "(Trophy) Raro", min: 5000, max: 6000, cat: "Working Bench", era: 3 },
  { name: "(Trophy) Scourge Undead", min: 1875, max: 2250, cat: "Working Bench", era: 3 },

  { name: "Arcane Vault", min: 6612, max: 7934, cat: "Working Bench", era: 3 },
  { name: "Crescent Oculus", min: 9512, max: 11415, cat: "Working Bench", era: 3 },
  { name: "Dark Marble Table", min: 513, max: 616, cat: "Working Bench", era: 3 },
  { name: "Dragon Skull", min: 3950, max: 4740, cat: "Working Bench", era: 3 },
  { name: "Explosive Barrel Keg of Black Powder", min: 1104, max: 1324, cat: "Working Bench", era: 3 },
  { name: "Large Frost Brazier", min: 4403, max: 5284, cat: "Working Bench", era: 3 },
  { name: "Lion Shield", min: 1155, max: 1386, cat: "Working Bench", era: 3 },
  { name: "Magus Statue", min: 1733, max: 2079, cat: "Working Bench", era: 3 },
  { name: "Relic Stand", min: 116, max: 139, cat: "Working Bench", era: 3 },
  { name: "Royal Storage Container", min: 509, max: 610, cat: "Working Bench", era: 3 },
  { name: "Shadow Chest", min: 762, max: 914, cat: "Working Bench", era: 3 },
  { name: "Vault of the Damned", min: 5254, max: 6305, cat: "Working Bench", era: 3 },

  { name: "High Elder Throne", min: 8873, max: 10647, cat: "Working Bench", era: 4 },
  { name: "Highborn Throne", min: 9581, max: 11497, cat: "Working Bench", era: 4 },
  { name: "Fountain of Nourishment", min: 3885, max: 4662, cat: "Working Bench", era: 4 },

  { name: "(Statue) Gold Lion", min: 2342, max: 2811, cat: "Working Bench", era: 5 },
  { name: "Arcane Prison", min: 8380, max: 10056, cat: "Working Bench", era: 5 },
  { name: "Cage Prison", min: 7078, max: 8493, cat: "Working Bench", era: 5 },
  { name: "Frozen Throne", min: 5741, max: 6889, cat: "Working Bench", era: 5 },
  { name: "Globet", min: 781, max: 937, cat: "Working Bench", era: 5 },
  { name: "Gold Lion Fountain", min: 3562, max: 4274, cat: "Working Bench", era: 5 },
  { name: "Golden Throne", min: 2672, max: 3206, cat: "Working Bench", era: 5 },
  { name: "Hammer of Justice", min: 21830, max: 26196, cat: "Working Bench", era: 5 },
  { name: "Horse / Lion / Moon Fountain", min: 3562, max: 4274, cat: "Working Bench", era: 5 },
  { name: "Lion Shield Gold", min: 3904, max: 4685, cat: "Working Bench", era: 5 },
  { name: "Lion Throne of Stormhold", min: 29815, max: 35778, cat: "Working Bench", era: 5 },
  { name: "Malagan Fountain", min: 3028, max: 3634, cat: "Working Bench", era: 5 },
  { name: "Moon Bowl", min: 810, max: 972, cat: "Working Bench", era: 5 },
  { name: "Rhino / Shadow Fountain", min: 3562, max: 4274, cat: "Working Bench", era: 5 },
  { name: "Shadow / Kingdom Siege Foundation", min: 1767, max: 2120, cat: "Working Bench", era: 5 },
  { name: "Shadow / Kingdom Trebuchet", min: 1183, max: 1419, cat: "Working Bench", era: 5 },
  { name: "Soul Prison", min: 5186, max: 6224, cat: "Working Bench", era: 5 },
  { name: "Summoning Altar", min: 5359, max: 6431, cat: "Working Bench", era: 5 },
  { name: "Warden's Gibbet", min: 8042, max: 9651, cat: "Working Bench", era: 5 },

  { name: "Eveirium Bow", min: 16244, max: 19493, cat: "Insanity", era: 5 },
  { name: "Crescent Bow", min: 2545, max: 3054, cat: "Insanity", era: 5 },
  { name: "Velian Bow", min: 7892, max: 9470, cat: "Insanity", era: 6 },
  { name: "Kronynxium Bow", min: 75619, max: 90743, cat: "Insanity", era: 6 },

  { name: "BD Alchemy Box", min: 28, max: 55, cat: "BD", era: 1 },
  { name: "BD Alchemy Calcinator", min: 28, max: 55, cat: "BD", era: 1 },
  { name: "BD Amulet 01", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Ankh", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Antique Bar 01 Brown", min: 200, max: 400, cat: "BD", era: 1 },
  { name: "BD Apple 01A", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Apple Group 01 D", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Armchair 01", min: 250, max: 500, cat: "BD", era: 1 },
  { name: "BD Armchair 02", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Armchair 03,04", min: 150, max: 300, cat: "BD", era: 1 },
  { name: "BD Armchair 05", min: 120, max: 240, cat: "BD", era: 1 },
  { name: "BD Armoire 01,02", min: 150, max: 300, cat: "BD", era: 1 },
  { name: "BD Arrow Box-A", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Artist Palette 01-A", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Astrolabe", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Bacon 01", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Bag 01,02", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Bakery 01-A", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Bale 01-A (S)", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Bamboo Fountain", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Banana 01-A", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Bandage 01", min: 37, max: 74, cat: "BD", era: 1 },
  { name: "BD Barrel 01-07", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Barrel Stand 01-A", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Basin 01-03", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Basket 01-09", min: 25, max: 49, cat: "BD", era: 1 },
  { name: "BD Bath 01", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Bath 01-White", min: 72, max: 143, cat: "BD", era: 1 },
  { name: "BD Bath 02-A (L)", min: 242, max: 484, cat: "BD", era: 1 },
  { name: "BD Bed 01-06 (Solteiro)", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Bed 01-Grey", min: 113, max: 225, cat: "BD", era: 1 },
  { name: "BD Bed 02-07 (Casal)", min: 300, max: 600, cat: "BD", era: 1 },
  { name: "BD Bedroll-B", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Beet 01", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Bench 01", min: 61, max: 121, cat: "BD", era: 1 },
  { name: "BD Bench 01-06", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Berries 01-A", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Big Sushi-A", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Biscuit 01-A", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Board 01-A", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Bones 02-04", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Book 01-05", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Book Basket", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Book Row 01 Stack 01", min: 55, max: 110, cat: "BD", era: 1 },
  { name: "BD Bookshelf 01 A", min: 150, max: 300, cat: "BD", era: 1 },
  { name: "BD Bookshelf 01-05", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Bookshelf 02-A", min: 200, max: 400, cat: "BD", era: 1 },
  { name: "BD Boots 01", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Bottle 01-06", min: 45, max: 90, cat: "BD", era: 1 },
  { name: "BD Bowl 01,04,05,07,09-12", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Bowl 02-Stack", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Bowl 02,08,14-19,21", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Bowl 03,06,13,20", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Box 01", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Box 01,02", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Box 02-A", min: 44, max: 88, cat: "BD", era: 1 },
  { name: "BD Box 03", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Box 04-09", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Box 10,11", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Brazier 01-A", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Bread 01-A", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Broom", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Bucket 01,02", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Burner 01", min: 49, max: 98, cat: "BD", era: 1 },
  { name: "BD Butter Churn 01", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Butterfly Jar", min: 49, max: 98, cat: "BD", era: 1 },
  { name: "BD Cabbage 01-A", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Cabinet 01", min: 200, max: 400, cat: "BD", era: 1 },
  { name: "BD Cabinet 01-02", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Cabinet 02,06", min: 100, max: 200, cat: "BD", era: 1 },
  { name: "BD Cabinet 03", min: 300, max: 600, cat: "BD", era: 1 },
  { name: "BD Cabinet 04,05,07", min: 150, max: 300, cat: "BD", era: 1 },
  { name: "BD Cage 01", min: 49, max: 98, cat: "BD", era: 1 },
  { name: "BD Calligraphy 01", min: 49, max: 98, cat: "BD", era: 1 },
  { name: "BD Campfire Grill Rail Tripod", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Candelabrum 01", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Candle 01-03", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Candle 02-A", min: 82, max: 164, cat: "BD", era: 1 },
  { name: "BD Candle Box 01", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Candlestick 01-A", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Candlestick 01,03", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Canopy 01-A (S)", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Canvas 01", min: 49, max: 98, cat: "BD", era: 1 },
  { name: "BD Carrot 01-A", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Casino Card Group", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Cauldron 01,02", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Cauldron 03", min: 62, max: 123, cat: "BD", era: 1 },
  { name: "BD Chair 01-07", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Chair 01,08", min: 154, max: 308, cat: "BD", era: 1 },
  { name: "BD Chair 02", min: 120, max: 240, cat: "BD", era: 1 },
  { name: "BD Chair 04,05", min: 150, max: 300, cat: "BD", era: 1 },
  { name: "BD Chair 07", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Chair 10", min: 120, max: 240, cat: "BD", era: 1 },
  { name: "BD Chalice 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Chandelier 01", min: 55, max: 110, cat: "BD", era: 1 },
  { name: "BD Chandelier 01-A", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Charcoal", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Cheese 01-05", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Chest 01-03 Storage", min: 66, max: 132, cat: "BD", era: 1 },
  { name: "BD Chest 01-04,07", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Chest 05,06", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Chicken 01,02", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Chili Pepper 01", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Chopstick 01", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Cleaver 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Climbing Ivy", min: 62, max: 123, cat: "BD", era: 1 },
  { name: "BD Cloth 01-04", min: 44, max: 88, cat: "BD", era: 1 },
  { name: "BD Cloth 05", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Cloth Hanger 01", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Clothes Line", min: 49, max: 98, cat: "BD", era: 1 },
  { name: "BD Coal Tray", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Coffee Grinder", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Coffee Pot", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Coin Pile", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Comb 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Commode 01", min: 66, max: 132, cat: "BD", era: 1 },
  { name: "BD Commode 02,03,05-07", min: 100, max: 200, cat: "BD", era: 1 },
  { name: "BD Commode 04", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Compass 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Cookie 01-A", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Cooking Pot 01", min: 45, max: 90, cat: "BD", era: 1 },
  { name: "BD Cooking Pot 02", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Cooking Spatula", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Cooking Stand 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Cooking Station 01-04", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Corn 01", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Cover Ivy 01", min: 62, max: 123, cat: "BD", era: 1 },
  { name: "BD Couch 01,03", min: 150, max: 300, cat: "BD", era: 1 },
  { name: "BD Couch 02", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Counter 01-04", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Crate 01-10", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Croissant 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Crystal Ball", min: 55, max: 110, cat: "BD", era: 1 },
  { name: "BD Crystal Ball (Large)", min: 121, max: 242, cat: "BD", era: 1 },
  { name: "BD Crystal Ball 02", min: 90, max: 180, cat: "BD", era: 1 },
  { name: "BD Cucumber 01", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Cup 01-03,07,08", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Cup 03", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Cup 04,06", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Cup 05", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Curtain 01", min: 44, max: 88, cat: "BD", era: 1 },
  { name: "BD Curtain 01-A", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Curtain 02", min: 44, max: 88, cat: "BD", era: 1 },
  { name: "BD Cushion 01,03-05", min: 44, max: 88, cat: "BD", era: 1 },
  { name: "BD Dagger 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Decorative Archway 01 (S)", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Desk 01", min: 66, max: 132, cat: "BD", era: 1 },
  { name: "BD Desk 01,03", min: 100, max: 200, cat: "BD", era: 1 },
  { name: "BD Desk 02", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Dessert 01-A,02", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Dice 01,02", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Distiller 01", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Distiller 02,03", min: 55, max: 110, cat: "BD", era: 1 },
  { name: "BD Doily 01", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Dreamcatcher 01", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Easel 01", min: 62, max: 123, cat: "BD", era: 1 },
  { name: "BD Egg 01,02", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Eggplant 01", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Evil Eye 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Examination Table", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Feather 02,03", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Fireplace 01", min: 45, max: 90, cat: "BD", era: 1 },
  { name: "BD Fireplace 02", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Fish 01,02", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Flask 01-04 A", min: 114, max: 229, cat: "BD", era: 1 },
  { name: "BD Flask 01-08", min: 12, max: 24, cat: "BD", era: 1 },
  { name: "BD Floor Cushion 01", min: 44, max: 88, cat: "BD", era: 1 },
  { name: "BD Flower 01-27", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Flower 02-16,21", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Flower 18,19", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Folding Screen 01,02", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Food Display", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Food Platter 01", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Fork A", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Fountain 01", min: 242, max: 484, cat: "BD", era: 1 },
  { name: "BD Frame 01-05", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Frame 01,02,05", min: 44, max: 88, cat: "BD", era: 1 },
  { name: "BD Frame 03,04", min: 121, max: 242, cat: "BD", era: 1 },
  { name: "BD Gameboard 01-04", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Garlic 01,02", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Grape 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Grapefruit", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Grilled Fish", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Grilled Vegetable", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Haggis Ivy 01-04", min: 62, max: 123, cat: "BD", era: 1 },
  { name: "BD Hand Fan", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Hand Mirror", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Hand Torch", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Hanging Cloth 01-04", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Hanging Herb 01", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Hanging Horn 01", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Hanging Rack 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Hanging Rack 02", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Hanging Tassel 01-02", min: 44, max: 88, cat: "BD", era: 1 },
  { name: "BD Hanging Tray 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Hedge 01-A", min: 130, max: 260, cat: "BD", era: 1 },
  { name: "BD Herb 01 Hanging", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Herb 01,02", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Houglass 01", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Houglass 01-A", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Ingots 01-A", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Ink 01", min: 164, max: 328, cat: "BD", era: 1 },
  { name: "BD Inkstand 01", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Inkwell 02", min: 49, max: 98, cat: "BD", era: 1 },
  { name: "BD Ivy 01,02", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Jinxed Book Pile 01", min: 55, max: 110, cat: "BD", era: 1 },
  { name: "BD Jug 01-04,06-09", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Jug 05", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Kettle 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Kettle 01 A", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Kettle 02", min: 45, max: 90, cat: "BD", era: 1 },
  { name: "BD Kitchen Cabinet 02", min: 100, max: 200, cat: "BD", era: 1 },
  { name: "BD Kitchen Corner Inside", min: 100, max: 200, cat: "BD", era: 1 },
  { name: "BD Kitchen Counter 02", min: 100, max: 200, cat: "BD", era: 1 },
  { name: "BD Kitchen Sink 02", min: 100, max: 200, cat: "BD", era: 1 },
  { name: "BD Kitchen Stove", min: 83, max: 165, cat: "BD", era: 1 },
  { name: "BD Kitchen Stove 02", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Kitchen Tools 01,02", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Knife", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Kohl Eyeliner", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Ladder", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Ladle", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Lampset", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Lantern 01-04,06,10", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Lantern 05,07", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Leather Piece", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Leather Roll", min: 66, max: 132, cat: "BD", era: 1 },
  { name: "BD Leatherwork Tool", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Lemon, Lime", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Loom", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Magic Book", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Magnifying Glass 01", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Magnifying Glass 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Magnifying Glass 02", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Mango 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Mannequin 01", min: 121, max: 242, cat: "BD", era: 1 },
  { name: "BD Map 01,02", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Mattress 01", min: 44, max: 88, cat: "BD", era: 1 },
  { name: "BD Meal 01", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Medicine Box", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Medical Tool 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Melon 01", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Microscope", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Mirror 01", min: 44, max: 88, cat: "BD", era: 1 },
  { name: "BD Mirror 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Mixed Bouquet 01", min: 66, max: 132, cat: "BD", era: 1 },
  { name: "BD Mortar 01", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Mortar and Pestle 01,03,04", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Mortar and Pestle 02", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Muffin 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Mushroom 01 A", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Mushroom 01-04", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Narguile 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Nectarine 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Net 01", min: 62, max: 123, cat: "BD", era: 1 },
  { name: "BD Net 02", min: 37, max: 74, cat: "BD", era: 1 },
  { name: "BD Note", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Noticeboard 01", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Occult Cube 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Oil Cruet", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Oil Lamp 01", min: 45, max: 90, cat: "BD", era: 1 },
  { name: "BD Olives 01", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Onion 01-03, Orange", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Orange 01", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Ore 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Ouija Board", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Package 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Paint Brush", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Pan 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Pancake 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Peach, Pear", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Pedestal", min: 45, max: 90, cat: "BD", era: 1 },
  { name: "BD Pen", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Pendant", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Pepper 01,02", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Pig", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Pillow", min: 44, max: 88, cat: "BD", era: 1 },
  { name: "BD Pineapple 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Pitcher 01,02", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Plant 01", min: 33, max: 66, cat: "BD", era: 1 },
  { name: "BD Plant 01-29 A", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Planter 01", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Planter 01 A", min: 242, max: 484, cat: "BD", era: 1 },
  { name: "BD Plate 01-03", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Plate 04-09", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Plate 10-13", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Plate Set 01", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Plate Set 01 A", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Playing Cards", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Pomegranate", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Pork", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Pot 01-11,13-15", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Pot 12", min: 45, max: 90, cat: "BD", era: 1 },
  { name: "BD Potato 01,02", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Pouch", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Pouf 01,02", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Poultry 01-AA", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Powder Pot 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Prie-Dieu", min: 100, max: 200, cat: "BD", era: 1 },
  { name: "BD Pumpkin 01-03", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Quill 01", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Rag 01", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Ration Bag 01", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Rice Cake", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Ring", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Rock Ring", min: 62, max: 123, cat: "BD", era: 1 },
  { name: "BD Rocking Chair", min: 100, max: 200, cat: "BD", era: 1 },
  { name: "BD Roots 01", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Rope 01", min: 25, max: 49, cat: "BD", era: 1 },
  { name: "BD Rug 01-12", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Runes 01", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Sack 01-03", min: 37, max: 74, cat: "BD", era: 1 },
  { name: "BD Sake Bottle", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Sashimi", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Sausage 01,02", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Scale 01", min: 62, max: 123, cat: "BD", era: 1 },
  { name: "BD Scale 01,02", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Scented Candle", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Scoop", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Screen 01", min: 154, max: 308, cat: "BD", era: 1 },
  { name: "BD Screen 02", min: 154, max: 308, cat: "BD", era: 1 },
  { name: "BD Scroll 01-A", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Scroll 01,02", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Scroll 03", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Sealed Letter", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Seashell 01-03", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Serving Stand", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Serving Tray", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Serving Tray 02", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Shelf 01-07,09,10", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Shelf 01,02 A", min: 100, max: 200, cat: "BD", era: 1 },
  { name: "BD Shelf 08", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Shovel 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Side Table 01-08,10-17", min: 66, max: 132, cat: "BD", era: 1 },
  { name: "BD Side Table 01-Brown", min: 100, max: 200, cat: "BD", era: 1 },
  { name: "BD Side Table 02-05,07 Brown", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Side Table 06", min: 61, max: 121, cat: "BD", era: 1 },
  { name: "BD Small Crystal 01", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Small Fill A", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Small Sushi A", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Smoking Pipe/Set 01", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Soap 01", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Sofa 01", min: 250, max: 500, cat: "BD", era: 1 },
  { name: "BD Sofa 02,06,11", min: 120, max: 240, cat: "BD", era: 1 },
  { name: "BD Sofa 03,05,07,08-10", min: 250, max: 500, cat: "BD", era: 1 },
  { name: "BD Sofa 12-15", min: 150, max: 300, cat: "BD", era: 1 },
  { name: "BD Spatula 01 A", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Specimen Jar 01", min: 45, max: 90, cat: "BD", era: 1 },
  { name: "BD Spinning Wheel 01", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Spoon 01", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Spoon A", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Stained Glass 01,02", min: 97, max: 194, cat: "BD", era: 1 },
  { name: "BD Stake 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Stall 01,02,05-07", min: 150, max: 300, cat: "BD", era: 1 },
  { name: "BD Stall 03,04 A", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Stall Rack 01", min: 66, max: 132, cat: "BD", era: 1 },
  { name: "BD Stamp 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Standing Mirror 01", min: 100, max: 200, cat: "BD", era: 1 },
  { name: "BD Standing Mirror 02", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Statue 01 A", min: 61, max: 121, cat: "BD", era: 1 },
  { name: "BD Statue 01-05", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Statue 02,06,08 A", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Statue 06", min: 66, max: 132, cat: "BD", era: 1 },
  { name: "BD Statue 07 A", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Steak 01", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Stool 01 Brown", min: 100, max: 200, cat: "BD", era: 1 },
  { name: "BD Stool 01-05", min: 44, max: 88, cat: "BD", era: 1 },
  { name: "BD Stool 02,06 A Brown", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Stool 03", min: 150, max: 300, cat: "BD", era: 1 },
  { name: "BD Stool 04,05", min: 154, max: 308, cat: "BD", era: 1 },
  { name: "BD Storage Bin 01-03", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Stove 01", min: 125, max: 250, cat: "BD", era: 1 },
  { name: "BD Strawberry", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Sundial 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Stylus 01", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Sugar Bowl", min: 45, max: 90, cat: "BD", era: 1 },
  { name: "BD Swab 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Symbol 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Syringe 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Table 01-09", min: 66, max: 132, cat: "BD", era: 1 },
  { name: "BD Table 01,02,04-06 A Brown", min: 100, max: 200, cat: "BD", era: 1 },
  { name: "BD Table 03", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Table 07 A", min: 200, max: 400, cat: "BD", era: 1 },
  { name: "BD Tailor Tool 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Tall Sushi A", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Tankard 01", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Tanning Rack", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Tarot Cards 01", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Tea Cup/Plate 02", min: 45, max: 90, cat: "BD", era: 1 },
  { name: "BD Tea Set 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Teapot 01,02,04", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Teapot 03", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Tent 01", min: 150, max: 300, cat: "BD", era: 1 },
  { name: "BD Tent 02-04", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Test Tube 01", min: 68, max: 136, cat: "BD", era: 1 },
  { name: "BD Test Tube 02", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Toilet 01", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Tomato 01", min: 8, max: 16, cat: "BD", era: 1 },
  { name: "BD Tombstone 01,02", min: 45, max: 90, cat: "BD", era: 1 },
  { name: "BD Tool 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Torii Gate", min: 150, max: 300, cat: "BD", era: 1 },
  { name: "BD Towel Rack 01-A/B", min: 50, max: 99, cat: "BD", era: 1 },
  { name: "BD Towel Rack 02-A/B (Wall)", min: 50, max: 99, cat: "BD", era: 1 },
  { name: "BD Tree 01", min: 55, max: 110, cat: "BD", era: 1 },
  { name: "BD Trophy 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Urn 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Vanity 01", min: 150, max: 300, cat: "BD", era: 1 },
  { name: "BD Vase 01 A", min: 61, max: 121, cat: "BD", era: 1 },
  { name: "BD Vase 01-16 A", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Vase 06-08 A", min: 45, max: 90, cat: "BD", era: 1 },
  { name: "BD Vase 09", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Vase 10", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Vines 01,02 A", min: 41, max: 82, cat: "BD", era: 1 },
  { name: "BD Vorpal Blade", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Wagon 01,02", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Water Stand 01 A", min: 100, max: 200, cat: "BD", era: 1 },
  { name: "BD Wall Candle 01", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Wall Deco 01,03", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Wall Deco 02,04", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Wall Shelf 01,03 A", min: 66, max: 132, cat: "BD", era: 1 },
  { name: "BD Wall Shelf 02,04 A", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD Wall Sign 01-03 A", min: 22, max: 44, cat: "BD", era: 1 },
  { name: "BD War Table 01", min: 100, max: 200, cat: "BD", era: 1 },
  { name: "BD War Table Elements A", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Wardrobe 02,03 A", min: 110, max: 220, cat: "BD", era: 1 },
  { name: "BD Wasabi A", min: 44, max: 88, cat: "BD", era: 1 },
  { name: "BD Washboard 01,02", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Water Ladle 01", min: 4, max: 8, cat: "BD", era: 1 },
  { name: "BD Waterskin 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Wax Box", min: 88, max: 176, cat: "BD", era: 1 },
  { name: "BD Witchcraft Board 01", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Wood 01 A", min: 21, max: 41, cat: "BD", era: 1 },
  { name: "BD Writing Setup 02", min: 105, max: 209, cat: "BD", era: 1 },
  { name: "BD Zucchini 01 A", min: 44, max: 88, cat: "BD", era: 1 },
    { name: "Alicerçe de Cerca de Madeira Resina", min: 34, max: 40, cat: "Construção", era: 1 },
  { name: "Alicerçe de Madeira Resina", min: 40, max: 48, cat: "Construção", era: 1 },
  { name: "Alicerçe de Cunha de Madeira Resina", min: 40, max: 48, cat: "Construção", era: 1 },
  { name: "Armação de Portinhola de Madeira Resina", min: 15, max: 18, cat: "Construção", era: 1 },
  { name: "Batente de Madeira Resina para Portas", min: 21, max: 25, cat: "Construção", era: 1 },
  { name: "Cerca de Madeira Resina", min: 21, max: 25, cat: "Construção", era: 1 },
  { name: "Cobertura de Cumeeira de Madeira Resina", min: 21, max: 25, cat: "Construção", era: 1 },
  { name: "Cobertura de Muro de Madeira Resina", min: 21, max: 25, cat: "Construção", era: 1 },
  { name: "Cumeeira de Madeira Resina", min: 21, max: 25, cat: "Construção", era: 1 },
  { name: "Cunha de Madeira Resina", min: 21, max: 25, cat: "Construção", era: 1 },
  { name: "Escada de Madeira Resina", min: 40, max: 48, cat: "Construção", era: 1 },
  { name: "Escada de Madeira Resina (Trilho)", min: 40, max: 48, cat: "Construção", era: 1 },
  { name: "Interseção de Cumeeira de Madeira Resina", min: 21, max: 25, cat: "Construção", era: 1 },
  { name: "Junção de Cumeeira de Madeira Resina", min: 21, max: 25, cat: "Construção", era: 1 },
  { name: "Moldura de Madeira Resina", min: 21, max: 25, cat: "Construção", era: 1 },
  { name: "Muro de Madeira Resina", min: 21, max: 25, cat: "Construção", era: 1 },
  { name: "Muro Inclinado Direita de Madeira Resina", min: 21, max: 25, cat: "Construção", era: 1 },
  { name: "Muro Inclinado Esquerda de Madeira Resina", min: 21, max: 25, cat: "Construção", era: 1 },
  { name: "Muro Invertido Direita de Madeira Resina", min: 21, max: 25, cat: "Construção", era: 1 },
  { name: "Muro Invertido Esquerda de Madeira Resina", min: 21, max: 25, cat: "Construção", era: 1 },
  { name: "Pilar de Madeira Resina", min: 21, max: 25, cat: "Construção", era: 1 },
  { name: "Ponta de Cumeeira de Madeira Resina", min: 21, max: 25, cat: "Construção", era: 1 },
  { name: "Porta de Madeira Resina", min: 40, max: 48, cat: "Construção", era: 1 },
  { name: "Portinhola Resina", min: 42, max: 50, cat: "Construção", era: 1 },
    { name: "Batente de Portão de Madeira Resina", min: 40, max: 48, cat: "Construção", era: 1 },
  { name: "Portão de Madeira Resina", min: 40, max: 48, cat: "Construção", era: 1 },
  { name: "Quina de Cumeeira de Madeira Resina", min: 21, max: 25, cat: "Construção", era: 1 },
  { name: "Quina de Escadas de Madeira Resina", min: 40, max: 48, cat: "Construção", era: 1 },
  { name: "Quina de Rampa de Madeira Resina", min: 21, max: 25, cat: "Construção", era: 1 },
  { name: "Quina de Telhado Inclinado de Madeira Resina", min: 21, max: 25, cat: "Construção", era: 1 },
  { name: "Quina de Telhado de Madeira Resina", min: 21, max: 25, cat: "Construção", era: 1 },
  { name: "Rampa de Madeira Resina", min: 21, max: 25, cat: "Construção", era: 1 },
  { name: "Telhado de Madeira Resina", min: 27, max: 33, cat: "Construção", era: 1 },
  { name: "Telhado em Cunha Invertido e Inclinado de Madeira Resina", min: 27, max: 33, cat: "Construção", era: 1 },
  { name: "Telhado em Cunha Inclinado de Madeira Resina", min: 27, max: 33, cat: "Construção", era: 1 },
  { name: "Telhado Inclinado de Madeira Resina", min: 27, max: 33, cat: "Construção", era: 1 },
  { name: "Toldo de Madeira Resina", min: 34, max: 41, cat: "Construção", era: 1 },

  { name: "Alicerçe de Pedra Reforçada", min: 143, max: 172, cat: "Construção", era: 2 },
  { name: "Alicerçe de Cunha de Pedra Reforçada", min: 124, max: 149, cat: "Construção", era: 2 },
  { name: "Armação de Pedra Reforçada", min: 75, max: 90, cat: "Construção", era: 2 },
  { name: "Batente de Porta de Pedra Reforçada", min: 53, max: 63, cat: "Construção", era: 2 },
  { name: "Cunha de Pedra Reforçada", min: 55, max: 66, cat: "Construção", era: 2 },
  { name: "Muro de Pedra Reforçada Invertido e Inclinado à Direita", min: 74, max: 89, cat: "Construção", era: 2 },
  { name: "Muro de Pedra Reforçada Invertido e Inclinado à Esquerda", min: 68, max: 82, cat: "Construção", era: 2 },
  { name: "Muro de Pedra Reforçada", min: 64, max: 77, cat: "Construção", era: 2 },
  { name: "Muro de Pedra Reforçada Inclinado à Direita", min: 65, max: 78, cat: "Construção", era: 2 },
  { name: "Muro de Pedra Reforçada Inclinado à Esquerda", min: 59, max: 71, cat: "Construção", era: 2 },
  { name: "Pilar de Pedra Reforçada", min: 64, max: 77, cat: "Construção", era: 2 },
  { name: "Teto de Pedra Reforçada", min: 68, max: 82, cat: "Construção", era: 2 },

  { name: "Alicerçe de Madeira Reforçada com Gelo Preto", min: 138, max: 165, cat: "Construção", era: 3 },
  { name: "Alicerçe de Cunha de Madeira Reforçada com Gelo Preto", min: 135, max: 162, cat: "Construção", era: 3 },
  { name: "Batente de Porta de Madeira Reforçada com Gelo Preto", min: 82, max: 99, cat: "Construção", era: 3 },
  { name: "Cunha de Madeira Reforçada com Gelo Preto", min: 82, max: 99, cat: "Construção", era: 3 },
  { name: "Moldura de Madeira Reforçada com Gelo Preto", min: 82, max: 99, cat: "Construção", era: 3 },
  { name: "Muro de Madeira Reforçada com Gelo Preto Inclinado à Direita", min: 82, max: 99, cat: "Construção", era: 3 },
  { name: "Muro de Madeira Reforçada com Gelo Preto Inclinado à Esquerda", min: 82, max: 99, cat: "Construção", era: 3 },
  { name: "Muro de Madeira Reforçada com Gelo Preto", min: 82, max: 99, cat: "Construção", era: 3 },
  { name: "Muro de Madeira Reforçada com Gelo Preto Invertido e Inclinado à Direita", min: 82, max: 99, cat: "Construção", era: 3 },
  { name: "Muro de Madeira Reforçada com Gelo Preto Invertido e Inclinado à Esquerda", min: 82, max: 99, cat: "Construção", era: 3 },
  { name: "Pilar de Madeira Reforçada com Gelo Preto", min: 82, max: 99, cat: "Construção", era: 3 },
  { name: "Porta de Madeira Reforçada com Gelo Preto", min: 138, max: 165, cat: "Construção", era: 3 },
  { name: "Quina de Telhado Invertido e Inclinado de Madeira Reforçada com Gelo Preto", min: 82, max: 99, cat: "Construção", era: 3 },
  { name: "Quina de Telhado Inclinado de Madeira Reforçada com Gelo Preto", min: 82, max: 99, cat: "Construção", era: 3 },
  { name: "Telhado Inclinado de Madeira Reforçada com Gelo Preto", min: 89, max: 107, cat: "Construção", era: 3 },
  { name: "Telhado de Madeira Reforçada com Gelo Preto", min: 89, max: 107, cat: "Construção", era: 3 },
  { name: "Telhado em Cunha Invertido e Inclinado de Madeira Reforçada com Gelo Preto", min: 89, max: 107, cat: "Construção", era: 3 },
  { name: "Cunha Inclinado de Madeira Reforçada com Gelo Preto", min: 89, max: 107, cat: "Construção", era: 3 },
  { name: "Toldo Reforçado com Gelo Preto", min: 95, max: 115, cat: "Construção", era: 3 },

  { name: "Abóbada", min: 143, max: 172, cat: "Construção", era: 2 },
  { name: "Alicerçe", min: 143, max: 172, cat: "Construção", era: 2 },
  { name: "Alicerçe de Casa na Árvore", min: 618, max: 742, cat: "Construção", era: 2 },
  { name: "Alicerçe de Cerca", min: 128, max: 154, cat: "Construção", era: 2 },
  { name: "Alicerçe de Cunha", min: 143, max: 172, cat: "Construção", era: 2 },
  { name: "Armação / Estrutura / Moldura", min: 85, max: 103, cat: "Construção", era: 2 },
  { name: "Armação de Portinhola", min: 50, max: 60, cat: "Construção", era: 2 },
  { name: "Batente", min: 85, max: 103, cat: "Construção", era: 2 },
  { name: "Cerca de Estábulo, Pilares", min: 85, max: 103, cat: "Construção", era: 2 },
  { name: "Cobertura", min: 85, max: 103, cat: "Construção", era: 2 },
  { name: "Cobertura para Muro", min: 69, max: 83, cat: "Construção", era: 2 },
  { name: "Cumeeira / Janela", min: 85, max: 103, cat: "Construção", era: 2 },
  { name: "Cunha", min: 85, max: 103, cat: "Construção", era: 2 },
  { name: "Escada", min: 143, max: 172, cat: "Construção", era: 2 },
  { name: "Guarnição de Portão de Cerca, Pilares", min: 85, max: 103, cat: "Construção", era: 2 },
  { name: "Janela Inclinado", min: 143, max: 172, cat: "Construção", era: 2 },
  { name: "Moldura de Portão", min: 287, max: 344, cat: "Construção", era: 2 },
  { name: "Muralhas Crenuladas", min: 143, max: 172, cat: "Construção", era: 2 },
  { name: "Muro", min: 85, max: 103, cat: "Construção", era: 2 },
  { name: "Muro de Treliça", min: 85, max: 103, cat: "Construção", era: 2 },
  { name: "Muro Inclinado, Invertido", min: 92, max: 111, cat: "Construção", era: 2 },
  { name: "Pilar", min: 85, max: 103, cat: "Construção", era: 2 },
  { name: "Porta", min: 82, max: 98, cat: "Construção", era: 2 },
  { name: "Portão", min: 143, max: 172, cat: "Construção", era: 2 },
  { name: "Portinhola", min: 84, max: 101, cat: "Construção", era: 2 },
  { name: "Quina de Escada, Invertida", min: 143, max: 172, cat: "Construção", era: 2 },
  { name: "Quina de Telhado Invertido, Inclinado", min: 85, max: 103, cat: "Construção", era: 2 },
  { name: "Rampa, Quina", min: 85, max: 103, cat: "Construção", era: 2 },
  { name: "Telhado (Piso)", min: 92, max: 111, cat: "Construção", era: 2 },
  { name: "Telhado de Cunha Invertidoo, Inclinado", min: 88, max: 106, cat: "Construção", era: 2 },
  { name: "Telhado Inclinado", min: 143, max: 172, cat: "Construção", era: 2 },
  { name: "Toldo, Quina", min: 16, max: 19, cat: "Construção", era: 2 },
];
