dataByProfession.cacador = [
  {"name":"Couro","min":2,"max":3,"cat":"BÁSICO","era":1,"ingredients":[{"qty":3,"item":"Couraça"}]},
  {"name":"Couro Reforçado","min":3,"max":6,"cat":"BÁSICO","era":1,"ingredients":[{"qty":1,"item":"Couraça Grossa"}]},
  {"name":"Piche","min":1,"max":1,"cat":"BÁSICO","era":1,"ingredients":[{"qty":3,"item":"Couraça"}]},
  {"name":"Pluma","min":1,"max":2,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Ovo","min":1,"max":2,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Teia","min":0.5,"max":1,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Vulcan Bee","min":2,"max":2,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Icor","min":1,"max":1,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Berrante","min":3,"max":5,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Couraça","min":0.3,"max":0.3,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Couraça-Grossa","min":2,"max":4,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Crânio Gasto","min":10,"max":20,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Osso","min":1,"max":1,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Marfim","min":2,"max":3,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Peles Reptilianas","min":1,"max":1,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Pele de Lobo","min":1,"max":1,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Pele de Hiena","min":1,"max":1,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Pele de Felino","min":1,"max":1,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Couraça de Rinoceronte","min":2,"max":3,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Couraça de Elefante","min":2,"max":3,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Pele de Urso","min":2,"max":3,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Pelos","min":1,"max":2,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Especiarias Raras","min":4,"max":6,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Presas","min":2,"max":3,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Garras","min":2,"max":3,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Quitina","min":1,"max":1,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Glândula Volátil","min":3,"max":5,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Glândula de Veneno de Serpente","min":3,"max":5,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Glândula Biliar de Fera das Areias","min":600,"max":800,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Glândula de Toxina do Terror das Dunas","min":4,"max":6,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Perna Decepada","min":500,"max":1000,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Fragmento do Poder","min":50,"max":300,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Pérola","min":20,"max":30,"cat":"BÁSICO","era":3,"ingredients":[]},
  {"name":"Ectoplasm","min":50,"max":60,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Honor Token","min":10,"max":20,"cat":"BÁSICO","era":5,"ingredients":[]},
  {"name":"Marca da Harpia","min":2000,"max":2500,"cat":"MARCAS DE SIPTAH","era":2,"ingredients":[{"qty":5,"item":"Fragmento do Poder"}]},
  {"name":"Marca dos Afogados","min":2000,"max":2500,"cat":"MARCAS DE SIPTAH","era":2,"ingredients":[{"qty":5,"item":"Fragmento do Poder"}]},
  {"name":"Marca da Serpente","min":2000,"max":2500,"cat":"MARCAS DE SIPTAH","era":2,"ingredients":[{"qty":5,"item":"Fragmento do Poder"}]},
  {"name":"Marca da Ninhada de Jhil","min":2000,"max":2500,"cat":"MARCAS DE SIPTAH","era":2,"ingredients":[{"qty":5,"item":"Fragmento do Poder"}]},
  {"name":"Marca de Gremlin","min":2000,"max":2500,"cat":"MARCAS DE SIPTAH","era":2,"ingredients":[{"qty":5,"item":"Fragmento do Poder"}]},
  {"name":"Coração do Deserto","min":1850,"max":2775,"cat":"DROPS DUNGEON","era":1,"ingredients":[]},
  {"name":"Presa Abismal","min":5,"max":10,"cat":"DROPS DUNGEON","era":1,"ingredients":[]},
  {"name":"Olho Abismal","min":50,"max":100,"cat":"DROPS DUNGEON","era":1,"ingredients":[]},
  {"name":"Carne Abismal","min":10,"max":20,"cat":"DROPS DUNGEON","era":1,"ingredients":[]},
  {"name":"Glândula de Peçonha da Rainha-Escorpião","min":10,"max":15,"cat":"DROPS DUNGEON","era":2,"ingredients":[]},
  {"name":"Flor-das-Sombras","min":20,"max":25,"cat":"DROPS DUNGEON","era":2,"ingredients":[]},
  {"name":"Carne da Memória","min":50,"max":100,"cat":"DROPS DUNGEON","era":2,"ingredients":[]},
  {"name":"Ovo de Escorpião","min":600,"max":1000,"cat":"DROPS DUNGEON","era":2,"ingredients":[]},
  {"name":"Máscara Feiticeira","min":1350,"max":2025,"cat":"DROPS DUNGEON","era":3,"ingredients":[]},
  {"name":"Frozen Heart","min":1350,"max":2025,"cat":"DROPS DUNGEON","era":3,"ingredients":[]},
  {"name":"Estrela do Campeão","min":1350,"max":2025,"cat":"DROPS DUNGEON","era":4,"ingredients":[]},
  {"name":"Aço Khari","min":100,"max":200,"cat":"DROPS DUNGEON","era":4,"ingredients":[]},
  {"name":"Escamas de Dagon","min":200,"max":300,"cat":"DROPS DUNGEON","era":3,"ingredients":[]},
  {"name":"Coração do Fratricida","min":1350,"max":2025,"cat":"DROPS DUNGEON","era":4,"ingredients":[]},
  {"name":"Lágrima de Duas Raças","min":1350,"max":2025,"cat":"DROPS DUNGEON","era":4,"ingredients":[]},
  {"name":"Black Heart","min":850,"max":1275,"cat":"DROPS DUNGEON","era":4,"ingredients":[]},
  {"name":"Trapezedro","min":1350,"max":2025,"cat":"DROPS DUNGEON","era":5,"ingredients":[]},
  {"name":"Cidade sem Nome","min":1000,"max":2000,"cat":"CIDADE SEM NOME","era":2,"ingredients":[]},
  {"name":"Cidade sem Nome","min":1000,"max":1500,"cat":"CIDADE SEM NOME","era":2,"ingredients":[]},
  {"name":"Cidade sem Nome","min":2000,"max":3000,"cat":"CIDADE SEM NOME","era":4,"ingredients":[]},
  {"name":"Pele de Morcego","min":2,"max":3,"cat":"DROPS DE ANIMAIS MÉDIOS","era":1,"ingredients":[]},
  {"name":"Concha de Filhote de Lombo-Grosso","min":1000,"max":1200,"cat":"DROPS DE ANIMAIS MÉDIOS","era":2,"ingredients":[]},
  {"name":"Coração do Herói","min":100,"max":200,"cat":"DROPS DE ANIMAIS MÉDIOS","era":2,"ingredients":[]},
  {"name":"Coração Nordemita","min":10,"max":20,"cat":"DROPS DE ANIMAIS MÉDIOS","era":2,"ingredients":[]},
  {"name":"Pergaminho de Aprendizado","min":1500,"max":2000,"cat":"DROPS DE ANIMAIS MÉDIOS","era":2,"ingredients":[]},
  {"name":"Osso de Dragão","min":50,"max":100,"cat":"DROPS DE ANIMAIS MÉDIOS","era":4,"ingredients":[]},
  {"name":"Pó de Mácula","min":1,"max":2,"cat":"DROPS DE ANIMAIS MÉDIOS","era":3,"ingredients":[]},
  {"name":"Máscara Subaquática","min":2000,"max":2500,"cat":"DROPS DE ANIMAIS MÉDIOS","era":3,"ingredients":[]},
  {"name":"Sangue de Demônio","min":10,"max":20,"cat":"DROPS DE ANIMAIS MÉDIOS","era":3,"ingredients":[]},
  {"name":"Seda de Ébano","min":150,"max":200,"cat":"DROPS DE ANIMAIS MÉDIOS","era":2,"ingredients":[]},
  {"name":"Chifre de Dragão","min":200,"max":300,"cat":"DROPS DE ANIMAIS MÉDIOS","era":4,"ingredients":[]},
  {"name":"Blood of the Devil Bear","min":100,"max":200,"cat":"DROPS DE ANIMAIS MÉDIOS","era":3,"ingredients":[]},
  {"name":"Sangue de Urso de Demônio","min":100,"max":200,"cat":"DROPS DE ANIMAIS MÉDIOS","era":3,"ingredients":[]},
  {"name":"Devil Bear Cub","min":3000,"max":6000,"cat":"DROPS DE ANIMAIS MÉDIOS","era":3,"ingredients":[]},
  {"name":"Wraith Essence","min":4000,"max":4200,"cat":"DROPS DE ANIMAIS MÉDIOS","era":3,"ingredients":[]},
  {"name":"Cursed Undead Remains","min":250,"max":300,"cat":"DROPS DE ANIMAIS MÉDIOS","era":3,"ingredients":[]},
  {"name":"Cursed Rabbit Remains","min":300,"max":350,"cat":"DROPS DE ANIMAIS MÉDIOS","era":3,"ingredients":[]},
  {"name":"Sangue de Morcego Demoníaco Albino","min":10,"max":20,"cat":"DROPS DE ANIMAIS MÉDIOS","era":3,"ingredients":[]},
  {"name":"Fragmento de Armadura","min":50,"max":100,"cat":"DROPS DE ANIMAIS MÉDIOS","era":4,"ingredients":[]},
  {"name":"Sangue Negro","min":50,"max":100,"cat":"DROPS DE ANIMAIS MÉDIOS","era":4,"ingredients":[]},
  {"name":"Unstable Substance","min":10,"max":20,"cat":"DROPS DE ANIMAIS MÉDIOS","era":4,"ingredients":[]},
  {"name":"Arco Lendário sem Bônus","min":1200,"max":1500,"cat":"ARMAS LENDÁRIAS","era":4,"ingredients":[]},
  {"name":"Arco Lendário com Bônus","min":1500,"max":2000,"cat":"ARMAS LENDÁRIAS","era":4,"ingredients":[]},
  {"name":"Armas de uma mão Lendária sem Bônus","min":2500,"max":3000,"cat":"ARMAS LENDÁRIAS","era":4,"ingredients":[]},
  {"name":"Armas de uma mão Lendária com Bônus","min":3000,"max":3500,"cat":"ARMAS LENDÁRIAS","era":4,"ingredients":[]},
  {"name":"Armas de duas mãos Lendária sem Bônus","min":2500,"max":3000,"cat":"ARMAS LENDÁRIAS","era":4,"ingredients":[]},
  {"name":"Armas de duas mãos Lendária com Bônus","min":3000,"max":3500,"cat":"ARMAS LENDÁRIAS","era":4,"ingredients":[]},
  {"name":"Adagas Lendárias sem Bônus","min":2500,"max":3000,"cat":"ARMAS LENDÁRIAS","era":4,"ingredients":[]},
  {"name":"Adagas Lendárias com Bônus","min":3000,"max":3500,"cat":"ARMAS LENDÁRIAS","era":4,"ingredients":[]},
  {"name":"Escudo Lendário sem Bônus","min":2500,"max":3000,"cat":"ARMAS LENDÁRIAS","era":4,"ingredients":[]},
  {"name":"Escudo Lendário com Bônus","min":3000,"max":3500,"cat":"ARMAS LENDÁRIAS","era":4,"ingredients":[]},
  {"name":"Amorosa / Lovetap","min":3000,"max":3500,"cat":"ARMAS LENDÁRIAS","era":4,"ingredients":[]},
  {"name":"Todas as Armas e Escudos","min":7000,"max":8000,"cat":"BAÚ LENDÁRIO 80 ANOS","era":4,"ingredients":[]},
  {"name":"Capacete o Nemédio","min":0,"max":0,"cat":"DROPS LENDÁRIOS","era":"X","ingredients":[]},
  {"name":"Armaduras Lendárias","min":5000,"max":6000,"cat":"DROPS LENDÁRIOS","era":4,"ingredients":[]},
  {"name":"Ferramentas Lendárias","min":4000,"max":5000,"cat":"DROPS LENDÁRIOS","era":4,"ingredients":[]},
  {"name":"Drops Lendários (Cidade sem Nome)","min":6000,"max":7000,"cat":"DROPS LENDÁRIOS","era":4,"ingredients":[]},
  {"name":"Cabeça de Alce","min":30,"max":50,"cat":"CABEÇAS","era":1,"ingredients":[]},
  {"name":"Cabeça de Antílope","min":0,"max":0,"cat":"CABEÇAS","era":1,"ingredients":[]},
  {"name":"Cabeça de Bico-de-Sapato","min":0,"max":0,"cat":"CABEÇAS","era":1,"ingredients":[]},
  {"name":"Cabeça de Bode","min":0,"max":0,"cat":"CABEÇAS","era":1,"ingredients":[]},
  {"name":"Cabeça de Cervo","min":0,"max":0,"cat":"CABEÇAS","era":1,"ingredients":[]},
  {"name":"Cabeça de Crocodilo","min":0,"max":0,"cat":"CABEÇAS","era":1,"ingredients":[]},
  {"name":"Cabeça de Gazela","min":0,"max":0,"cat":"CABEÇAS","era":1,"ingredients":[]},
  {"name":"Cabeça de Gorila","min":0,"max":0,"cat":"CABEÇAS","era":1,"ingredients":[]},
  {"name":"Cabeça de Hiena","min":0,"max":0,"cat":"CABEÇAS","era":1,"ingredients":[]},
  {"name":"Cabeça de Hiena Morta-Viva","min":0,"max":0,"cat":"CABEÇAS","era":1,"ingredients":[]},
  {"name":"Cabeça de Jaguar","min":0,"max":0,"cat":"CABEÇAS","era":1,"ingredients":[]},
  {"name":"Cabeça de Javali-Selvagem","min":0,"max":0,"cat":"CABEÇAS","era":1,"ingredients":[]},
  {"name":"Cabeça de Kudu","min":0,"max":0,"cat":"CABEÇAS","era":1,"ingredients":[]},
  {"name":"Cabeça de Lombo-Grosso","min":0,"max":0,"cat":"CABEÇAS","era":1,"ingredients":[]},
  {"name":"Cabeça de Pantera","min":0,"max":0,"cat":"CABEÇAS","era":1,"ingredients":[]},
  {"name":"Cabeça de Rochifre","min":0,"max":0,"cat":"CABEÇAS","era":1,"ingredients":[]},
  {"name":"Cabeça de Salamandra","min":0,"max":0,"cat":"CABEÇAS","era":1,"ingredients":[]},
  {"name":"Cabeça de Símio-Cinzento","min":0,"max":0,"cat":"CABEÇAS","era":1,"ingredients":[]},
  {"name":"Cabeça de Tigre","min":0,"max":0,"cat":"CABEÇAS","era":1,"ingredients":[]},
  {"name":"Cabeça de Urso Marrom","min":0,"max":0,"cat":"CABEÇAS","era":1,"ingredients":[]},
  {"name":"Cabeça de Lobo","min":0,"max":0,"cat":"CABEÇAS","era":2,"ingredients":[]},
  {"name":"Cabeça de Rinoceronte","min":0,"max":0,"cat":"CABEÇAS","era":2,"ingredients":[]},
  {"name":"Cabeça de Lombo-Grosso Demônio","min":150,"max":200,"cat":"CABEÇAS","era":1,"ingredients":[]},
  {"name":"Cabeça de Rei Lombo-Grosso","min":0,"max":0,"cat":"CABEÇAS","era":1,"ingredients":[]},
  {"name":"Cabeça de Homem Serpente Esqueleto","min":0,"max":0,"cat":"CABEÇAS","era":2,"ingredients":[]},
  {"name":"Cabeça de Mamute","min":0,"max":0,"cat":"CABEÇAS","era":2,"ingredients":[]},
  {"name":"Cabeça de Rei Rinoceronte","min":0,"max":0,"cat":"CABEÇAS","era":2,"ingredients":[]},
  {"name":"Cabeça de Rei Rochifre","min":0,"max":0,"cat":"CABEÇAS","era":2,"ingredients":[]},
  {"name":"Cabeça de Rinoceronte Branco","min":0,"max":0,"cat":"CABEÇAS","era":2,"ingredients":[]},
  {"name":"Cabeça de Rinoceronte Preto","min":0,"max":0,"cat":"CABEÇAS","era":2,"ingredients":[]},
  {"name":"Cabeça de Dente-de-Sabre","min":0,"max":0,"cat":"CABEÇAS","era":3,"ingredients":[]},
  {"name":"Cabeça de Morcego Demoníaco","min":0,"max":0,"cat":"CABEÇAS","era":3,"ingredients":[]},
  {"name":"Cabeça de Alce Rei","min":1000,"max":1200,"cat":"CABEÇAS","era":2,"ingredients":[]},
  {"name":"Cabeça de Lobo Gigante","min":0,"max":0,"cat":"CABEÇAS","era":2,"ingredients":[]},
  {"name":"Cabeça de Tigre Branco","min":0,"max":0,"cat":"CABEÇAS","era":2,"ingredients":[]},
  {"name":"Cabeça de Urso Negro","min":0,"max":0,"cat":"CABEÇAS","era":2,"ingredients":[]},
  {"name":"Giant Head","min":0,"max":0,"cat":"CABEÇAS","era":2,"ingredients":[]},
  {"name":"Scourge Rhino Head","min":0,"max":0,"cat":"CABEÇAS","era":2,"ingredients":[]},
  {"name":"Blood Hound Head","min":0,"max":0,"cat":"CABEÇAS","era":3,"ingredients":[]},
  {"name":"Devil Bear Cub Head","min":0,"max":0,"cat":"CABEÇAS","era":3,"ingredients":[]},
  {"name":"Kurokumo Head","min":0,"max":0,"cat":"CABEÇAS","era":3,"ingredients":[]},
  {"name":"Scourge Dweller Head","min":0,"max":0,"cat":"CABEÇAS","era":3,"ingredients":[]},
  {"name":"Scourge Mammoth Head","min":0,"max":0,"cat":"CABEÇAS","era":3,"ingredients":[]},
  {"name":"Akuma Head","min":2000,"max":2500,"cat":"CABEÇAS","era":3,"ingredients":[]},
  {"name":"Cabeça de Dragão Verde","min":0,"max":0,"cat":"CABEÇAS","era":3,"ingredients":[]},
  {"name":"Cabeça de Dragão Vermelho","min":0,"max":0,"cat":"CABEÇAS","era":3,"ingredients":[]},
  {"name":"Scourge Hound Head","min":0,"max":0,"cat":"CABEÇAS","era":4,"ingredients":[]},
  {"name":"Cabeça Aranha Demoníaca","min":0,"max":0,"cat":"CABEÇAS","era":4,"ingredients":[]},
  {"name":"Ashira Head","min":0,"max":0,"cat":"CABEÇAS","era":4,"ingredients":[]},
  {"name":"Scourge Crocodile Head","min":0,"max":0,"cat":"CABEÇAS","era":4,"ingredients":[]},
  {"name":"Scourge Gargoyle Head","min":0,"max":0,"cat":"CABEÇAS","era":4,"ingredients":[]},
  {"name":"Skull of the Harbinger","min":3000,"max":3500,"cat":"CABEÇAS","era":3,"ingredients":[]},
  {"name":"Spawn of Scargath Head","min":0,"max":0,"cat":"CABEÇAS","era":3,"ingredients":[]},
  {"name":"Scourge Dragon Head","min":0,"max":0,"cat":"CABEÇAS","era":4,"ingredients":[]},
  {"name":"Carne Saborosa","min":2,"max":3,"cat":"CARNES","era":1,"ingredients":[]},
  {"name":"Carne Exótica","min":2,"max":3,"cat":"CARNES","era":1,"ingredients":[]},
  {"name":"Carne de Feras","min":1,"max":1,"cat":"CARNES","era":1,"ingredients":[]},
  {"name":"Porco Cru","min":1,"max":4,"cat":"CARNES","era":1,"ingredients":[]},
  {"name":"Carne Requintada","min":3,"max":6,"cat":"CARNES","era":1,"ingredients":[]},
  {"name":"Carne Humana","min":2,"max":3,"cat":"CARNES","era":1,"ingredients":[]},
  {"name":"Carne de Ostras","min":3,"max":6,"cat":"CARNES","era":1,"ingredients":[]},
  {"name":"Mina de Ferro","min":500,"max":700,"cat":"Cavernas","era":1,"ingredients":[]},
  {"name":"Mina de Carvão","min":500,"max":500,"cat":"Cavernas","era":1,"ingredients":[]},
  {"name":"Mina de Enxofre","min":700,"max":1400,"cat":"Cavernas","era":2,"ingredients":[]}
];
