dataByProfession.cacador = [
  // BÁSICO (Era 1)
  { name: "Couro", min: 2, max: 3, cat: "Básico", era: 1 },
  { name: "Couro Reforçado", min: 3, max: 6, cat: "Básico", era: 1 },
  { name: "Piche", min: 0.5, max: 1, cat: "Básico", era: 1 },
  { name: "Pluma", min: 1, max: 2, cat: "Básico", era: 1 },
  { name: "Ovo", min: 1, max: 2, cat: "Básico", era: 1 },
  { name: "Teia", min: 0.5, max: 1, cat: "Básico", era: 1 },
  { name: "Vulcan Bee", min: 2, max: 2, cat: "Básico", era: 1 },
  { name: "Icor", min: 1, max: 1, cat: "Básico", era: 1 },
  { name: "Berrante", min: 3, max: 5, cat: "Básico", era: 1 },
  { name: "Couraça", min: 0.3, max: 0.3, cat: "Básico", era: 1 },
  { name: "Couraça Grossa", min: 2, max: 4, cat: "Básico", era: 1 },
  { name: "Crânio Gasto", min: 10, max: 20, cat: "Básico", era: 1 },
  { name: "Osso", min: 1, max: 1, cat: "Básico", era: 1 },
  { name: "Marfim", min: 2, max: 3, cat: "Básico", era: 1 },
  { name: "Peles Reptilianas", min: 1, max: 1, cat: "Básico", era: 1 },
  { name: "Pele de Lobo", min: 1, max: 1, cat: "Básico", era: 1 },
  { name: "Pele de Hiena", min: 1, max: 1, cat: "Básico", era: 1 },
  { name: "Pele de Felino", min: 1, max: 1, cat: "Básico", era: 1 },
  { name: "Couraça de Rinoceronte", min: 2, max: 3, cat: "Básico", era: 1 },

  // PARTES DE ANIMAIS (Era 1 e 2)
  { name: "Couraça de Elefante", min: 2, max: 3, cat: "Partes de Animais", era: 1 },
  { name: "Pele de Urso", min: 2, max: 3, cat: "Partes de Animais", era: 1 },
  { name: "Pelos", min: 1, max: 2, cat: "Partes de Animais", era: 1 },
  { name: "Presas", min: 2, max: 3, cat: "Partes de Animais", era: 1 },
  { name: "Garras", min: 2, max: 3, cat: "Partes de Animais", era: 1 },
  { name: "Quitina", min: 1, max: 1, cat: "Partes de Animais", era: 1 },
  { name: "Glândula Volátil", min: 3, max: 5, cat: "Partes de Animais", era: 1 },
  { name: "Glândula de Veneno de Serpente", min: 3, max: 5, cat: "Partes de Animais", era: 1 },
  { name: "Glândula Biliar de Fera das Areias", min: 6, max: 8, cat: "Partes de Animais", era: 1 },
  { name: "Glândula de Toxina do Terror das Dunas", min: 4, max: 6, cat: "Partes de Animais", era: 1 },
  { name: "Perna Decepada", min: 5, max: 10, cat: "Partes de Animais", era: 1 },
  { name: "Fragmento do Poder", min: 50, max: 300, cat: "Partes de Animais", era: 1 },
  { name: "Pérola", min: 20, max: 30, cat: "Partes de Animais", era: 2 },
  { name: "Ectoplasma", min: 50, max: 80, cat: "Partes de Animais", era: 1 },
  { name: "Coração do Deserto", min: 18.50, max: 27.75, cat: "Partes de Animais", era: 1 },
  { name: "Presa Abismal", min: 5, max: 10, cat: "Partes de Animais", era: 2 },
  { name: "Olho Abismal", min: 50, max: 100, cat: "Partes de Animais", era: 2 },

  // DUNGEON & RAROS (Mistura de Eras 2 a 5)
  { name: "Carne Abismal", min: 10, max: 20, cat: "Dungeon & Raros", era: 2 },
  { name: "Glândula de Peçonha da Rainha-Escorpião", min: 10, max: 15, cat: "Dungeon & Raros", era: 2 },
  { name: "Flor-das-Sombras", min: 20, max: 25, cat: "Dungeon & Raros", era: 2 },
  { name: "Carne da Memória", min: 50, max: 100, cat: "Dungeon & Raros", era: 2 },
  { name: "Ovo de Escorpião", min: 8, max: 10, cat: "Dungeon & Raros", era: 2 },
  { name: "Máscara Feiticeira", min: 13.50, max: 20.25, cat: "Dungeon & Raros", era: 3 },
  { name: "Estrela do Campeão", min: 13.50, max: 20.25, cat: "Dungeon & Raros", era: 4 },
  { name: "Aço Khari", min: 100, max: 200, cat: "Dungeon & Raros", era: 4 },
  { name: "Escamas de Dagon", min: 200, max: 300, cat: "Dungeon & Raros", era: 3 },
  { name: "Coração do Fratricida", min: 13.50, max: 20.25, cat: "Dungeon & Raros", era: 4 },
  { name: "Lágrima de Duas Raças", min: 13.50, max: 20.25, cat: "Dungeon & Raros", era: 4 },
  { name: "Trapezedro", min: 13.50, max: 20.25, cat: "Dungeon & Raros", era: 5 },
  { name: "Pele de Morcego", min: 2, max: 3, cat: "Dungeon & Raros", era: 1 },
  { name: "Coração do Herói", min: 100, max: 200, cat: "Dungeon & Raros", era: 2 },
  { name: "Coração Nordemita", min: 10, max: 20, cat: "Dungeon & Raros", era: 2 },
  { name: "Osso de Dragão", min: 50, max: 100, cat: "Dungeon & Raros", era: 4 },
  { name: "Pó de Mácula", min: 1, max: 2, cat: "Dungeon & Raros", era: 3 },
  { name: "Máscara Subaquática", min: 20, max: 25, cat: "Dungeon & Raros", era: 3 },

  // DROPS ANIMAIS MÉDIOS (Era 2 e 3)
  { name: "Sangue de Demônio", min: 10, max: 20, cat: "Drops Animais Médios", era: 3 },
  { name: "Seda de Ébano", min: 1.5, max: 2, cat: "Drops Animais Médios", era: 2 },
  { name: "Chifre de Dragão", min: 200, max: 300, cat: "Drops Animais Médios", era: 4 },
  { name: "Sangue de Urso de Demônio", min: 1, max: 2, cat: "Drops Animais Médios", era: 3 },
  { name: "Devil Bear Cub", min: 30, max: 60, cat: "Drops Animais Médios", era: 3 },
  { name: "Wraith Essence", min: 40, max: 42, cat: "Drops Animais Médios", era: 3 },
  { name: "Cursed Undead Remains", min: 2.5, max: 3, cat: "Drops Animais Médios", era: 3 },
  { name: "Cursed Rabbit Remains", min: 3, max: 3.5, cat: "Drops Animais Médios", era: 3 },
  { name: "Sangue de Morcego Demoníaco Albino", min: 10, max: 20, cat: "Drops Animais Médios", era: 3 },
  { name: "Fragmento de Armadura", min: 50, max: 100, cat: "Drops Animais Médios", era: 4 },
  { name: "Sangue Negro", min: 50, max: 100, cat: "Drops Animais Médios", era: 4 },
  { name: "Unstable Substance", min: 10, max: 20, cat: "Drops Animais Médios", era: 4 },

  // CABEÇAS BÁSICAS (Era 1 e 2)
  { name: "Cabeça de Alce", min: 30, max: 50, cat: "Cabeças Básicas", era: 1 },
  { name: "Cabeça de Antílope", min: 30, max: 50, cat: "Cabeças Básicas", era: 1 },
  { name: "Cabeça de Bico-de-Sapato", min: 30, max: 50, cat: "Cabeças Básicas", era: 1 },
  { name: "Cabeça de Bode", min: 30, max: 50, cat: "Cabeças Básicas", era: 1 },
  { name: "Cabeça de Cervo", min: 30, max: 50, cat: "Cabeças Básicas", era: 1 },
  { name: "Cabeça de Crocodilo", min: 30, max: 50, cat: "Cabeças Básicas", era: 1 },
  { name: "Cabeça de Gazela", min: 30, max: 50, cat: "Cabeças Básicas", era: 1 },
  { name: "Cabeça de Gorila", min: 30, max: 50, cat: "Cabeças Básicas", era: 2 },
  { name: "Cabeça de Hiena", min: 30, max: 50, cat: "Cabeças Básicas", era: 1 },
  { name: "Cabeça de Hiena Morta-Viva", min: 30, max: 50, cat: "Cabeças Básicas", era: 1 },
  { name: "Cabeça de Jaguar", min: 30, max: 50, cat: "Cabeças Básicas", era: 1 },
  { name: "Cabeça de Javali", min: 30, max: 50, cat: "Cabeças Básicas", era: 1 },
  { name: "Cabeça de Kudu", min: 30, max: 50, cat: "Cabeças Básicas", era: 1 },
  { name: "Cabeça de Lombo-Grosso", min: 30, max: 50, cat: "Cabeças Básicas", era: 1 },
  { name: "Cabeça de Pantera", min: 30, max: 50, cat: "Cabeças Básicas", era: 1 },
  { name: "Cabeça de Rochifre", min: 30, max: 50, cat: "Cabeças Básicas", era: 1 },
  { name: "Cabeça de Salamandra", min: 30, max: 50, cat: "Cabeças Básicas", era: 1 },
  { name: "Cabeça de Símio", min: 30, max: 50, cat: "Cabeças Básicas", era: 1 },
  { name: "Cabeça de Tigre", min: 30, max: 50, cat: "Cabeças Básicas", era: 1 },
  { name: "Cabeça de Urso Marrom", min: 30, max: 50, cat: "Cabeças Básicas", era: 2 },

  // CABEÇAS MÉDIAS (Era 2)
  { name: "Cabeça de Lombo-Grosso Demônio", min: 150, max: 200, cat: "Cabeças Médias", era: 2 },
  { name: "Cabeça de Rei Lombo-Grosso", min: 150, max: 200, cat: "Cabeças Médias", era: 2 },
  { name: "Cabeça de Homem Serpente Esqueleto", min: 150, max: 200, cat: "Cabeças Médias", era: 2 },
  { name: "Cabeça de Mamute", min: 150, max: 200, cat: "Cabeças Médias", era: 2 },
  { name: "Cabeça de Rei Rinoceronte", min: 150, max: 200, cat: "Cabeças Médias", era: 2 },
  { name: "Cabeça de Rei Rochifre", min: 150, max: 200, cat: "Cabeças Médias", era: 2 },
  { name: "Cabeça de Rinoceronte Branco", min: 150, max: 200, cat: "Cabeças Médias", era: 2 },
  { name: "Cabeça de Rinoceronte Preto", min: 150, max: 200, cat: "Cabeças Médias", era: 2 },
  { name: "Cabeça de Dente-de-Sabre", min: 150, max: 200, cat: "Cabeças Médias", era: 2 },
  { name: "Cabeça de Morcego Demoníaco", min: 150, max: 200, cat: "Cabeças Médias", era: 2 },

  // CABEÇAS ESPECIAIS (Era 3)
  { name: "Scourge Rhino Head", min: 1000, max: 1200, cat: "Cabeças Especiais", era: 3 },
  { name: "Blood Hound Head", min: 1000, max: 1200, cat: "Cabeças Especiais", era: 3 },
  { name: "Devil Bear Cub Head", min: 1000, max: 1200, cat: "Cabeças Especiais", era: 3 },
  { name: "Kurokumo Head", min: 1000, max: 1200, cat: "Cabeças Especiais", era: 3 },
  { name: "Scourge Dweller Head", min: 1000, max: 1200, cat: "Cabeças Especiais", era: 3 },
  { name: "Scourge Mammoth Head", min: 1000, max: 1200, cat: "Cabeças Especiais", era: 3 },

  // CABEÇAS RARAS (Era 4)
  { name: "Akuma Head", min: 2000, max: 2500, cat: "Cabeças Raras", era: 4 },
  { name: "Cabeça de Dragão Verde", min: 2000, max: 2500, cat: "Cabeças Raras", era: 4 },
  { name: "Cabeça de Dragão Vermelho", min: 2000, max: 2500, cat: "Cabeças Raras", era: 4 },
  { name: "Scourge Hound Head", min: 2000, max: 2500, cat: "Cabeças Raras", era: 4 },
  { name: "Cabeça Aranha Demoníaca", min: 2000, max: 2500, cat: "Cabeças Raras", era: 4 },
  { name: "Ashira Head", min: 2000, max: 2500, cat: "Cabeças Raras", era: 4 },
  { name: "Scourge Crocodile Head", min: 2000, max: 2500, cat: "Cabeças Raras", era: 4 },
  { name: "Scourge Gargoyle Head", min: 2000, max: 2500, cat: "Cabeças Raras", era: 4 },

  // CABEÇAS LENDÁRIAS (Era 5)
  { name: "Skull of the Harbinger", min: 3000, max: 3500, cat: "Cabeças Lendárias", era: 5 },
  { name: "Spawn of Scargath Head", min: 3000, max: 3500, cat: "Cabeças Lendárias", era: 5 },
  { name: "Scourge Dragon Head", min: 3000, max: 3500, cat: "Cabeças Lendárias", era: 5 },

  // CARNES (Era 1)
  { name: "Carne Saborosa", min: 2, max: 3, cat: "Carnes", era: 1 },
  { name: "Carne Exótica", min: 2, max: 3, cat: "Carnes", era: 1 },
  { name: "Carne de Feras", min: 1, max: 1, cat: "Carnes", era: 1 },
  { name: "Porco Cru", min: 1, max: 4, cat: "Carnes", era: 1 },
  { name: "Carne Requintada", min: 3, max: 6, cat: "Carnes", era: 1 },
  { name: "Carne Humana", min: 2, max: 3, cat: "Carnes", era: 1 },
  { name: "Carne de Ostras", min: 3, max: 6, cat: "Carnes", era: 1 },

  // PEIXES (Era 1)
  { name: "Peixe Pequeno", min: 1, max: 2, cat: "Peixes", era: 1 },
  { name: "Peixe Médio", min: 3, max: 5, cat: "Peixes", era: 1 },
  { name: "Peixe Grande", min: 5, max: 10, cat: "Peixes", era: 1 },
  { name: "Peixe Exótico", min: 15, max: 20, cat: "Peixes", era: 2 }, // Exótico pode ser considerado era 2
  { name: "Peixe Abissal", min: 25, max: 35, cat: "Peixes", era: 2 }, // Abissal é dungeon/área difícil
  { name: "Lula", min: 4, max: 6, cat: "Peixes", era: 1 },
  { name: "Enguia", min: 5, max: 8, cat: "Peixes", era: 1 }
];