dataByProfession.cacador = [
  { name: "Couro", min: 2, max: 3, cat: "Básico" },
  { name: "Couro Reforçado", min: 3, max: 6, cat: "Básico" },
  { name: "Piche", min: 0.5, max: 1, cat: "Básico" },
  { name: "Pluma", min: 1, max: 2, cat: "Básico" },
  { name: "Ovo", min: 1, max: 2, cat: "Básico" },
  { name: "Teia", min: 0.5, max: 1, cat: "Básico" },
  { name: "Vulcan Bee", min: 2, max: 2, cat: "Básico" },
  { name: "Icor", min: 1, max: 1, cat: "Básico" },
  { name: "Berrante", min: 3, max: 5, cat: "Básico" },
  { name: "Couraça", min: 0.3, max: 0.3, cat: "Básico" },
  { name: "Couraça-Grossa", min: 2, max: 4, cat: "Básico" },
  { name: "Crânio Gasto", min: 10, max: 20, cat: "Básico" },
  { name: "Osso", min: 1, max: 1, cat: "Básico" },
  { name: "Marfim", min: 2, max: 3, cat: "Básico" },
  { name: "Peles Reptilianas", min: 1, max: 1, cat: "Básico" },
  { name: "Pele de Lobo", min: 1, max: 1, cat: "Básico" },
  { name: "Pele de Hiena", min: 1, max: 1, cat: "Básico" },
  { name: "Pele de Felino", min: 1, max: 1, cat: "Básico" },
  { name: "Couraça de Rinoceronte", min: 2, max: 3, cat: "Básico" },

  { name: "Carne Saborosa", min: 2, max: 3, cat: "Carnes" },
  { name: "Carne Exótica", min: 2, max: 3, cat: "Carnes" },
  { name: "Carne de Feras", min: 1, max: 1, cat: "Carnes" },
  { name: "Porco Cru", min: 1, max: 4, cat: "Carnes" },
  { name: "Carne Requintada", min: 3, max: 6, cat: "Carnes" },
  { name: "Carne Humana", min: 2, max: 3, cat: "Carnes" },
  { name: "Carne de Ostras", min: 3, max: 6, cat: "Carnes" },

  {
    name: "Couraça de Elefante",
    min: 2,
    max: 3,
    cat: "Partes de Animais",
  },
  { name: "Pele de Urso", min: 2, max: 3, cat: "Partes de Animais" },
  { name: "Pelos", min: 1, max: 2, cat: "Partes de Animais" },
  { name: "Presas", min: 2, max: 3, cat: "Partes de Animais" },
  { name: "Garras", min: 2, max: 3, cat: "Partes de Animais" },
  { name: "Quitina", min: 1, max: 1, cat: "Partes de Animais" },
  {
    name: "Glândula Volátil",
    min: 3,
    max: 5,
    cat: "Partes de Animais",
  },
  {
    name: "Glândula de Veneno de Serpente",
    min: 3,
    max: 5,
    cat: "Partes de Animais",
  },
  {
    name: "Glândula Biliar de Fera das Areias",
    min: 600,
    max: 800,
    cat: "Partes de Animais",
  },
  {
    name: "Glândula de Toxina do Terror",
    min: 4,
    max: 6,
    cat: "Partes de Animais",
  },
  {
    name: "Perna Decepada",
    min: 500,
    max: 1000,
    cat: "Partes de Animais",
  },
  {
    name: "Fragmento do Poder",
    min: 50,
    max: 300,
    cat: "Partes de Animais",
  },
  { name: "Pérola", min: 20, max: 30, cat: "Partes de Animais" },
  { name: "Ectoplasm", min: 50, max: 80, cat: "Partes de Animais" },
  {
    name: "Coração do Deserto",
    min: 1850,
    max: 2775,
    cat: "Partes de Animais",
  },
  { name: "Presa Abismal", min: 5, max: 10, cat: "Partes de Animais" },
  { name: "Olho Abismal", min: 50, max: 100, cat: "Partes de Animais" },

  { name: "Carne Abismal", min: 10, max: 20, cat: "Dungeon & Raros" },
  {
    name: "Glândula de Peçonha Rainha",
    min: 10,
    max: 15,
    cat: "Dungeon & Raros",
  },
  {
    name: "Flor-das-Sombras",
    min: 20,
    max: 25,
    cat: "Dungeon & Raros",
  },
  {
    name: "Carne da Memória",
    min: 50,
    max: 100,
    cat: "Dungeon & Raros",
  },
  {
    name: "Ovo de Escorpião",
    min: 600,
    max: 1000,
    cat: "Dungeon & Raros",
  },
  {
    name: "Máscara Feiticeira",
    min: 1350,
    max: 2025,
    cat: "Dungeon & Raros",
  },
  {
    name: "Estrela do Campeão",
    min: 1350,
    max: 2025,
    cat: "Dungeon & Raros",
  },
  { name: "Aço Khari", min: 100, max: 200, cat: "Dungeon & Raros" },
  {
    name: "Escamas de Dagon",
    min: 200,
    max: 300,
    cat: "Dungeon & Raros",
  },
  {
    name: "Coração do Fratricida",
    min: 1350,
    max: 2025,
    cat: "Dungeon & Raros",
  },
  {
    name: "Lágrima de Duas Raças",
    min: 1350,
    max: 2025,
    cat: "Dungeon & Raros",
  },
  { name: "Trapezedro", min: 1350, max: 2025, cat: "Dungeon & Raros" },
  { name: "Pele de Morcego", min: 2, max: 3, cat: "Dungeon & Raros" },
  {
    name: "Coração do Herói",
    min: 100,
    max: 200,
    cat: "Dungeon & Raros",
  },
  {
    name: "Coração Nordemita",
    min: 10,
    max: 20,
    cat: "Dungeon & Raros",
  },
  { name: "Osso de Dragão", min: 50, max: 100, cat: "Dungeon & Raros" },
  { name: "Pó de Mácula", min: 1, max: 2, cat: "Dungeon & Raros" },
  {
    name: "Máscara Subaquática",
    min: 2000,
    max: 2500,
    cat: "Dungeon & Raros",
  },

  {
    name: "Sangue de Demônio",
    min: 10,
    max: 20,
    cat: "Drops Animais Médios",
  },
  {
    name: "Seda de Ébano",
    min: 150,
    max: 200,
    cat: "Drops Animais Médios",
  },
  {
    name: "Chifre de Dragão",
    min: 200,
    max: 300,
    cat: "Drops Animais Médios",
  },
  {
    name: "Sangue de Urso de Demônio",
    min: 100,
    max: 200,
    cat: "Drops Animais Médios",
  },
  {
    name: "Devil Bear Cub",
    min: 3000,
    max: 6000,
    cat: "Drops Animais Médios",
  },
  {
    name: "Wraith Essence",
    min: 4000,
    max: 4200,
    cat: "Drops Animais Médios",
  },
  {
    name: "Cursed Undead Remains",
    min: 250,
    max: 300,
    cat: "Drops Animais Médios",
  },
  {
    name: "Cursed Rabbit Remains",
    min: 300,
    max: 350,
    cat: "Drops Animais Médios",
  },
  {
    name: "Sangue de Morcego Demoníaco Albino",
    min: 10,
    max: 20,
    cat: "Drops Animais Médios",
  },
  {
    name: "Fragmento de Armadura",
    min: 50,
    max: 100,
    cat: "Drops Animais Médios",
  },
  {
    name: "Sangue Negro",
    min: 50,
    max: 100,
    cat: "Drops Animais Médios",
  },
  {
    name: "Unstable Substance",
    min: 10,
    max: 20,
    cat: "Drops Animais Médios",
  },

  { name: "Cabeça de Alce", min: 30, max: 50, cat: "Cabeças Básicas" },
  {
    name: "Cabeça de Antílope",
    min: 30,
    max: 50,
    cat: "Cabeças Básicas",
  },
  {
    name: "Cabeça de Bico-de-Sapato",
    min: 30,
    max: 50,
    cat: "Cabeças Básicas",
  },
  { name: "Cabeça de Bode", min: 30, max: 50, cat: "Cabeças Básicas" },
  { name: "Cabeça de Cervo", min: 30, max: 50, cat: "Cabeças Básicas" },
  {
    name: "Cabeça de Crocodilo",
    min: 30,
    max: 50,
    cat: "Cabeças Básicas",
  },
  {
    name: "Cabeça de Gazela",
    min: 30,
    max: 50,
    cat: "Cabeças Básicas",
  },
  {
    name: "Cabeça de Gorila",
    min: 30,
    max: 50,
    cat: "Cabeças Básicas",
  },
  { name: "Cabeça de Hiena", min: 30, max: 50, cat: "Cabeças Básicas" },
  {
    name: "Cabeça de Hiena Morta-Viva",
    min: 30,
    max: 50,
    cat: "Cabeças Básicas",
  },
  {
    name: "Cabeça de Jaguar",
    min: 30,
    max: 50,
    cat: "Cabeças Básicas",
  },
  {
    name: "Cabeça de Javali",
    min: 30,
    max: 50,
    cat: "Cabeças Básicas",
  },
  { name: "Cabeça de Kudu", min: 30, max: 50, cat: "Cabeças Básicas" },
  {
    name: "Cabeça de Lombo-Grosso",
    min: 30,
    max: 50,
    cat: "Cabeças Básicas",
  },
  {
    name: "Cabeça de Pantera",
    min: 30,
    max: 50,
    cat: "Cabeças Básicas",
  },
  {
    name: "Cabeça de Rochifre",
    min: 30,
    max: 50,
    cat: "Cabeças Básicas",
  },
  {
    name: "Cabeça de Salamandra",
    min: 30,
    max: 50,
    cat: "Cabeças Básicas",
  },
  { name: "Cabeça de Símio", min: 30, max: 50, cat: "Cabeças Básicas" },
  { name: "Cabeça de Tigre", min: 30, max: 50, cat: "Cabeças Básicas" },
  {
    name: "Cabeça de Urso Marrom",
    min: 30,
    max: 50,
    cat: "Cabeças Básicas",
  },

  {
    name: "Cabeça de Lombo-Grosso Demônio",
    min: 150,
    max: 200,
    cat: "Cabeças Médias",
  },
  {
    name: "Cabeça de Rei Lombo-Grosso",
    min: 150,
    max: 200,
    cat: "Cabeças Médias",
  },
  {
    name: "Cabeça de Homem Serpente Esqueleto",
    min: 150,
    max: 200,
    cat: "Cabeças Médias",
  },
  {
    name: "Cabeça de Mamute",
    min: 150,
    max: 200,
    cat: "Cabeças Médias",
  },
  {
    name: "Cabeça de Rei Rinoceronte",
    min: 150,
    max: 200,
    cat: "Cabeças Médias",
  },
  {
    name: "Cabeça de Rei Rochifre",
    min: 150,
    max: 200,
    cat: "Cabeças Médias",
  },
  {
    name: "Cabeça de Rinoceronte Branco",
    min: 150,
    max: 200,
    cat: "Cabeças Médias",
  },
  {
    name: "Cabeça de Rinoceronte Preto",
    min: 150,
    max: 200,
    cat: "Cabeças Médias",
  },
  {
    name: "Cabeça de Dente-de-Sabre",
    min: 150,
    max: 200,
    cat: "Cabeças Médias",
  },
  {
    name: "Cabeça de Morcego Demoníaco",
    min: 150,
    max: 200,
    cat: "Cabeças Médias",
  },

  {
    name: "Scourge Rhino Head",
    min: 1000,
    max: 1200,
    cat: "Cabeças Especiais",
  },
  {
    name: "Blood Hound Head",
    min: 1000,
    max: 1200,
    cat: "Cabeças Especiais",
  },
  {
    name: "Devil Bear Cub Head",
    min: 1000,
    max: 1200,
    cat: "Cabeças Especiais",
  },
  {
    name: "Kurokumo Head",
    min: 1000,
    max: 1200,
    cat: "Cabeças Especiais",
  },
  {
    name: "Scourge Dweller Head",
    min: 1000,
    max: 1200,
    cat: "Cabeças Especiais",
  },
  {
    name: "Scourge Mammoth Head",
    min: 1000,
    max: 1200,
    cat: "Cabeças Especiais",
  },

  { name: "Akuma Head", min: 2000, max: 2500, cat: "Cabeças Raras" },
  {
    name: "Cabeça de Dragão Verde",
    min: 2000,
    max: 2500,
    cat: "Cabeças Raras",
  },
  {
    name: "Cabeça de Dragão Vermelho",
    min: 2000,
    max: 2500,
    cat: "Cabeças Raras",
  },
  {
    name: "Scourge Hound Head",
    min: 2000,
    max: 2500,
    cat: "Cabeças Raras",
  },
  {
    name: "Cabeça Aranha Demoníaca",
    min: 2000,
    max: 2500,
    cat: "Cabeças Raras",
  },
  { name: "Ashira Head", min: 2000, max: 2500, cat: "Cabeças Raras" },
  {
    name: "Scourge Crocodile Head",
    min: 2000,
    max: 2500,
    cat: "Cabeças Raras",
  },
  {
    name: "Scourge Gargoyle Head",
    min: 2000,
    max: 2500,
    cat: "Cabeças Raras",
  },

  {
    name: "Skull of the Harbinger",
    min: 3000,
    max: 3500,
    cat: "Cabeças Lendárias",
  },
  {
    name: "Spawn of Scargath Head",
    min: 3000,
    max: 3500,
    cat: "Cabeças Lendárias",
  },
  {
    name: "Scourge Dragon Head",
    min: 3000,
    max: 3500,
    cat: "Cabeças Lendárias",
  },
];
