dataByProfession.desocupado = [
  {"name":"Madeira","min":0.1,"max":0.12,"cat":"Basicos","era":1,"ingredients":[]},
  {"name":"Pedra","min":0.1,"max":0.12,"cat":"Basicos","era":1,"ingredients":[]},
  {"name":"Galho","min":0.1,"max":0.12,"cat":"Basicos","era":1,"ingredients":[]},
  {"name":"Casca","min":0.1,"max":0.12,"cat":"Basicos","era":1,"ingredients":[]},
  {"name":"Fibra","min":0.1,"max":0.12,"cat":"Basicos","era":1,"ingredients":[]},
  {"name":"Cogumelo Amanita","min":1,"max":1.2,"cat":"Basicos","era":1,"ingredients":[]},
  {"name":"Gloria de Asura","min":1,"max":1.2,"cat":"Basicos","era":1,"ingredients":[]},
  {"name":"Gelo","min":1,"max":1.2,"cat":"Basicos","era":1,"ingredients":[]},
  {"name":"Fermento","min":1,"max":1.2,"cat":"Basicos","era":1,"ingredients":[]},
  {"name":"Lúpulo","min":1,"max":1.2,"cat":"Basicos","era":1,"ingredients":[]},
  {"name":"Semente","min":1,"max":1.2,"cat":"Basicos","era":1,"ingredients":[]},
  {"name":"Ovo","min":0.25,"max":1,"cat":"Basicos","era":1,"ingredients":[]},
  {"name":"Peixes","min":0,"max":0,"cat":"Pesca","era":1,"ingredients":[]},
  {"name":"Tamboril","min":0,"max":0,"cat":"Pesca","era":1,"ingredients":[]},
  {"name":"Peixe Salgado","min":0,"max":0,"cat":"Pesca","era":1,"ingredients":[]},
  {"name":"Marisco pouco apetitoso","min":0,"max":0,"cat":"Pesca","era":1,"ingredients":[]},
  {"name":"Carne de ostra","min":0,"max":0,"cat":"Pesca","era":1,"ingredients":[]},
  {"name":"Moreia","min":0,"max":0,"cat":"Pesca","era":3,"ingredients":[]},
  {"name":"- Filhote de tartaruga","min":0,"max":0,"cat":"Pesca","era":3,"ingredients":[]},
  {"name":"Garoupa","min":0,"max":0,"cat":"Pesca","era":1,"ingredients":[]},
  {"name":"Peixe insosso","min":0,"max":0,"cat":"Pesca","era":1,"ingredients":[]},
  {"name":"Peixe-Gato","min":0,"max":0,"cat":"Pesca","era":1,"ingredients":[]},
  {"name":"Marisco Salgado","min":0,"max":0,"cat":"Pesca","era":1,"ingredients":[]},
  {"name":"Peixes Exóticos","min":0,"max":0,"cat":"Pesca","era":1,"ingredients":[]},
  {"name":"Marisco Exótico","min":0,"max":0,"cat":"Pesca","era":1,"ingredients":[]},
  {"name":"Cabelo de mulher morta","min":0,"max":0,"cat":"Pesca","era":1,"ingredients":[]},
  {"name":"Pó de túmulo","min":0,"max":0,"cat":"Pesca","era":1,"ingredients":[]},
  {"name":"Olhos da inocência","min":0,"max":0,"cat":"Pesca","era":1,"ingredients":[]},
  {"name":"Old Boot","min":0,"max":0,"cat":"Pesca","era":1,"ingredients":[]},
  {"name":"Mensageiro","min":0,"max":0,"cat":"Serviços","era":1,"ingredients":[]},
  {"name":"Ajudante de Taverna","min":0,"max":0,"cat":"Serviços","era":1,"ingredients":[]},
  {"name":"Leite","min":2,"max":5,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Lã","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Uva","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Trigo","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Tomate","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Tabaco","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Salsinha","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Repolho","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Pimenta","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Pepino","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Morango","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Milho","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Melancia","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Hortelã","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Girasol","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Feijão","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Espinafre","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Folhas de Chá","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Cenoura","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Cebola","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Cana de Açúcar","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Café","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Cacau","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Brócolis","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Mirtilo","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Beterraba","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Amora","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Beringela","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Batata","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Avelã","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Alho","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Alface","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]},
  {"name":"Abobora","min":1,"max":2,"cat":"Fazenda","era":1,"ingredients":[]}
];
