dataByProfession.desocupado = [
  {
    name: "Madeira",
    min: 0.1,
    max: 0.12,
    cat: "BÁSICOS",
    era: 1,
    ingredients: [],
  },
  {
    name: "Pedra",
    min: 0.1,
    max: 0.12,
    cat: "BÁSICOS",
    era: 1,
    ingredients: [],
  },
  {
    name: "Galho",
    min: 0.1,
    max: 0.12,
    cat: "BÁSICOS",
    era: 1,
    ingredients: [],
  },
  {
    name: "Casca",
    min: 0.1,
    max: 0.12,
    cat: "BÁSICOS",
    era: 1,
    ingredients: [],
  },
  {
    name: "Fibra",
    min: 0.1,
    max: 0.12,
    cat: "BÁSICOS",
    era: 1,
    ingredients: [],
  },
  {
    name: "Cogumelo Amanita",
    min: 1,
    max: 1.2,
    cat: "BÁSICOS",
    era: 1,
    ingredients: [],
  },
  {
    name: "Glória de Alura",
    min: 1,
    max: 1.2,
    cat: "BÁSICOS",
    era: 1,
    ingredients: [],
  },
  {
    name: "Gelo",
    min: 1,
    max: 1.2,
    cat: "BÁSICOS",
    era: 1,
    ingredients: [],
  },
  {
    name: "Fermento",
    min: 1,
    max: 1.2,
    cat: "BÁSICOS",
    era: 1,
    ingredients: [],
  },
  {
    name: "Lúpulo",
    min: 1,
    max: 1.2,
    cat: "BÁSICOS",
    era: 1,
    ingredients: [],
  },
  {
    name: "Semente",
    min: 1,
    max: 1.2,
    cat: "BÁSICOS",
    era: 1,
    ingredients: [],
  },
  { name: "Ovo", min: 0.5, max: 1, cat: "BÁSICOS", era: 1, ingredients: [] },

  {
    name: "Mensageiro",
    min: 3,
    max: 5,
    cat: "SERVIÇOS",
    era: 1,
    ingredients: [],
  },
  {
    name: "Ajudante de Taverna",
    min: 3,
    max: 5,
    cat: "SERVIÇOS",
    era: 1,
    ingredients: [],
  },

  { name: "Leite", min: 2, max: 5, cat: "FAZENDA", era: 1, ingredients: [] },
  { name: "Lã", min: 1, max: 2, cat: "FAZENDA", era: 1, ingredients: [] },
  { name: "Uva", min: 1, max: 2, cat: "FAZENDA", era: 1, ingredients: [] },
  { name: "Trigo", min: 1, max: 2, cat: "FAZENDA", era: 1, ingredients: [] },
  { name: "Tomate", min: 1, max: 2, cat: "FAZENDA", era: 1, ingredients: [] },
  { name: "Tabaco", min: 1, max: 2, cat: "FAZENDA", era: 1, ingredients: [] },
  { name: "Salsinha", min: 1, max: 2, cat: "FAZENDA", era: 1, ingredients: [] },
  { name: "Repolho", min: 1, max: 2, cat: "FAZENDA", era: 1, ingredients: [] },
  { name: "Pimenta", min: 1, max: 2, cat: "FAZENDA", era: 1, ingredients: [] },
  { name: "Pepino", min: 1, max: 2, cat: "FAZENDA", era: 1, ingredients: [] },
  { name: "Morango", min: 1, max: 2, cat: "FAZENDA", era: 1, ingredients: [] },
  { name: "Milho", min: 1, max: 2, cat: "FAZENDA", era: 1, ingredients: [] },
  { name: "Melancia", min: 1, max: 2, cat: "FAZENDA", era: 1, ingredients: [] },
  { name: "Hortelã", min: 1, max: 2, cat: "FAZENDA", era: 1, ingredients: [] },
  { name: "Girassol", min: 1, max: 2, cat: "FAZENDA", era: 1, ingredients: [] },
  { name: "Feijão", min: 1, max: 2, cat: "FAZENDA", era: 1, ingredients: [] },
  {
    name: "Espinafre",
    min: 1,
    max: 2,
    cat: "FAZENDA",
    era: 1,
    ingredients: [],
  },
  {
    name: "Folha de Chá",
    min: 1,
    max: 2,
    cat: "FAZENDA",
    era: 1,
    ingredients: [],
  },
  { name: "Cenoura", min: 1, max: 2, cat: "FAZENDA", era: 1, ingredients: [] },
  { name: "Cebola", min: 1, max: 2, cat: "FAZENDA", era: 1, ingredients: [] },
  {
    name: "Cana de Açúcar",
    min: 1,
    max: 2,
    cat: "FAZENDA",
    era: 1,
    ingredients: [],
  },
  { name: "Café", min: 1, max: 2, cat: "FAZENDA", era: 1, ingredients: [] },
  { name: "Cacau", min: 1, max: 2, cat: "FAZENDA", era: 1, ingredients: [] },
  { name: "Brócolis", min: 1, max: 2, cat: "FAZENDA", era: 1, ingredients: [] },
  { name: "Mirtilo", min: 1, max: 2, cat: "FAZENDA", era: 1, ingredients: [] },
  {
    name: "Beterraba",
    min: 1,
    max: 2,
    cat: "FAZENDA",
    era: 1,
    ingredients: [],
  },
  { name: "Amora", min: 1, max: 2, cat: "FAZENDA", era: 1, ingredients: [] },
  {
    name: "Berinjela",
    min: 1,
    max: 2,
    cat: "FAZENDA",
    era: 1,
    ingredients: [],
  },
  { name: "Batata", min: 1, max: 2, cat: "FAZENDA", era: 1, ingredients: [] },
  { name: "Aveia", min: 1, max: 2, cat: "FAZENDA", era: 1, ingredients: [] },
  { name: "Alho", min: 1, max: 2, cat: "FAZENDA", era: 1, ingredients: [] },
  { name: "Alface", min: 1, max: 2, cat: "FAZENDA", era: 1, ingredients: [] },
  { name: "Abóbora", min: 1, max: 2, cat: "FAZENDA", era: 1, ingredients: [] },
];
