dataByProfession.ferreiro = [
  {"name":"Reforço de Ferro","min":2,"max":4,"cat":"INICIAL","era":1,"ingredients":[{"qty":2,"item":"Barra de Ferro"}]},
  {"name":"Reforço de Aço","min":17,"max":20,"cat":"INICIAL","era":2,"ingredients":[{"qty":2,"item":"Barra de Aço"}]},
  {"name":"Chromium Reinforcement","min":82,"max":98,"cat":"INICIAL","era":3,"ingredients":[{"qty":1,"item":"Carbon"},{"qty":2,"item":"Aluminium"},{"qty":3,"item":"Reforço de Aço"}]},
  {"name":"Iron Torch","min":82,"max":99,"cat":"INICIAL","era":1,"ingredients":[{"qty":12,"item":"Barra de Ferro"},{"qty":5,"item":"Reforço de Ferro"},{"qty":5,"item":"Madeira Moldada"}]},
  {"name":"Molde Frasco de Vidro","min":26,"max":32,"cat":"MOLDES","era":1,"ingredients":[{"qty":15,"item":"Barra de Ferro"}]},
  {"name":"Frasco de Vidro","min":5,"max":6,"cat":"MOLDES","era":1,"ingredients":[{"qty":3,"item":"Vidro"}]},
  {"name":"Molde de Moedas","min":26,"max":32,"cat":"MOLDES","era":1,"ingredients":[{"qty":15,"item":"Barra de Ferro"}]},
  {"name":"Molde de Tiara","min":26,"max":32,"cat":"MOLDES","era":1,"ingredients":[{"qty":15,"item":"Barra de Ferro"}]},
  {"name":"Molde de Tornozeleira","min":26,"max":32,"cat":"MOLDES","era":1,"ingredients":[{"qty":15,"item":"Barra de Ferro"}]},
  {"name":"Molde de Bracelete","min":26,"max":32,"cat":"MOLDES","era":1,"ingredients":[{"qty":15,"item":"Barra de Ferro"}]},
  {"name":"Molde de Brinco","min":26,"max":32,"cat":"MOLDES","era":1,"ingredients":[{"qty":15,"item":"Barra de Ferro"}]},
  {"name":"Moeda de Prata","min":54,"max":65,"cat":"MOEDAS","era":2,"ingredients":[{"qty":1,"item":"Molde de Moedas"},{"qty":1,"item":"Barra de Prata"}]},
  {"name":"Moeda de Ouro","min":62,"max":74,"cat":"MOEDAS","era":2,"ingredients":[{"qty":1,"item":"Molde de Moedas"},{"qty":1,"item":"Barra de Ouro"}]},
  {"name":"Bracelete de Ferro","min":40,"max":48,"cat":"JOIAS","era":1,"ingredients":[{"qty":1,"item":"Molde de Bracelete"},{"qty":1,"item":"Barra de Ferro"}]},
  {"name":"Bracelete de Ouro","min":107,"max":128,"cat":"JOIAS","era":2,"ingredients":[{"qty":1,"item":"Molde de Bracelete"},{"qty":3,"item":"Barra de Ouro"}]},
  {"name":"Bracelete de Prata","min":84,"max":101,"cat":"JOIAS","era":2,"ingredients":[{"qty":1,"item":"Molde de Bracelete"},{"qty":3,"item":"Barra de Prata"}]},
  {"name":"Braceletes com Joias","min":107,"max":128,"cat":"JOIAS","era":2,"ingredients":[{"qty":1,"item":"Molde de Bracelete"},{"qty":3,"item":"Barra de Ouro"}]},
  {"name":"Brincos de Ferro","min":40,"max":48,"cat":"JOIAS","era":1,"ingredients":[{"qty":1,"item":"Molde de Brinco"},{"qty":1,"item":"Barra de Ferro"}]},
  {"name":"Brincos de Ouro","min":107,"max":128,"cat":"JOIAS","era":2,"ingredients":[{"qty":1,"item":"Molde de Brinco"},{"qty":3,"item":"Barra de Ouro"}]},
  {"name":"Brincos de Prata","min":84,"max":101,"cat":"JOIAS","era":2,"ingredients":[{"qty":1,"item":"Molde de Brinco"},{"qty":3,"item":"Barra de Prata"}]},
  {"name":"Correntes de Joias","min":68,"max":81,"cat":"JOIAS","era":2,"ingredients":[{"qty":3,"item":"Barra de Ouro"}]},
  {"name":"Coxal com Joias","min":68,"max":81,"cat":"JOIAS","era":2,"ingredients":[{"qty":3,"item":"Barra de Ouro"}]},
  {"name":"Tiara de Ferro","min":40,"max":48,"cat":"JOIAS","era":1,"ingredients":[{"qty":1,"item":"Molde de Tiara"},{"qty":1,"item":"Barra de Ferro"}]},
  {"name":"Tiara de Ferro e Brincos","min":120,"max":144,"cat":"JOIAS","era":1,"ingredients":[{"qty":1,"item":"Brincos de Ferro"},{"qty":1,"item":"Tiara de Ferro"}]},
  {"name":"Tiara de Joias","min":107,"max":128,"cat":"JOIAS","era":2,"ingredients":[{"qty":1,"item":"Molde de Tiara"},{"qty":3,"item":"Barra de Ouro"}]},
  {"name":"Tiara de Ouro","min":107,"max":128,"cat":"JOIAS","era":2,"ingredients":[{"qty":1,"item":"Molde de Tiara"},{"qty":3,"item":"Barra de Ouro"}]},
  {"name":"Tiara de Ouro de Brincos","min":321,"max":385,"cat":"JOIAS","era":2,"ingredients":[{"qty":1,"item":"Tiara de Ouro"},{"qty":1,"item":"Brincos de Ouro"}]},
  {"name":"Tiara de Prata","min":84,"max":101,"cat":"JOIAS","era":2,"ingredients":[{"qty":1,"item":"Molde de Tiara"},{"qty":3,"item":"Barra de Prata"}]},
  {"name":"Tiara de Prata e Brincos","min":253,"max":304,"cat":"JOIAS","era":2,"ingredients":[{"qty":1,"item":"Tiara de Prata"},{"qty":1,"item":"Brincos de Prata"}]},
  {"name":"Tornozeleira com Ferro","min":40,"max":48,"cat":"JOIAS","era":1,"ingredients":[{"qty":1,"item":"Molde de Tornozeleira"},{"qty":1,"item":"Barra de Ferro"}]},
  {"name":"Tornozeleira com Joias","min":62,"max":74,"cat":"JOIAS","era":2,"ingredients":[{"qty":1,"item":"Molde de Tornozeleira"},{"qty":1,"item":"Barra de Ouro"}]},
  {"name":"Tornozeleira com Ouro","min":62,"max":74,"cat":"JOIAS","era":2,"ingredients":[{"qty":1,"item":"Molde de Tornozeleira"},{"qty":1,"item":"Barra de Ouro"}]},
  {"name":"Tornozeleira com Prata","min":54,"max":65,"cat":"JOIAS","era":2,"ingredients":[{"qty":1,"item":"Molde de Tornozeleira"},{"qty":1,"item":"Barra de Prata"}]},
  {"name":"Foice de Ferro","min":88,"max":106,"cat":"FOICES","era":1,"ingredients":[{"qty":30,"item":"Barra de Ferro"},{"qty":5,"item":"Galho"}]},
  {"name":"Foice de Aço","min":264,"max":317,"cat":"FOICES","era":2,"ingredients":[{"qty":30,"item":"Barra de Aço"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Foice de Aço Reforçado","min":389,"max":466,"cat":"FOICES","era":3,"ingredients":[{"qty":30,"item":"Barra de Aço Enrijecida"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Foice de Aqueronte","min":524,"max":628,"cat":"FOICES","era":3,"ingredients":[{"qty":30,"item":"Barra de Aço Enrijecida"},{"qty":4,"item":"Madeira Moldada"},{"qty":10,"item":"Base Alquímica"}]},
  {"name":"Foice de Metal das Estrelas","min":755,"max":905,"cat":"FOICES","era":4,"ingredients":[{"qty":30,"item":"Barra de Metal das Estrelas"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Foice de Obsidiana","min":2526,"max":3031,"cat":"FOICES","era":5,"ingredients":[{"qty":20,"item":"Compósito de Obsidiana"},{"qty":4,"item":"Madeira Moldada"},{"qty":10,"item":"Base Alquímica"}]},
  {"name":"Machadinha de Ferro","min":88,"max":106,"cat":"MACHADINHAS","era":1,"ingredients":[{"qty":30,"item":"Barra de Ferro"},{"qty":5,"item":"Galho"}]},
  {"name":"Machadinha de Aço","min":299,"max":359,"cat":"MACHADINHAS","era":2,"ingredients":[{"qty":30,"item":"Barra de Aço"},{"qty":5,"item":"Galho"},{"qty":15,"item":"Couro"}]},
  {"name":"Machadinha de Aço Reforçado","min":389,"max":466,"cat":"MACHADINHAS","era":3,"ingredients":[{"qty":30,"item":"Barra de Aço Enrijecida"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Machadinha de Metal das Estrelas","min":755,"max":905,"cat":"MACHADINHAS","era":4,"ingredients":[{"qty":30,"item":"Barra de Metal das Estrelas"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Machadinha de Obsidiana","min":2526,"max":3031,"cat":"MACHADINHAS","era":5,"ingredients":[{"qty":20,"item":"Composito de Obsidian"},{"qty":4,"item":"Madeira Moldada"},{"qty":10,"item":"Base Alquímica"}]},
  {"name":"Picareta de Ferro","min":88,"max":106,"cat":"PICARETAS","era":1,"ingredients":[{"qty":30,"item":"Barra de Ferro"},{"qty":5,"item":"Galho"}]},
  {"name":"Picareta de Aço","min":299,"max":359,"cat":"PICARETAS","era":2,"ingredients":[{"qty":30,"item":"Barra de Aço"},{"qty":5,"item":"Galho"},{"qty":15,"item":"Couro"}]},
  {"name":"Picareta Dupla","min":299,"max":359,"cat":"PICARETAS","era":2,"ingredients":[{"qty":30,"item":"Barra de Aço"},{"qty":5,"item":"Galho"},{"qty":15,"item":"Couro"}]},
  {"name":"Picareta de Aço Reforçado","min":389,"max":466,"cat":"PICARETAS","era":3,"ingredients":[{"qty":30,"item":"Barra de Aço Enrijecida"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Picareta de Aqueronte","min":524,"max":628,"cat":"PICARETAS","era":3,"ingredients":[{"qty":30,"item":"Barra de Aço Enrijecida"},{"qty":4,"item":"Madeira Moldada"},{"qty":10,"item":"Base Alquímica"}]},
  {"name":"Picareta de Metal das Estrelas","min":755,"max":905,"cat":"PICARETAS","era":4,"ingredients":[{"qty":30,"item":"Barra de Metal das Estrelas"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Picareta Dupla de Metal das Estrelas","min":755,"max":905,"cat":"PICARETAS","era":4,"ingredients":[{"qty":30,"item":"Barra de Metal das Estrelas"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Picareta de Obsidiana","min":2526,"max":3031,"cat":"PICARETAS","era":5,"ingredients":[{"qty":20,"item":"Compósito de Obsidiana"},{"qty":4,"item":"Madeira Moldada"},{"qty":10,"item":"Base Alquímica"}]},
  {"name":"Cutelo de Ferro","min":88,"max":106,"cat":"CUTELOS","era":1,"ingredients":[{"qty":30,"item":"Barra de Ferro"},{"qty":5,"item":"Galho"}]},
  {"name":"Chef's Cleaver","min":168,"max":201,"cat":"CUTELOS","era":1,"ingredients":[{"qty":15,"item":"Reforço de Ferro"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Skull Cleaver","min":168,"max":201,"cat":"CUTELOS","era":1,"ingredients":[{"qty":15,"item":"Reforço de Ferro"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Cutelo de Aço","min":203,"max":244,"cat":"CUTELOS","era":2,"ingredients":[{"qty":24,"item":"Barra de Aço"},{"qty":5,"item":"Galho"}]},
  {"name":"Cutelo de Aço Reforçado","min":307,"max":369,"cat":"CUTELOS","era":3,"ingredients":[{"qty":24,"item":"Barra de Aço Enrijecida"},{"qty":2,"item":"Madeira Moldada"}]},
  {"name":"Cutelo de Metal das Estrelas","min":600,"max":720,"cat":"CUTELOS","era":4,"ingredients":[{"qty":24,"item":"Barra de Metal das Estrelas"},{"qty":2,"item":"Madeira Moldada"}]},
  {"name":"Faca de Ferro para Esfolamento","min":88,"max":106,"cat":"FACA DE ESFOLAMENTOS","era":1,"ingredients":[{"qty":30,"item":"Barra de Ferro"},{"qty":5,"item":"Galho"}]},
  {"name":"Faca de Aço para Esfolamento","min":264,"max":317,"cat":"FACA DE ESFOLAMENTOS","era":2,"ingredients":[{"qty":30,"item":"Barra de Aço"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Faca de Aço Reforçado para Esfolamento","min":389,"max":466,"cat":"FACA DE ESFOLAMENTOS","era":3,"ingredients":[{"qty":30,"item":"Barra de Aço Enrijecida"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Faca de Metal das Estrelas para Esfolamento","min":755,"max":905,"cat":"FACA DE ESFOLAMENTOS","era":4,"ingredients":[{"qty":30,"item":"Barra de Metal das Estrelas"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Faca de Obsidiana para Esfolamento","min":3132,"max":3758,"cat":"FACA DE ESFOLAMENTOS","era":5,"ingredients":[{"qty":30,"item":"Compósito de Obsidiana"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Martelo de Reparos de Aço","min":254,"max":305,"cat":"MARTELO DE REPAROS","era":2,"ingredients":[{"qty":30,"item":"Barra de Aço"},{"qty":5,"item":"Galho"}]},
  {"name":"Martelo de Reparos de Metal das Estrelas","min":755,"max":905,"cat":"MARTELO DE REPAROS","era":4,"ingredients":[{"qty":30,"item":"Barra de Metal das Estrelas"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Espada de Ferro Afiada","min":88,"max":106,"cat":"ESPADAS","era":1,"ingredients":[{"qty":30,"item":"Barra de Ferro"},{"qty":5,"item":"Galho"}]},
  {"name":"Espada curta de ferro","min":88,"max":106,"cat":"ESPADAS","era":1,"ingredients":[{"qty":30,"item":"Barra de Ferro"},{"qty":5,"item":"Galho"}]},
  {"name":"Alfanje","min":88,"max":106,"cat":"ESPADAS","era":1,"ingredients":[{"qty":30,"item":"Barra de Ferro"},{"qty":5,"item":"Galho"}]},
  {"name":"Espada de Ferro de Duas Mãos","min":129,"max":155,"cat":"ESPADAS","era":1,"ingredients":[{"qty":45,"item":"Barra de Ferro"},{"qty":5,"item":"Galho"}]},
  {"name":"Dual Iron Broadsword","min":121,"max":145,"cat":"ESPADAS","era":1,"ingredients":[{"qty":40,"item":"Barra de Ferro"},{"qty":10,"item":"Galho"}]},
  {"name":"Espada Longa","min":254,"max":305,"cat":"ESPADAS","era":2,"ingredients":[{"qty":5,"item":"Galho"},{"qty":30,"item":"Barra de Aço"}]},
  {"name":"Falcata","min":254,"max":305,"cat":"ESPADAS","era":2,"ingredients":[{"qty":5,"item":"Galho"},{"qty":30,"item":"Barra de Aço"}]},
  {"name":"Espada curta de Aço","min":254,"max":305,"cat":"ESPADAS","era":2,"ingredients":[{"qty":30,"item":"Barra de Aço"},{"qty":5,"item":"Galho"}]},
  {"name":"Espada de Aço de Duas Mãos","min":380,"max":456,"cat":"ESPADAS","era":2,"ingredients":[{"qty":45,"item":"Barra de Aço"},{"qty":5,"item":"Galho"}]},
  {"name":"Espada Reliquia de Duas Mãos","min":290,"max":348,"cat":"ESPADAS","era":2,"ingredients":[{"qty":33,"item":"Barra de Aço"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Espada de Aço Enrijecido","min":389,"max":466,"cat":"ESPADAS","era":3,"ingredients":[{"qty":30,"item":"Barra de Aço Enrijecida"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Espada curta de Aço reforçado","min":389,"max":466,"cat":"ESPADAS","era":3,"ingredients":[{"qty":30,"item":"Barra de Aço Enrijecida"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Espada Longa de Aqueronte","min":647,"max":776,"cat":"ESPADAS","era":3,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":30,"item":"Barra de Aço Enrijecida"},{"qty":10,"item":"Base Alquímica"}]},
  {"name":"Espada de Duas Mãos de Aqueronte","min":647,"max":776,"cat":"ESPADAS","era":3,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":30,"item":"Barra de Aço Enrijecida"},{"qty":10,"item":"Base Alquímica"}]},
  {"name":"Grande Espada de Aço Reforçado","min":389,"max":466,"cat":"ESPADAS","era":3,"ingredients":[{"qty":30,"item":"Barras de Aço enrijecida"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Acheronian Dual Longsword","min":714,"max":857,"cat":"ESPADAS","era":3,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":30,"item":"Barra de Aço Enrijecida"},{"qty":15,"item":"Base Alquímica"}]},
  {"name":"Espada Lemuriana Antiga","min":2079,"max":2495,"cat":"ESPADAS","era":3,"ingredients":[{"qty":30,"item":"Barra de Aço Enrijecida"},{"qty":5,"item":"Base Alquímica"},{"qty":5,"item":"Escama de Dagon"}]},
  {"name":"Espada Curta de Metal das Estrelas","min":878,"max":1053,"cat":"ESPADAS","era":4,"ingredients":[{"qty":30,"item":"Barra de Metal das Estrelas"},{"qty":1,"item":"Empunhadura de Arma"}]},
  {"name":"Espada de Metal das Estrelas","min":945,"max":1134,"cat":"ESPADAS","era":4,"ingredients":[{"qty":30,"item":"Barra de Metal das Estrelas"},{"qty":1,"item":"Empunhadura de Arma"},{"qty":15,"item":"Couro Reforçado"}]},
  {"name":"Grande Espada de Metal das Estrelas","min":878,"max":1053,"cat":"ESPADAS","era":4,"ingredients":[{"qty":30,"item":"Barra de Metal das Estrelas"},{"qty":1,"item":"Empunhadura de Arma"}]},
  {"name":"Espada de Obsidiana","min":3640,"max":4368,"cat":"ESPADAS","era":5,"ingredients":[{"qty":30,"item":"Compósito de Obsidiana"},{"qty":1,"item":"Empunhadura de Arma"},{"qty":5,"item":"Base Alquímica"}]},
  {"name":"Espada Grande de Obsidiana","min":3640,"max":4368,"cat":"ESPADAS","era":5,"ingredients":[{"qty":30,"item":"Compósito de Obsidiana"},{"qty":1,"item":"Empunhadura de Arma"},{"qty":5,"item":"Base Alquímica"}]},
  {"name":"Espadas Duplas de Ferro","min":85,"max":102,"cat":"Espadas Duplas","era":1,"ingredients":[{"qty":30,"item":"Barra de Ferro"},{"qty":5,"item":"Galho"}]},
  {"name":"Espadas Duplas de Aço","min":253,"max":304,"cat":"Espadas Duplas","era":2,"ingredients":[{"qty":30,"item":"Barra de Aço"},{"qty":5,"item":"Galho"}]},
  {"name":"Espadas Duplas de Aço Enrijecido","min":389,"max":466,"cat":"Espadas Duplas","era":3,"ingredients":[{"qty":30,"item":"Barra de Aço Enrijecida"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Espadas Duplas Arqueronte","min":647,"max":776,"cat":"Espadas Duplas","era":3,"ingredients":[{"qty":30,"item":"Barra de Aço Enrijecida"},{"qty":10,"item":"Base Alquímica"},{"qty":1,"item":"Empunhadura de Arma"}]},
  {"name":"Espadas Duplas de Metal das Estrelas","min":878,"max":1053,"cat":"Espadas Duplas","era":4,"ingredients":[{"qty":30,"item":"Barra de Metal das Estrelas"},{"qty":1,"item":"Empunhadura de Arma"}]},
  {"name":"Espadas Duplas de Obsidiana","min":3640,"max":4368,"cat":"Espadas Duplas","era":5,"ingredients":[{"qty":30,"item":"Compósito de Obsidiana"},{"qty":5,"item":"Base Alquímica"},{"qty":1,"item":"Empunhadura de Arma"}]},
  {"name":"Lança de Ferro","min":133,"max":159,"cat":"LANÇAS","era":1,"ingredients":[{"qty":45,"item":"Barra de Ferro"},{"qty":8,"item":"Galho"}]},
  {"name":"Corseque de Ferro","min":88,"max":106,"cat":"LANÇAS","era":1,"ingredients":[{"qty":30,"item":"Barra de Ferro"},{"qty":5,"item":"Galho"}]},
  {"name":"Lança de Aço","min":304,"max":365,"cat":"LANÇAS","era":2,"ingredients":[{"qty":36,"item":"Barra de Aço"},{"qty":5,"item":"Galho"}]},
  {"name":"Pique Antigo","min":267,"max":321,"cat":"LANÇAS","era":2,"ingredients":[{"qty":30,"item":"Barra de Aço"},{"qty":5,"item":"Madeira Moldada"}]},
  {"name":"Lança de Aço Enrijecido","min":577,"max":692,"cat":"LANÇAS","era":3,"ingredients":[{"qty":45,"item":"Barra de Aço Enrijecida"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Lança de Aqueronte","min":647,"max":776,"cat":"LANÇAS","era":3,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":30,"item":"Barra de Aço Enrijecida"},{"qty":10,"item":"Base Alquímica"}]},
  {"name":"Lança de Metal das Estrelas","min":1249,"max":1499,"cat":"LANÇAS","era":4,"ingredients":[{"qty":45,"item":"Barra de Metal das Estrelas"},{"qty":1,"item":"Empunhadura de Arma"}]},
  {"name":"Lança de Obsidiana","min":3640,"max":4368,"cat":"LANÇAS","era":5,"ingredients":[{"qty":30,"item":"Compósito de Obsidiana"},{"qty":1,"item":"Empunhadura de Arma"},{"qty":5,"item":"Base Alquímica"}]},
  {"name":"Núcleo de Hasta","min":95,"max":113,"cat":"HASTA","era":1,"ingredients":[{"qty":10,"item":"Madeira Resinada"},{"qty":15,"item":"Couro"},{"qty":10,"item":"Resina"}]},
  {"name":"Hasta Leve","min":29,"max":35,"cat":"HASTA","era":1,"ingredients":[{"qty":6,"item":"Madeira Moldada"},{"qty":15,"item":"Barra de Ferro"}]},
  {"name":"Hasta Forte","min":29,"max":35,"cat":"HASTA","era":1,"ingredients":[{"qty":6,"item":"Madeira Moldada"},{"qty":15,"item":"Barra de Ferro"}]},
  {"name":"Hasta Pesada","min":29,"max":35,"cat":"HASTA","era":1,"ingredients":[{"qty":6,"item":"Madeira Moldada"},{"qty":15,"item":"Barra de Ferro"}]},
  {"name":"Hasta Leve Épica","min":686,"max":824,"cat":"HASTA","era":4,"ingredients":[{"qty":1,"item":"Núcleo de Hasta"},{"qty":22,"item":"Barra de Metal das Estrelas"}]},
  {"name":"Hasta Forte Épica","min":686,"max":824,"cat":"HASTA","era":4,"ingredients":[{"qty":1,"item":"Núcleo de Hasta"},{"qty":22,"item":"Barra de Metal das Estrelas"}]},
  {"name":"Hasta Pesada Épica","min":686,"max":824,"cat":"HASTA","era":4,"ingredients":[{"qty":1,"item":"Núcleo de Hasta"},{"qty":22,"item":"Barra de Metal das Estrelas"}]},
  {"name":"Maça Pesada de Ferro","min":88,"max":106,"cat":"MAÇAS","era":1,"ingredients":[{"qty":30,"item":"Barra de Ferro"},{"qty":5,"item":"Galho"}]},
  {"name":"Maça Reforçada de Ferro","min":88,"max":106,"cat":"MAÇAS","era":1,"ingredients":[{"qty":30,"item":"Barra de Ferro"},{"qty":5,"item":"Galho"}]},
  {"name":"Maça de Ferro","min":88,"max":106,"cat":"MAÇAS","era":1,"ingredients":[{"qty":30,"item":"Barra de Ferro"},{"qty":5,"item":"Galho"}]},
  {"name":"Maça de Aço","min":254,"max":305,"cat":"MAÇAS","era":2,"ingredients":[{"qty":30,"item":"Barra de Aço"},{"qty":5,"item":"Galho"}]},
  {"name":"Maça Antiga","min":293,"max":351,"cat":"MAÇAS","era":2,"ingredients":[{"qty":33,"item":"Barra de Aço"},{"qty":5,"item":"Madeira Moldada"}]},
  {"name":"Maça de Aço Reforçado","min":389,"max":466,"cat":"MAÇAS","era":3,"ingredients":[{"qty":30,"item":"Barra de Aço Enrijecida"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Maça de Metal das Estrelas","min":878,"max":1053,"cat":"MAÇAS","era":4,"ingredients":[{"qty":30,"item":"Barra de Metal das Estrelas"},{"qty":1,"item":"Empunhadura de Arma"}]},
  {"name":"Maça de Obsidiana","min":3640,"max":4368,"cat":"MAÇAS","era":5,"ingredients":[{"qty":30,"item":"Compósito de Obsidiana"},{"qty":1,"item":"Empunhadura de Arma"},{"qty":5,"item":"Base Alquímica"}]},
  {"name":"Machado de Ferro","min":88,"max":106,"cat":"MACHADOS","era":1,"ingredients":[{"qty":30,"item":"Barra de Ferro"},{"qty":5,"item":"Galho"}]},
  {"name":"Machado de Guerra de Ferro","min":88,"max":106,"cat":"MACHADOS","era":1,"ingredients":[{"qty":30,"item":"Barra de Ferro"},{"qty":5,"item":"Galho"}]},
  {"name":"Machado de Guerra Cimério","min":254,"max":305,"cat":"MACHADOS","era":2,"ingredients":[{"qty":30,"item":"Barra de Aço"},{"qty":5,"item":"Galho"}]},
  {"name":"Machado Milenar","min":264,"max":317,"cat":"MACHADOS","era":2,"ingredients":[{"qty":30,"item":"Barra de Aço"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Machado de Guerra de Aço Reforçado","min":389,"max":466,"cat":"MACHADOS","era":3,"ingredients":[{"qty":30,"item":"Barra de Aço Enrijecida"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Machado de Guerra de Aqueronte","min":606,"max":727,"cat":"MACHADOS","era":3,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":30,"item":"Barra de Aço Enrijecida"},{"qty":7,"item":"Base Alquímica"}]},
  {"name":"Machado de Metal das Estrelas","min":680,"max":815,"cat":"MACHADOS","era":4,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":22,"item":"Barra de Metal das Estrelas"}]},
  {"name":"Machado de Arremesso","min":19,"max":23,"cat":"MACHADOS","era":1,"ingredients":[{"qty":5,"item":"Barra de Ferro"},{"qty":5,"item":"Galho"}]},
  {"name":"Machado de Arremesso de Aço","min":44,"max":52,"cat":"MACHADOS","era":2,"ingredients":[{"qty":5,"item":"Barra de Aço"},{"qty":5,"item":"Galho"}]},
  {"name":"Machado de Arremesso Milenar","min":45,"max":54,"cat":"MACHADOS","era":2,"ingredients":[{"qty":5,"item":"Barra de Aço"},{"qty":1,"item":"Madeira Moldada"}]},
  {"name":"Machado de Arremesso de Aço Reforçado","min":41,"max":49,"cat":"MACHADOS","era":3,"ingredients":[{"qty":3,"item":"Barra de Aço Enrijecida"},{"qty":1,"item":"Madeira Moldada"}]},
  {"name":"Machado de Arremesso de Metal das Estrelas","min":209,"max":251,"cat":"MACHADOS","era":4,"ingredients":[{"qty":3,"item":"Barra de Metal das Estrelas"},{"qty":1,"item":"Empunhadura de Arma"}]},
  {"name":"Machado de Arremesso de Obsidiana","min":463,"max":556,"cat":"MACHADOS","era":5,"ingredients":[{"qty":1,"item":"Compósito de Obsidiana"},{"qty":1,"item":"Empunhadura de Arma"}]},
  {"name":"Iron War Blade","min":63,"max":76,"cat":"WAR BLADE","era":1,"ingredients":[{"qty":20,"item":"Barra de Ferro"},{"qty":5,"item":"Barbante"}]},
  {"name":"Steel War Blade","min":171,"max":205,"cat":"WAR BLADE","era":2,"ingredients":[{"qty":20,"item":"Barra de Aço"},{"qty":5,"item":"Barbante"}]},
  {"name":"Hardened Steel","min":269,"max":323,"cat":"WAR BLADE","era":3,"ingredients":[{"qty":20,"item":"Barra de Aço Enrijecida"},{"qty":4,"item":"Couro Reforçado"}]},
  {"name":"Tempered Blade","min":521,"max":625,"cat":"WAR BLADE","era":4,"ingredients":[{"qty":20,"item":"Barra de Aço Enrijecida"},{"qty":10,"item":"Base Alquímica"},{"qty":1,"item":"Empunhadura de Arma"}]},
  {"name":"Dual Obsidian Swords","min":18198,"max":21838,"cat":"WAR BLADE","era":5,"ingredients":[{"qty":30,"item":"Compósito de Obsidiana"},{"qty":1,"item":"Empunhadura de Arma"},{"qty":5,"item":"Base Alquímica"}]},
  {"name":"Grande machado de ferro para duas mãos","min":88,"max":106,"cat":"MACHADO DUAS MÃOS","era":1,"ingredients":[{"qty":30,"item":"Barra de Ferro"},{"qty":5,"item":"Galho"}]},
  {"name":"Grande machado de duas mãos de aço","min":254,"max":305,"cat":"MACHADO DUAS MÃOS","era":2,"ingredients":[{"qty":30,"item":"Barra de Aço"},{"qty":5,"item":"Galho"}]},
  {"name":"Steel Bearded Greataxe","min":255,"max":306,"cat":"MACHADO DUAS MÃOS","era":2,"ingredients":[{"qty":30,"item":"Barra de Aço"},{"qty":8,"item":"Galho"}]},
  {"name":"Grande machado de duas mãos de aço reforçado","min":389,"max":466,"cat":"MACHADO DUAS MÃOS","era":3,"ingredients":[{"qty":30,"item":"Barra de Aço Enrijecida"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Grande machado de Metal das Estrelas","min":878,"max":1053,"cat":"MACHADO DUAS MÃOS","era":4,"ingredients":[{"qty":30,"item":"Barra de Metal das Estrelas"},{"qty":1,"item":"Empunhadura de Arma"}]},
  {"name":"Iron GreatBlade","min":88,"max":106,"cat":"GREATBLADE","era":1,"ingredients":[{"qty":30,"item":"Barra de Ferro"},{"qty":5,"item":"Galho"}]},
  {"name":"Steel GreatBlade","min":170,"max":204,"cat":"GREATBLADE","era":2,"ingredients":[{"qty":20,"item":"Barra de Aço"},{"qty":5,"item":"Galho"}]},
  {"name":"Hardened Steel GreatBlade","min":269,"max":323,"cat":"GREATBLADE","era":3,"ingredients":[{"qty":20,"item":"Barra de Aço Enrijecida"},{"qty":4,"item":"Couro Reforçado"}]},
  {"name":"Star Metal GreatBlade","min":765,"max":918,"cat":"GREATBLADE","era":4,"ingredients":[{"qty":20,"item":"Barra de Metal das Estrelas"},{"qty":10,"item":"Base Alquímica"},{"qty":1,"item":"Empunhadura de Arma"}]},
  {"name":"Espada Grande de Obsidiana","min":3640,"max":4368,"cat":"GREATBLADE","era":5,"ingredients":[{"qty":30,"item":"Compósito de Obsidiana"},{"qty":1,"item":"Empunhadura de Arma"},{"qty":5,"item":"Base Alquímica"}]},
  {"name":"Katana","min":26,"max":31,"cat":"KATANA","era":1,"ingredients":[{"qty":33,"item":"Barra de Ferro"},{"qty":3,"item":"Galho"}]},
  {"name":"Hardened Steel Katana","min":0,"max":0,"cat":"KATANA","era":3,"ingredients":[{"qty":0,"item":"X"},{"qty":0,"item":"X"}]},
  {"name":"Katana de Metal das Estrelas","min":680,"max":815,"cat":"KATANA","era":4,"ingredients":[{"qty":22,"item":"Barra de Metal das Estrelas"},{"qty":1,"item":"Empunhadura de Arma"}]},
  {"name":"Punhais de Ferro","min":88,"max":106,"cat":"ADAGAS","era":1,"ingredients":[{"qty":30,"item":"Barra de Ferro"},{"qty":5,"item":"Galho"}]},
  {"name":"Punhais de Aço","min":303,"max":364,"cat":"ADAGAS","era":2,"ingredients":[{"qty":30,"item":"Barra de Aço"},{"qty":5,"item":"Galho"},{"qty":11,"item":"Couro Reforçado"}]},
  {"name":"Adagas Antigas","min":290,"max":348,"cat":"ADAGAS","era":2,"ingredients":[{"qty":33,"item":"Barra de Aço"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Adagas de Aço Reforçado","min":389,"max":466,"cat":"ADAGAS","era":3,"ingredients":[{"qty":30,"item":"Barra de Aço Enrijecida"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Adagas de Metal das Estrelas","min":878,"max":1053,"cat":"ADAGAS","era":4,"ingredients":[{"qty":30,"item":"Barra de Metal das Estrelas"},{"qty":1,"item":"Empunhadura de Arma"}]},
  {"name":"Adagas de Obsidiana","min":3640,"max":4368,"cat":"ADAGAS","era":5,"ingredients":[{"qty":30,"item":"Compósito de Obsidiana"},{"qty":1,"item":"Empunhadura de Arma"},{"qty":5,"item":"Base Alquímica"}]},
  {"name":"Adagas-de-Soco de Ferro","min":253,"max":304,"cat":"Adagas-de-Soco","era":1,"ingredients":[{"qty":30,"item":"Barra de Ferro"},{"qty":5,"item":"Galho"},{"qty":15,"item":"Couro"}]},
  {"name":"Adagas-de-Soco de Aço","min":299,"max":359,"cat":"Adagas-de-Soco","era":2,"ingredients":[{"qty":30,"item":"Barra de Aço"},{"qty":5,"item":"Galho"},{"qty":15,"item":"Couro"}]},
  {"name":"Adagas-de-Soco de Aço Reforçado","min":389,"max":466,"cat":"Adagas-de-Soco","era":3,"ingredients":[{"qty":30,"item":"Barra de Aço Reforçado"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Steel Claw","min":170,"max":204,"cat":"Adagas-de-Soco","era":2,"ingredients":[{"qty":20,"item":"Barra de Aço"},{"qty":5,"item":"Galho"}]},
  {"name":"Hardened Steel Katar","min":263,"max":316,"cat":"Adagas-de-Soco","era":3,"ingredients":[{"qty":20,"item":"Barra de Aço Enrijecida"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Tempered Katar","min":440,"max":528,"cat":"Adagas-de-Soco","era":4,"ingredients":[{"qty":20,"item":"Barra de Aço Enrijecida"},{"qty":4,"item":"Base Alquímica"},{"qty":1,"item":"Empunhadura de Arma"}]},
  {"name":"Epic Hyrkanian Sabre","min":1125,"max":1350,"cat":"Adagas-de-Soco","era":4,"ingredients":[{"qty":40,"item":"Barra de Metal das Estrelas"},{"qty":1,"item":"Empunhadura de Arma"}]},
  {"name":"Epic Serpent Charkam","min":1253,"max":1503,"cat":"Adagas-de-Soco","era":4,"ingredients":[{"qty":30,"item":"Barra de Metal das Estrelas"},{"qty":5,"item":"Osso de Dragão"},{"qty":1,"item":"Empunhadura de Arma"}]},
  {"name":"Star Metal Claw","min":630,"max":756,"cat":"Adagas-de-Soco","era":4,"ingredients":[{"qty":20,"item":"Barra de Metal das Estrelas"},{"qty":1,"item":"Empunhadura de Arma"}]},
  {"name":"Martelo de Guerra de Ferro","min":130,"max":156,"cat":"MARTELOS","era":1,"ingredients":[{"qty":45,"item":"Barra de Ferro"},{"qty":6,"item":"Galho"}]},
  {"name":"Martelo de Guerra de Aço","min":381,"max":457,"cat":"MARTELOS","era":2,"ingredients":[{"qty":45,"item":"Barra de Aço"},{"qty":8,"item":"Galho"}]},
  {"name":"Martelo de Guerra Arcaico","min":397,"max":476,"cat":"MARTELOS","era":2,"ingredients":[{"qty":45,"item":"Barra de Aço"},{"qty":6,"item":"Madeira Moldada"}]},
  {"name":"Martelo de Aço Reforçado","min":577,"max":692,"cat":"MARTELOS","era":3,"ingredients":[{"qty":45,"item":"Barra de Aço Enrijecida"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Martelo de Metal das Estrelas","min":878,"max":1053,"cat":"MARTELOS","era":4,"ingredients":[{"qty":30,"item":"Barra de Metal das Estrelas"},{"qty":1,"item":"Empunhadura de Arma"}]},
  {"name":"Martelo de Obsidiana","min":3527,"max":4232,"cat":"MARTELOS","era":5,"ingredients":[{"qty":30,"item":"Compósito de Obsidiana"},{"qty":1,"item":"Empunhadura de Arma"},{"qty":1,"item":"Reforço de Aço"}]},
  {"name":"Azagaia Arredondada","min":14,"max":17,"cat":"AZAGAIAS","era":1,"ingredients":[{"qty":5,"item":"Galho"},{"qty":3,"item":"Barra de Ferro"}]},
  {"name":"Azagaia Balanceada de Ferro","min":14,"max":17,"cat":"AZAGAIAS","era":1,"ingredients":[{"qty":5,"item":"Galho"},{"qty":3,"item":"Barra de Ferro"}]},
  {"name":"Azagaia de Aço","min":27,"max":32,"cat":"AZAGAIAS","era":2,"ingredients":[{"qty":5,"item":"Galho"},{"qty":3,"item":"Barra de Aço"}]},
  {"name":"Azagaia Antiga","min":37,"max":45,"cat":"AZAGAIAS","era":2,"ingredients":[{"qty":4,"item":"Madeira Moldada"},{"qty":3,"item":"Barra de Aço"}]},
  {"name":"Azagaia de Aço Reforçado","min":67,"max":81,"cat":"AZAGAIAS","era":3,"ingredients":[{"qty":1,"item":"Madeira Resinada"},{"qty":5,"item":"Barra de Aço Enrijecida"}]},
  {"name":"Azagaia de Obsidiana","min":409,"max":491,"cat":"AZAGAIAS","era":5,"ingredients":[{"qty":4,"item":"Madeira Moldada"},{"qty":3,"item":"Compósito de Obsidiana"},{"qty":1,"item":"Reforço de Aço"}]},
  {"name":"Iron Dory","min":17,"max":20,"cat":"DORY","era":1,"ingredients":[{"qty":5,"item":"Galho"},{"qty":20,"item":"Barra de Ferro"}]},
  {"name":"Steel Dory","min":170,"max":204,"cat":"DORY","era":2,"ingredients":[{"qty":5,"item":"Galho"},{"qty":20,"item":"Barra de Aço"}]},
  {"name":"Hardened Steel Dory","min":266,"max":319,"cat":"DORY","era":3,"ingredients":[{"qty":5,"item":"Madeira Moldada"},{"qty":20,"item":"Barra de Aço Enrijecida"}]},
  {"name":"Star Metal Dory","min":1553,"max":1863,"cat":"DORY","era":4,"ingredients":[{"qty":1,"item":"Espada de Metal das Estrelas"},{"qty":1,"item":"Empunhadura de Arma"}]},
  {"name":"Kit de Reparo de Armas Simples","min":5,"max":9,"cat":"KIT DE REPARO","era":1,"ingredients":[{"qty":30,"item":"Pedras"}]},
  {"name":"Kit de Reparo de Armas","min":17,"max":21,"cat":"KIT DE REPARO","era":1,"ingredients":[{"qty":23,"item":"Barra de Ferro"}]},
  {"name":"Kit de Reparo de Armas Avançado","min":194,"max":232,"cat":"KIT DE REPARO","era":2,"ingredients":[{"qty":23,"item":"Barra de Aço"}]},
  {"name":"Kit de Reparo de Armas Mestre","min":289,"max":347,"cat":"KIT DE REPARO","era":3,"ingredients":[{"qty":23,"item":"Barra de Aço Enrijecida"}]},
  {"name":"Kit de Reparo de Armas Lendário","min":516,"max":619,"cat":"KIT DE REPARO","era":3,"ingredients":[{"qty":1,"item":"Kit de Reparo de Armas Mestre"},{"qty":5,"item":"Base Alquímica"},{"qty":5,"item":"Óleo"}]},
  {"name":"3x Euphoric Weapon Repair Kit","min":1271,"max":1526,"cat":"KIT DE REPARO","era":"X","ingredients":[{"qty":9,"item":"Chromium Metal Bar"},{"qty":5,"item":"Crescent Steel Bar"}]},
  {"name":"Venerable Weapon Repair Kit","min":2519,"max":3023,"cat":"KIT DE REPARO","era":"X","ingredients":[{"qty":3,"item":"Eveirium Metal Bar"},{"qty":15,"item":"Bronze Bar"}]},
  {"name":"Mythical Weapon Repair Kit","min":0,"max":0,"cat":"KIT DE REPARO","era":"X","ingredients":[{"qty":3,"item":"Titanium Alloy"},{"qty":15,"item":"Mystical Dust"}]},
  {"name":"Heirloom Weapon Repair Kit","min":6807,"max":8168,"cat":"KIT DE REPARO","era":"X","ingredients":[{"qty":2,"item":"Teran Steel Bar"},{"qty":1,"item":"Trucioum Iron Bar"},{"qty":15,"item":"Ectoplasm"}]},
  {"name":"Apetrecho Arredondado Simples de Arma","min":28,"max":33,"cat":"KIT ARREDONDADO","era":1,"ingredients":[{"qty":10,"item":"Barra de Ferro"}]},
  {"name":"Apetrecho Arredondado de Arma","min":84,"max":101,"cat":"KIT ARREDONDADO","era":2,"ingredients":[{"qty":10,"item":"Barra de Aço"}]},
  {"name":"Apetrecho Arredondado Avançado de Arma","min":126,"max":151,"cat":"KIT ARREDONDADO","era":3,"ingredients":[{"qty":10,"item":"Barra de Aço Enrijecida"}]},
  {"name":"Kit de Reforço Simples de Arma","min":28,"max":33,"cat":"KIT DE REFORÇO","era":1,"ingredients":[{"qty":10,"item":"Barra de Ferro"}]},
  {"name":"Kit de Reforço","min":84,"max":101,"cat":"KIT DE REFORÇO","era":2,"ingredients":[{"qty":10,"item":"Barra de Aço"}]},
  {"name":"Kit de Reforço Avançado","min":126,"max":151,"cat":"KIT DE REFORÇO","era":3,"ingredients":[{"qty":10,"item":"Barra de Aço Enrijecida"}]},
  {"name":"Kit de Reforço de Qualidade Superior","min":258,"max":310,"cat":"KIT DE REFORÇO","era":4,"ingredients":[{"qty":8,"item":"Barra de Metal das Estrelas"},{"qty":20,"item":"Óleo"}]},
  {"name":"Kit Simples de Dano","min":83,"max":99,"cat":"KIT DE DANO","era":1,"ingredients":[{"qty":10,"item":"Barra de Ferro"},{"qty":5,"item":"Óleo"}]},
  {"name":"Kit de Dano de Arma","min":114,"max":137,"cat":"KIT DE DANO","era":2,"ingredients":[{"qty":10,"item":"Barra de Aço"},{"qty":10,"item":"Óleo"}]},
  {"name":"Kit Avançado de Dano","min":171,"max":205,"cat":"KIT DE DANO","era":3,"ingredients":[{"qty":10,"item":"Barra de Aço Enrijecida"},{"qty":15,"item":"Óleo"}]},
  {"name":"Apetrecho de Arma de Qualidade Superior","min":258,"max":310,"cat":"KIT DE DANO","era":4,"ingredients":[{"qty":8,"item":"Barra de Metal das Estrelas"},{"qty":20,"item":"Óleo"}]},
  {"name":"Kit de Melhoria Simples","min":28,"max":33,"cat":"KIT DE MELHORIA","era":1,"ingredients":[{"qty":10,"item":"Barra de Ferro"}]},
  {"name":"Kit de Melhoria","min":84,"max":101,"cat":"KIT DE MELHORIA","era":2,"ingredients":[{"qty":10,"item":"Barra de Aço"}]},
  {"name":"Kit de Melhoria Avançado","min":126,"max":151,"cat":"KIT DE MELHORIA","era":3,"ingredients":[{"qty":10,"item":"Barra de Aço Enrijecida"}]},
  {"name":"Apetrecho para Arma Esgrimista","min":258,"max":310,"cat":"KIT DE MELHORIA","era":4,"ingredients":[{"qty":8,"item":"Barra de Metal das Estrelas"},{"qty":20,"item":"Óleo"}]},
  {"name":"Apetrecho Farpado de Arma","min":126,"max":151,"cat":"KIT DE PERFURAÇÃO","era":3,"ingredients":[{"qty":10,"item":"Barra de Aço Enrijecida"}]},
  {"name":"Small Mailbox","min":138,"max":165,"cat":"GAIOLAS","era":1,"ingredients":[{"qty":10,"item":"Barra de Ferro"},{"qty":10,"item":"Madeira Moldada"}]},
  {"name":"Small Wall Mailbox","min":138,"max":165,"cat":"GAIOLAS","era":1,"ingredients":[{"qty":10,"item":"Barra de Ferro"},{"qty":10,"item":"Madeira Moldada"}]},
  {"name":"Small Bird Coop (Cage)","min":55,"max":66,"cat":"GAIOLAS","era":1,"ingredients":[{"qty":20,"item":"Barra de Ferro"}]},
  {"name":"Small Bird Coop (Box)","min":138,"max":165,"cat":"GAIOLAS","era":1,"ingredients":[{"qty":10,"item":"Barra de Ferro"},{"qty":10,"item":"Madeira Moldada"}]},
  {"name":"Small Bird Coop (Wall Cage) - 1 pássaro","min":165,"max":198,"cat":"GAIOLAS","era":1,"ingredients":[{"qty":20,"item":"Barra de Ferro"},{"qty":10,"item":"Madeira Moldada"}]},
  {"name":"Medium Bird Coop - 5 pássaros","min":275,"max":330,"cat":"GAIOLAS","era":1,"ingredients":[{"qty":20,"item":"Barra de Ferro"},{"qty":20,"item":"Madeira Moldada"}]},
  {"name":"Large Bird Coop - 1 pássaro","min":275,"max":330,"cat":"GAIOLAS","era":1,"ingredients":[{"qty":20,"item":"Barra de Ferro"},{"qty":20,"item":"Madeira Moldada"}]},
  {"name":"Medium Bird Coop - 12 pássaros","min":275,"max":330,"cat":"GAIOLAS","era":1,"ingredients":[{"qty":20,"item":"Barra de Ferro"},{"qty":20,"item":"Madeira Moldada"}]},
  {"name":"Adagas Imbuídas de Veneno","min":1778,"max":2133,"cat":"ARMAS ENVENENADAS","era":4,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":30,"item":"Barra de Metal das Estrelas"},{"qty":1,"item":"Glândula Biliar de Fera das Areias"}]},
  {"name":"Espada Imbuída de Veneno","min":1778,"max":2133,"cat":"ARMAS ENVENENADAS","era":4,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":30,"item":"Barra de Metal das Estrelas"},{"qty":1,"item":"Glândula Biliar de Fera das Areias"}]},
  {"name":"Espada de Duas Mãos Imbuída de Veneno","min":1778,"max":2133,"cat":"ARMAS ENVENENADAS","era":4,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":30,"item":"Barra de Metal das Estrelas"},{"qty":1,"item":"Glândula Biliar de Fera das Areias"}]},
  {"name":"Machado de Guerra Imbuída de Veneno","min":1778,"max":2133,"cat":"ARMAS ENVENENADAS","era":4,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":30,"item":"Barra de Metal das Estrelas"},{"qty":1,"item":"Glândula Biliar de Fera das Areias"}]},
  {"name":"Lança Imbuída de Veneno","min":1778,"max":2133,"cat":"ARMAS ENVENENADAS","era":4,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":30,"item":"Barra de Metal das Estrelas"},{"qty":1,"item":"Glândula Biliar de Fera das Areias"}]},
  {"name":"Dawn's Edge","min":58,"max":69,"cat":"AGE OF CALAMITOUS","era":1,"ingredients":[{"qty":7,"item":"Reforço de Ferro"}]},
  {"name":"Improved Dawn's Edge","min":856,"max":1027,"cat":"AGE OF CALAMITOUS","era":2,"ingredients":[{"qty":10,"item":"Bronze Bar"},{"qty":12,"item":"Reforço de Ferro"},{"qty":1,"item":"Dawn's Edge"}]},
  {"name":"Refined Dawn's Edge","min":4516,"max":5420,"cat":"AGE OF CALAMITOUS","era":3,"ingredients":[{"qty":5,"item":"Chromium Metal Bar"},{"qty":22,"item":"Chromium Reinforcement"},{"qty":15,"item":"Barra de Aço Enrijecida"}]},
  {"name":"Enchanced Dawn's Edge","min":28431,"max":34118,"cat":"AGE OF CALAMITOUS","era":6,"ingredients":[{"qty":1,"item":"Skyan Metal Bar"},{"qty":25,"item":"Chromium Metal Bar"},{"qty":1,"item":"Refined Dawn's Edge"}]},
  {"name":"Edge of Elydarh","min":83,"max":99,"cat":"AGE OF CALAMITOUS","era":1,"ingredients":[{"qty":10,"item":"Reforço de Ferro"}]},
  {"name":"Improved Edge of Elydarh","min":893,"max":1072,"cat":"AGE OF CALAMITOUS","era":2,"ingredients":[{"qty":10,"item":"Bronze Bar"},{"qty":12,"item":"Reforço de Ferro"},{"qty":1,"item":"Edge of Elydarh"}]},
  {"name":"Refined Edge of Elydarh","min":4572,"max":5486,"cat":"AGE OF CALAMITOUS","era":3,"ingredients":[{"qty":5,"item":"Chromium Metal Bar"},{"qty":22,"item":"Chromium Reinforcement"},{"qty":15,"item":"Barra de Aço Enrijecida"}]},
  {"name":"Enchanced Edge of Elydarh","min":28515,"max":34218,"cat":"AGE OF CALAMITOUS","era":6,"ingredients":[{"qty":1,"item":"Skyan Metal Bar"},{"qty":25,"item":"Chromium Metal Bar"},{"qty":1,"item":"Refined Edge of Elydarh"}]},
  {"name":"Perfected Edge of Elydarh","min":87907,"max":105489,"cat":"AGE OF CALAMITOUS","era":7,"ingredients":[{"qty":1,"item":"Kronyxium Steel Bar"},{"qty":50,"item":"Chromium Metal Bar"},{"qty":2,"item":"Amethyst"}]},
  {"name":"Cleaver of Brutality","min":127,"max":152,"cat":"AGE OF CALAMITOUS","era":1,"ingredients":[{"qty":10,"item":"Reforço de Ferro"},{"qty":4,"item":"Madeira Moldada"}]},
  {"name":"Improved Cleaver of Brutality","min":959,"max":1151,"cat":"AGE OF CALAMITOUS","era":2,"ingredients":[{"qty":10,"item":"Bronze Bar"},{"qty":12,"item":"Reforço de Ferro"},{"qty":1,"item":"Cleaver of Brutality"}]},
  {"name":"Refined Cleaver of Brutality","min":4671,"max":5605,"cat":"AGE OF CALAMITOUS","era":3,"ingredients":[{"qty":5,"item":"Chromium Metal Bar"},{"qty":22,"item":"Chromium Reinforcement"},{"qty":15,"item":"Barra de Aço Enrijecida"}]},
  {"name":"Enchanced Cleaver of Brutality","min":28663,"max":34396,"cat":"AGE OF CALAMITOUS","era":6,"ingredients":[{"qty":1,"item":"Skyan Metal Bar"},{"qty":25,"item":"Chromium Metal Bar"},{"qty":1,"item":"Refined Cleaver of Brutality"}]},
  {"name":"Shadow Dagger","min":58,"max":69,"cat":"AGE OF CALAMITOUS","era":1,"ingredients":[{"qty":7,"item":"Reforço de Ferro"}]},
  {"name":"Improved Shadow Dagger","min":842,"max":1010,"cat":"AGE OF CALAMITOUS","era":2,"ingredients":[{"qty":10,"item":"Bronze Bar"},{"qty":17,"item":"Uncut Ruby"},{"qty":1,"item":"Shadow Dagger"}]},
  {"name":"Refined Shadow Dagger","min":4331,"max":5198,"cat":"AGE OF CALAMITOUS","era":3,"ingredients":[{"qty":5,"item":"Chromium Metal Bar"},{"qty":22,"item":"Chromium Reinforcment"},{"qty":5,"item":"Ruby Shard"}]},
  {"name":"Enchanced Shadow Dagger","min":28263,"max":33915,"cat":"AGE OF CALAMITOUS","era":6,"ingredients":[{"qty":1,"item":"Skyan Metal Bar"},{"qty":25,"item":"Chromium Metal Bar"},{"qty":5,"item":"Ruby"}]},
  {"name":"Reapers of Righteousness","min":58,"max":69,"cat":"AGE OF CALAMITOUS","era":1,"ingredients":[{"qty":7,"item":"Reforço de Ferro"}]},
  {"name":"Improved Reapers of Righteousness","min":842,"max":1010,"cat":"AGE OF CALAMITOUS","era":2,"ingredients":[{"qty":10,"item":"Bronze Bar"},{"qty":17,"item":"Uncut Ruby"},{"qty":1,"item":"Reapers of Righteousness"}]},
  {"name":"Refined Reapers of Righteousness","min":4331,"max":5198,"cat":"AGE OF CALAMITOUS","era":3,"ingredients":[{"qty":5,"item":"Chromium Metal Bar"},{"qty":22,"item":"Chromium Reinforcment"},{"qty":5,"item":"Ruby Shard"}]},
  {"name":"Enchanced Reapers of Righteousness","min":28263,"max":33915,"cat":"AGE OF CALAMITOUS","era":6,"ingredients":[{"qty":1,"item":"Skyan Metal Bar"},{"qty":25,"item":"Chromium Metal Bar"},{"qty":5,"item":"Ruby"}]},
  {"name":"Nethersbane","min":58,"max":69,"cat":"AGE OF CALAMITOUS","era":1,"ingredients":[{"qty":7,"item":"Reforço de Ferro"}]},
  {"name":"Improved Nethersbane","min":519,"max":623,"cat":"AGE OF CALAMITOUS","era":2,"ingredients":[{"qty":15,"item":"Bitter Crinilla Dust"},{"qty":2,"item":"Sapphire Shard"},{"qty":1,"item":"Mystical Potion"}]},
  {"name":"Refined Nethersbane","min":1234,"max":1480,"cat":"AGE OF CALAMITOUS","era":3,"ingredients":[{"qty":5,"item":"Chromium Metal Bar"},{"qty":5,"item":"Sapphire"},{"qty":1,"item":"Improved Nethersbane"}]},
  {"name":"Enchanced Nethersbane","min":23507,"max":28209,"cat":"AGE OF CALAMITOUS","era":6,"ingredients":[{"qty":1,"item":"Skyan Metal Bar"},{"qty":25,"item":"Chromium Metal Bar"},{"qty":1,"item":"Refined Nethersbane"}]},
  {"name":"Knight Blade","min":124,"max":149,"cat":"AGE OF CALAMITOUS","era":1,"ingredients":[{"qty":15,"item":"Reforço de Ferro"}]},
  {"name":"Improved Knight Blade","min":755,"max":906,"cat":"AGE OF CALAMITOUS","era":2,"ingredients":[{"qty":10,"item":"Bronze Bar"},{"qty":17,"item":"Uncut Ruby"},{"qty":1,"item":"Knight Blade"}]},
  {"name":"Refined Knight Blade","min":3069,"max":3682,"cat":"AGE OF CALAMITOUS","era":3,"ingredients":[{"qty":5,"item":"Chromium Metal Bar"},{"qty":22,"item":"Chromium Reinforcement"},{"qty":5,"item":"Ruby Shard"}]},
  {"name":"Enchanced Knight Blade","min":21766,"max":26119,"cat":"AGE OF CALAMITOUS","era":6,"ingredients":[{"qty":1,"item":"Skyan Metal Bar"},{"qty":25,"item":"Chromium Metal Bar"},{"qty":5,"item":"Ruby"}]},
  {"name":"Skull Torch","min":38,"max":45,"cat":"AGE OF CALAMITOUS","era":2,"ingredients":[{"qty":15,"item":"Osso"},{"qty":1,"item":"Crânio Gasto"}]},
  {"name":"Frost Fire Torch","min":1048,"max":1258,"cat":"AGE OF CALAMITOUS","era":3,"ingredients":[{"qty":15,"item":"Chromium Metal Bar"},{"qty":2,"item":"Tijolo Endurecido"}]},
  {"name":"Metal Torch","min":1040,"max":1247,"cat":"AGE OF CALAMITOUS","era":3,"ingredients":[{"qty":15,"item":"Chromium Metal Bar"}]},
  {"name":"Spirit Fire Torch","min":389,"max":467,"cat":"AGE OF CALAMITOUS","era":3,"ingredients":[{"qty":3,"item":"Chromium Reinforcement"},{"qty":2,"item":"Mystical Dust"}]},
  {"name":"Armas Eveirium","min":9746,"max":11696,"cat":"AoC ARMAS E FERRAMENTAS","era":5,"ingredients":[{"qty":12,"item":"Eveirium Metal Bar"},{"qty":24,"item":"Bronze Bar"},{"qty":4,"item":"Sarin Steel Bar"}]},
  {"name":"Ferramentas Eveirium","min":1826,"max":2191,"cat":"AoC ARMAS E FERRAMENTAS","era":5,"ingredients":[{"qty":3,"item":"Eveirium Metal Bar"},{"qty":5,"item":"Chromium Metal Bar"},{"qty":3,"item":"Madeira Moldada"}]},
  {"name":"Armas Crescent","min":1527,"max":1833,"cat":"AoC ARMAS E FERRAMENTAS","era":5,"ingredients":[{"qty":7,"item":"Crescent Steel Bar"},{"qty":15,"item":"Blue Bell Dust"},{"qty":2,"item":"Teran Steel Bar"}]},
  {"name":"Ferramentas Crescent","min":1503,"max":1803,"cat":"AoC ARMAS E FERRAMENTAS","era":5,"ingredients":[{"qty":3,"item":"Crescent Steel Bar"},{"qty":15,"item":"Chromium Metal Bar"},{"qty":3,"item":"Madeira Moldada"}]},
  {"name":"Armas Verian","min":47353,"max":56823,"cat":"AoC ARMAS E FERRAMENTAS","era":6,"ingredients":[{"qty":13,"item":"Verian Metal Bar"},{"qty":3,"item":"Trucioum Iron Bar"},{"qty":5,"item":"Madeira Moldada"}]},
  {"name":"Ferramentas Verian","min":39619,"max":47542,"cat":"AoC ARMAS E FERRAMENTAS","era":6,"ingredients":[{"qty":8,"item":"Verian Metal Bar"},{"qty":4,"item":"Trucioum Iron Bar"},{"qty":3,"item":"Madeira Moldada"}]},
  {"name":"Armas Kronyxium","min":45371,"max":54446,"cat":"AoC ARMAS E FERRAMENTAS","era":6,"ingredients":[{"qty":1,"item":"Kronyxium Steel Bar"},{"qty":1,"item":"Diamond"},{"qty":3,"item":"Sarin Steel Bar"}]},
  {"name":"Ferramentas Kronyxium","min":47507,"max":57009,"cat":"AoC ARMAS E FERRAMENTAS","era":6,"ingredients":[{"qty":1,"item":"Kronyxium Steel Bar"},{"qty":3,"item":"Sarin Steel Bar"},{"qty":3,"item":"Madeira Moldada"}]},
  {"name":"Picareta de Gelo Preto","min":836,"max":1672,"cat":"FORJA DE GELO","era":3,"ingredients":[{"qty":1,"item":"Picareta de Aço Reforçado"},{"qty":20,"item":"Gelo Preto"}]},
  {"name":"Azagaia de Gelo Preto","min":135,"max":270,"cat":"FORJA DE GELO","era":3,"ingredients":[{"qty":1,"item":"Azagaia de Aço Reforçado"},{"qty":1,"item":"Gelo Preto"}]},
  {"name":"Adagas de Gelo Preto","min":836,"max":1672,"cat":"FORJA DE GELO","era":3,"ingredients":[{"qty":1,"item":"Adagas de Aço Reforçado"},{"qty":20,"item":"Gelo Preto"}]},
  {"name":"Espadas Duplas de Gelo Preto","min":836,"max":1672,"cat":"FORJA DE GELO","era":3,"ingredients":[{"qty":1,"item":"Espada de Aço Enrijecido"},{"qty":20,"item":"Gelo Preto"}]},
  {"name":"Lança de Gelo Preto","min":1203,"max":2406,"cat":"FORJA DE GELO","era":3,"ingredients":[{"qty":1,"item":"Lança de Aço Enrijecido"},{"qty":20,"item":"Gelo Preto"}]},
  {"name":"Machado de Guerra de Gelo Preto","min":1203,"max":2406,"cat":"FORJA DE GELO","era":3,"ingredients":[{"qty":1,"item":"Martelo de Aço Reforçado"},{"qty":20,"item":"Gelo Preto"}]},
  {"name":"Machados Duplos de Gelo Preto","min":1281,"max":2562,"cat":"FORJA DE GELO","era":3,"ingredients":[{"qty":1,"item":"Martelo de Aço Reforçado"},{"qty":40,"item":"Gelo Preto"}]},
  {"name":"Espada Grande de Gelo Preto","min":836,"max":1672,"cat":"FORJA DE GELO","era":3,"ingredients":[{"qty":1,"item":"Espada de Aço Enrijecido"},{"qty":20,"item":"Gelo Preto"}]},
  {"name":"Espada Larga de Gelo Preto","min":836,"max":1672,"cat":"FORJA DE GELO","era":3,"ingredients":[{"qty":1,"item":"Espada de Aço Enrijecido"},{"qty":20,"item":"Gelo Preto"}]},
  {"name":"Espada Longa de Gelo Preto","min":836,"max":1672,"cat":"FORJA DE GELO","era":3,"ingredients":[{"qty":1,"item":"Espada de aço Enrijecido"},{"qty":20,"item":"Gelo Preto"}]},
  {"name":"Machado de Arremesso de Gelo Preto","min":83,"max":166,"cat":"FORJA DE GELO","era":3,"ingredients":[{"qty":1,"item":"Machado de Arremesso de Aço Reforçado"},{"qty":1,"item":"Gelo Preto"}]},
  {"name":"Telith's Pain","min":2540,"max":3048,"cat":"ARMAS DE DUNGEON","era":4,"ingredients":[{"qty":30,"item":"Barra de Aço Enrijecida"},{"qty":1,"item":"Empunhadura de Arma"},{"qty":1,"item":"Gelo Preto"}]},
  {"name":"Telith's Punishment","min":2800,"max":3360,"cat":"ARMAS DE DUNGEON","era":4,"ingredients":[{"qty":40,"item":"Barra de Aço Enrijecida"},{"qty":2,"item":"Empunhadura de Arma"},{"qty":1,"item":"Gelo Preto"}]},
  {"name":"Deathbringer Axe","min":2294,"max":2753,"cat":"ARMAS DE DUNGEON","era":4,"ingredients":[{"qty":20,"item":"Barra de Aço Enrijecida"},{"qty":5,"item":"Madeira Moldada"},{"qty":1,"item":"Gelo Preto"}]},
  {"name":"Lamento de Telith","min":2481,"max":2977,"cat":"ARMAS DE DUNGEON","era":4,"ingredients":[{"qty":22,"item":"Barra de Aço Enrijecida"},{"qty":15,"item":"Gelo Preto"},{"qty":1,"item":"Coração do Fratricida"}]},
  {"name":"Sofrimento de Telith","min":2815,"max":3378,"cat":"ARMAS DE DUNGEON","era":4,"ingredients":[{"qty":45,"item":"Barra de Aço Enrijecida"},{"qty":30,"item":"Gelo Preto"},{"qty":1,"item":"Coração do Fratricida"}]},
  {"name":"Espadas Duplas Lamento de Telith","min":2597,"max":3116,"cat":"ARMAS DE DUNGEON","era":4,"ingredients":[{"qty":30,"item":"Barra de Aço Enrijecida"},{"qty":20,"item":"Gelo Preto"},{"qty":1,"item":"Coração do Fratricida"}]},
  {"name":"Alabarda Regicida","min":657,"max":788,"cat":"ARMAS DE DUNGEON","era":3,"ingredients":[{"qty":45,"item":"Barra de Aço Enrijecida"},{"qty":8,"item":"Madeira Moldada"},{"qty":15,"item":"Couro Reforçado"}]},
  {"name":"Adagas Regicidas","min":456,"max":547,"cat":"ARMAS DE DUNGEON","era":3,"ingredients":[{"qty":30,"item":"Barra de Aço Enrijecida"},{"qty":4,"item":"Madeira Moldada"},{"qty":15,"item":"Couro Reforçado"}]},
  {"name":"Espada Abismal","min":167,"max":200,"cat":"ARMAS DE DUNGEON","era":1,"ingredients":[{"qty":5,"item":"Galho"},{"qty":30,"item":"Barra de Ferro"},{"qty":15,"item":"Couro Reforçado"}]},
  {"name":"Adagas Abismais","min":124,"max":149,"cat":"ARMAS DE DUNGEON","era":1,"ingredients":[{"qty":5,"item":"Galho"},{"qty":15,"item":"Barra de Ferro"},{"qty":8,"item":"Couro Reforçado"}]},
  {"name":"Lâmina Coração-Sombrio","min":3634,"max":4360,"cat":"ARMAS DE DUNGEON","era":5,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":60,"item":"Barra de Metal das Estrelas"},{"qty":45,"item":"Compósito de Obsidiana"}]},
  {"name":"Martelo Coração-Sombrio","min":3634,"max":4360,"cat":"ARMAS DE DUNGEON","era":5,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":60,"item":"Barra de Metal das Estrelas"},{"qty":45,"item":"Compósito de Obsidiana"}]},
  {"name":"Lemurian Greataxe","min":389,"max":466,"cat":"ARMAS DE DUNGEON","era":3,"ingredients":[{"qty":4,"item":"Madeira Moldada"},{"qty":30,"item":"Barra de Aço Enrijecida"}]},
  {"name":"Lemurian War-axe","min":512,"max":614,"cat":"ARMAS DE DUNGEON","era":3,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":30,"item":"Barra de Aço Enrijecida"}]},
  {"name":"Espada Lemuriana","min":549,"max":659,"cat":"ARMAS DE DUNGEON","era":3,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":33,"item":"Barra de Aço Enrijecida"}]},
  {"name":"Pique Lemuriano","min":549,"max":659,"cat":"ARMAS DE DUNGEON","era":3,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":33,"item":"Barra de Aço Enrijecida"}]},
  {"name":"Lemurian Dual Wakizashi","min":647,"max":776,"cat":"ARMAS DE DUNGEON","era":3,"ingredients":[{"qty":2,"item":"Empunhadura de Arma"},{"qty":30,"item":"Barra de Aço Enrijecida"}]},
  {"name":"Lemurian Katana","min":512,"max":614,"cat":"ARMAS DE DUNGEON","era":3,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":30,"item":"Barra de Aço Enrijecida"}]},
  {"name":"Lemurian Wakizashi","min":512,"max":614,"cat":"ARMAS DE DUNGEON","era":3,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":30,"item":"Barra de Aço Enrijecida"}]},
  {"name":"Espada Lemuriana Antiga","min":2079,"max":2495,"cat":"ARMAS DE DUNGEON","era":3,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":5,"item":"Escama de Dagon"},{"qty":5,"item":"Base Alquímica"}]},
  {"name":"Espada Lemuriana","min":700,"max":840,"cat":"ARMAS DE DUNGEON","era":3,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":45,"item":"Barra de Aço Enrijecida"}]},
  {"name":"Pique Lemuriano","min":1249,"max":1499,"cat":"ARMAS DE DUNGEON","era":3,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":45,"item":"Barra de Aço Enrijecida"}]},
  {"name":"Espadas Duplas Lemuriana Antiga","min":2079,"max":2495,"cat":"ARMAS DE DUNGEON","era":3,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":5,"item":"Escama de Dagon"},{"qty":5,"item":"Base Alquímica"}]},
  {"name":"Tridente Lemuriano Antigo","min":2079,"max":2495,"cat":"ARMAS DE DUNGEON","era":3,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":5,"item":"Escama de Dagon"},{"qty":5,"item":"Base Alquímica"}]},
  {"name":"Machado Lemuriano Antigo","min":1076,"max":1291,"cat":"ARMAS DE DUNGEON","era":4,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":38,"item":"Barra de Metal das Estrelas"}]},
  {"name":"Machados Duplos Lemuriano Antigo","min":1076,"max":1291,"cat":"ARMAS DE DUNGEON","era":4,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":38,"item":"Barra de Metal das Estrelas"}]},
  {"name":"Adagas de Dagon","min":2378,"max":2853,"cat":"ARMAS DE DUNGEON","era":4,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":30,"item":"Barra de Metal das Estrelas"},{"qty":5,"item":"Escama de Dagon"}]},
  {"name":"Adagas dos Homens-Serpente","min":400,"max":480,"cat":"Homens-Serpente","era":2,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":30,"item":"Barra de Ferro"},{"qty":10,"item":"Peles Reptilianas"}]},
  {"name":"Azagaia dos Homens-Serpente","min":17,"max":21,"cat":"Homens-Serpente","era":2,"ingredients":[{"qty":4,"item":"Madeira Moldada"},{"qty":3,"item":"Barra de Ferro"},{"qty":2,"item":"Peles Reptilianas"}]},
  {"name":"Machados Duplos dos Homens-Serpente","min":308,"max":369,"cat":"Homens-Serpente","era":2,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":30,"item":"Barra de Ferro"},{"qty":10,"item":"Peles Reptilianas"}]},
  {"name":"Espada dos Homens-Serpente","min":308,"max":369,"cat":"Homens-Serpente","era":2,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":30,"item":"Barra de Ferro"},{"qty":10,"item":"Peles Reptilianas"}]},
  {"name":"Lança de Guerra dos Homens-Serpente","min":308,"max":369,"cat":"Homens-Serpente","era":2,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":30,"item":"Barra de Ferro"},{"qty":10,"item":"Peles Reptilianas"}]},
  {"name":"Martelo de Guerra dos Homens-Serpente","min":319,"max":383,"cat":"Homens-Serpente","era":2,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":45,"item":"Barra de Ferro"},{"qty":10,"item":"Peles Reptilianas"}]},
  {"name":"Maça dos Homens-Serpente","min":308,"max":369,"cat":"Homens-Serpente","era":2,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":30,"item":"Barra de Ferro"},{"qty":10,"item":"Peles Reptilianas"}]},
  {"name":"Espadas Duplas dos Homens-Serpente","min":308,"max":369,"cat":"Homens-Serpente","era":2,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":30,"item":"Barra de Ferro"},{"qty":10,"item":"Peles Reptilianas"}]},
  {"name":"Serpent-man Throwing Club","min":3,"max":4,"cat":"Homens-Serpente","era":2,"ingredients":[{"qty":1,"item":"Madeira Resinada"},{"qty":4,"item":"Barra de Ferro"}]},
  {"name":"Serpent-man Throwing Knife","min":3,"max":3,"cat":"Homens-Serpente","era":2,"ingredients":[{"qty":1,"item":"Madeira Resinada"},{"qty":3,"item":"Barra de Ferro"}]},
  {"name":"Machado de Arremesso dos Homens-Serpente","min":136,"max":163,"cat":"Homens-Serpente","era":2,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":1,"item":"Barra de Ferro"}]},
  {"name":"Machado de Guerra dos Homens-Serpente","min":308,"max":369,"cat":"Homens-Serpente","era":2,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":30,"item":"Barra de Ferro"},{"qty":10,"item":"Peles Reptilianas"}]},
  {"name":"Adaga de Osso de Dragão","min":810,"max":972,"cat":"OSSOS DE DRAGÃO","era":4,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":1,"item":"Chifre de Dragão"},{"qty":5,"item":"Osso de Dragão"}]},
  {"name":"Azagaia de Osso de Dragão","min":76,"max":91,"cat":"OSSOS DE DRAGÃO","era":4,"ingredients":[{"qty":3,"item":"Galho"},{"qty":1,"item":"Osso de Dragão"}]},
  {"name":"Espadas Duplas de Osso de Dragão","min":1185,"max":1422,"cat":"OSSOS DE DRAGÃO","era":4,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":1,"item":"Chifre de Dragão"},{"qty":10,"item":"Osso de Dragão"}]},
  {"name":"Dragonbone Throwning Knife","min":225,"max":270,"cat":"OSSOS DE DRAGÃO","era":4,"ingredients":[{"qty":1,"item":"Galho"},{"qty":3,"item":"Osso de Dragão"}]},
  {"name":"Machados Duplos de Osso de Dragão","min":1185,"max":1422,"cat":"OSSOS DE DRAGÃO","era":4,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":1,"item":"Chifre de Dragão"},{"qty":10,"item":"Osso de Dragão"}]},
  {"name":"Espada de Duas Mãos de Osso de Dragão","min":1185,"max":1422,"cat":"OSSOS DE DRAGÃO","era":4,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":1,"item":"Chifre de Dragão"},{"qty":10,"item":"Osso de Dragão"}]},
  {"name":"Espada de Osso de Dragão","min":1185,"max":1422,"cat":"OSSOS DE DRAGÃO","era":4,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":1,"item":"Chifre de Dragão"},{"qty":10,"item":"Osso de Dragão"}]},
  {"name":"Lança de Osso de Dragão","min":751,"max":901,"cat":"OSSOS DE DRAGÃO","era":4,"ingredients":[{"qty":3,"item":"Galhos"},{"qty":10,"item":"Osso de Dragão"}]},
  {"name":"Machado de Arremesso","min":78,"max":94,"cat":"OSSOS DE DRAGÃO","era":4,"ingredients":[{"qty":1,"item":"Madeira Moldada"},{"qty":1,"item":"Osso de Dragão"}]},
  {"name":"Machado de Guerra de Osso de Dragão","min":1185,"max":1422,"cat":"OSSOS DE DRAGÃO","era":4,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":1,"item":"Chifre de Dragão"},{"qty":10,"item":"Osso de Dragão"}]},
  {"name":"Marreta de Osso de Dragão","min":1185,"max":1422,"cat":"OSSOS DE DRAGÃO","era":4,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":1,"item":"Chifre de Dragão"},{"qty":10,"item":"Osso de Dragão"}]},
  {"name":"Adagas Khari","min":3135,"max":3762,"cat":"ARMAS KHARI","era":4,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":20,"item":"Aço Khari"}]},
  {"name":"Espada Grande de Khari","min":3135,"max":3762,"cat":"ARMAS KHARI","era":4,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":20,"item":"Aço Khari"}]},
  {"name":"Machado de Guerra Khari","min":3135,"max":3762,"cat":"ARMAS KHARI","era":4,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":20,"item":"Aço Khari"}]},
  {"name":"Martelo Khari","min":3135,"max":3762,"cat":"ARMAS KHARI","era":4,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":20,"item":"Aço Khari"}]},
  {"name":"Pique Khari","min":3135,"max":3762,"cat":"ARMAS KHARI","era":4,"ingredients":[{"qty":1,"item":"Empunhadura de Arma"},{"qty":20,"item":"Aço Khari"}]},
  {"name":"Espadas de Treino","min":100,"max":120,"cat":"ARMAS CIDADE SEM NOME","era":1,"ingredients":[{"qty":5,"item":"Madeira"},{"qty":5,"item":"Madeira Resinada"}]},
  {"name":"Espadas Grande de Treino","min":100,"max":120,"cat":"ARMAS CIDADE SEM NOME","era":1,"ingredients":[{"qty":5,"item":"Madeira"},{"qty":5,"item":"Madeira Resinada"}]},
  {"name":"Perna Morta","min":825,"max":990,"cat":"ARMAS CIDADE SEM NOME","era":1,"ingredients":[{"qty":1,"item":"Fragmento do Poder"},{"qty":1,"item":"Perna Decepada"}]},
  {"name":"Perna de Mesa","min":705,"max":846,"cat":"ARMAS CIDADE SEM NOME","era":4,"ingredients":[{"qty":1,"item":"Fragmento do Poder"},{"qty":1,"item":"Empunhadura de Arma"},{"qty":20,"item":"Barra de Metal das Estrelas"}]},
  {"name":"Lâminas de Turbilhão","min":1324,"max":1589,"cat":"ARMAS CIDADE SEM NOME","era":4,"ingredients":[{"qty":1,"item":"Fragmento do Poder"},{"qty":1,"item":"Empunhadura de Arma"},{"qty":45,"item":"Barra de Metal das Estrelas"}]},
  {"name":"Caos e Malícia","min":1324,"max":1589,"cat":"ARMAS CIDADE SEM NOME","era":4,"ingredients":[{"qty":1,"item":"Fragmento do Poder"},{"qty":1,"item":"Empunhadura de Arma"},{"qty":45,"item":"Barra de Metal das Estrelas"}]},
  {"name":"Banquinho Reforçado","min":755,"max":905,"cat":"ARMAS CIDADE SEM NOME","era":4,"ingredients":[{"qty":1,"item":"Fragmento do Poder"},{"qty":1,"item":"Empunhadura de Arma"},{"qty":22,"item":"Barra de Metal das Estrelas"}]},
  {"name":"Espátula de Batalha","min":755,"max":905,"cat":"ARMAS CIDADE SEM NOME","era":4,"ingredients":[{"qty":1,"item":"Fragmento do Poder"},{"qty":1,"item":"Empunhadura de Arma"},{"qty":22,"item":"Barra de Metal das Estrelas"}]},
  {"name":"Vidraceiro","min":884,"max":1060,"cat":"ARMAS CIDADE SEM NOME","era":4,"ingredients":[{"qty":1,"item":"Fragmento do Poder"},{"qty":30,"item":"Barra de Metal das Estrelas"},{"qty":40,"item":"Vidro"}]}
];
