dataByProfession.minerador = [
  {"name":"Barra de Ferro","min":0.5,"max":1,"cat":"METAIS","era":1,"ingredients":[{"qty":2,"item":"Minério de Ferro"}]},
  {"name":"Barra de Aço","min":6,"max":6,"cat":"METAIS","era":2,"ingredients":[{"qty":5,"item":"Barra de Ferro"},{"qty":1,"item":"Fogaço"}]},
  {"name":"Barra de Prata","min":10,"max":15,"cat":"METAIS","era":2,"ingredients":[{"qty":3,"item":"Rocha Prateada"}]},
  {"name":"Barra de Ouro","min":15,"max":20,"cat":"METAIS","era":2,"ingredients":[{"qty":3,"item":"Rocha Dourada"}]},
  {"name":"Barra de Aço Enrijecida","min":8,"max":9,"cat":"METAIS","era":3,"ingredients":[{"qty":1,"item":"Barra de Aço"},{"qty":1,"item":"Gelo Preto"}]},
  {"name":"Barra de Metal das Estrelas","min":17,"max":18,"cat":"METAIS","era":4,"ingredients":[{"qty":2,"item":"Minério de Metal das Estrelas"},{"qty":1,"item":"Gelo Preto"},{"qty":1,"item":"Enxofre"}]},
  {"name":"Compósito de Obsidiana","min":26,"max":28,"cat":"METAIS","era":5,"ingredients":[{"qty":10,"item":"Obsidiana"},{"qty":1,"item":"Barra de Aço"}]},
  {"name":"Eveirium Metal Bar","min":312,"max":344,"cat":"METAIS","era":5,"ingredients":[{"qty":2,"item":"Chromium Metal Bar"},{"qty":1,"item":"Topaz"},{"qty":10,"item":"Eveirium"},{"qty":3,"item":"Rocha Dourada"}]},
  {"name":"Sarin Steel Bar","min":388,"max":427,"cat":"METAIS","era":5,"ingredients":[{"qty":10,"item":"Vanadium"},{"qty":13,"item":"Aluminium"},{"qty":3,"item":"Blood of the Devil Bear"},{"qty":9,"item":"Ruby Shard"}]},
  {"name":"Crescent Steel Bar","min":86,"max":95,"cat":"METAIS","era":5,"ingredients":[{"qty":4,"item":"Titanium"},{"qty":25,"item":"Quartz"},{"qty":1,"item":"Sapphire"},{"qty":8,"item":"Carbon"}]},
  {"name":"Teran Steel Bar","min":187,"max":205,"cat":"METAIS","era":5,"ingredients":[{"qty":6,"item":"Carbon"},{"qty":1,"item":"Amethyst Shard"},{"qty":12,"item":"Arsenic"},{"qty":18,"item":"Mystical Dust"}]},
  {"name":"Verian Metal Bar","min":1586,"max":1745,"cat":"METAIS","era":6,"ingredients":[{"qty":2,"item":"Vanadium"},{"qty":7,"item":"Fragment of Demise"},{"qty":12,"item":"Onyx"},{"qty":1,"item":"Emerald"}]},
  {"name":"Trucioum Iron Bar","min":3414,"max":3756,"cat":"METAIS","era":6,"ingredients":[{"qty":10,"item":"Emerald Shard"},{"qty":26,"item":"Aluminium"},{"qty":15,"item":"Fragment of Fury"},{"qty":60,"item":"Cinzas Cruas"}]},
  {"name":"Kronyxium Steel Bar","min":27577,"max":30334,"cat":"METAIS","era":6,"ingredients":[{"qty":15,"item":"Titanium Alloy"},{"qty":4,"item":"Onyx Composite"},{"qty":1,"item":"Diamond"},{"qty":2,"item":"Kronyxium Core"}]},
  {"name":"Carvão","min":0.5,"max":1,"cat":"SECUNDÁRIOS","era":1,"ingredients":[]},
  {"name":"Cristal","min":0.5,"max":1,"cat":"SECUNDÁRIOS","era":1,"ingredients":[]},
  {"name":"Sal","min":0.5,"max":1,"cat":"SECUNDÁRIOS","era":1,"ingredients":[]},
  {"name":"Tijolo","min":1,"max":1,"cat":"SECUNDÁRIOS","era":1,"ingredients":[{"qty":10,"item":"Pedra"}]},
  {"name":"Vidro","min":1,"max":1,"cat":"SECUNDÁRIOS","era":1,"ingredients":[{"qty":2,"item":"Cristal"}]},
  {"name":"Enxofre","min":1,"max":2,"cat":"SECUNDÁRIOS","era":2,"ingredients":[]},
  {"name":"Gelo","min":0.5,"max":1,"cat":"SECUNDÁRIOS","era":1,"ingredients":[]},
  {"name":"Tijolo Endurecido","min":3,"max":3,"cat":"SECUNDÁRIOS","era":2,"ingredients":[{"qty":1,"item":"Tijolo"},{"qty":1,"item":"Consolidador de Pedras"}]},
  {"name":"Cinzas Cruas","min":2,"max":4,"cat":"SECUNDÁRIOS","era":2,"ingredients":[]},
  {"name":"Gelo Preto","min":2,"max":4,"cat":"SECUNDÁRIOS","era":3,"ingredients":[]},
  {"name":"Unstable Substance","min":10,"max":20,"cat":"SECUNDÁRIOS","era":4,"ingredients":[]},
  {"name":"Cobblestone","min":0.2,"max":0.5,"cat":"BÁSICOS AOC","era":1,"ingredients":[]},
  {"name":"Cooper Ore","min":2,"max":2,"cat":"BÁSICOS AOC","era":2,"ingredients":[]},
  {"name":"Tin Ore","min":1,"max":1,"cat":"BÁSICOS AOC","era":2,"ingredients":[]},
  {"name":"Arsenic","min":1,"max":1,"cat":"BÁSICOS AOC","era":2,"ingredients":[]},
  {"name":"Carbon","min":1,"max":1,"cat":"BÁSICOS AOC","era":2,"ingredients":[]},
  {"name":"Cobalt Ore","min":0.5,"max":0.5,"cat":"BÁSICOS AOC","era":2,"ingredients":[]},
  {"name":"Aluminium","min":1,"max":1,"cat":"BÁSICOS AOC","era":2,"ingredients":[]},
  {"name":"Vanadium","min":1,"max":1,"cat":"BÁSICOS AOC","era":2,"ingredients":[]},
  {"name":"Titanium","min":2,"max":2,"cat":"BÁSICOS AOC","era":2,"ingredients":[]},
  {"name":"Quartz","min":2,"max":3,"cat":"BÁSICOS AOC","era":2,"ingredients":[]},
  {"name":"Onyx","min":0.5,"max":0.5,"cat":"BÁSICOS AOC","era":2,"ingredients":[]},
  {"name":"Kronyx","min":1,"max":1,"cat":"BÁSICOS AOC","era":2,"ingredients":[]},
  {"name":"Eveirium","min":15,"max":30,"cat":"BÁSICOS AOC","era":5,"ingredients":[]},
  {"name":"Uncut Ruby","min":0.5,"max":1,"cat":"CRISTAIS AOC","era":1,"ingredients":[]},
  {"name":"Uncut Sapphire","min":0.5,"max":1,"cat":"CRISTAIS AOC","era":1,"ingredients":[]},
  {"name":"Uncut Emerald","min":0.5,"max":1,"cat":"CRISTAIS AOC","era":1,"ingredients":[]},
  {"name":"Uncut Topaz","min":0.5,"max":1,"cat":"CRISTAIS AOC","era":1,"ingredients":[]},
  {"name":"Uncut Amethyst","min":4,"max":5,"cat":"CRISTAIS AOC","era":1,"ingredients":[]},
  {"name":"Uncut Diamond","min":80,"max":90,"cat":"CRISTAIS AOC","era":1,"ingredients":[]},
  {"name":"Ruby Shard","min":3,"max":4,"cat":"CRISTAIS AOC","era":2,"ingredients":[{"qty":6,"item":"Uncut Ruby"}]},
  {"name":"Sapphire Shard","min":3,"max":4,"cat":"CRISTAIS AOC","era":2,"ingredients":[{"qty":6,"item":"Uncut Sapphire"}]},
  {"name":"Emerald Shard","min":3,"max":4,"cat":"CRISTAIS AOC","era":2,"ingredients":[{"qty":6,"item":"Uncut Emerald"}]},
  {"name":"Topaz Shard","min":3,"max":4,"cat":"CRISTAIS AOC","era":2,"ingredients":[{"qty":6,"item":"Uncut Topaz"}]},
  {"name":"Amethyst Shard","min":23,"max":25,"cat":"CRISTAIS AOC","era":2,"ingredients":[{"qty":6,"item":"Uncut Amethyst"}]},
  {"name":"Ruby","min":15,"max":16,"cat":"CRISTAIS AOC","era":3,"ingredients":[{"qty":4,"item":"Ruby Shard"}]},
  {"name":"Sapphire","min":15,"max":16,"cat":"CRISTAIS AOC","era":3,"ingredients":[{"qty":4,"item":"Sapphire Shard"}]},
  {"name":"Emerald","min":15,"max":16,"cat":"CRISTAIS AOC","era":3,"ingredients":[{"qty":4,"item":"Emerald Shard"}]},
  {"name":"Topaz","min":15,"max":16,"cat":"CRISTAIS AOC","era":3,"ingredients":[{"qty":4,"item":"Topaz Shard"}]},
  {"name":"Amethyst","min":102,"max":112,"cat":"CRISTAIS AOC","era":3,"ingredients":[{"qty":4,"item":"Amethyst Shard"}]},
  {"name":"Diamond","min":352,"max":387,"cat":"CRISTAIS AOC","era":3,"ingredients":[{"qty":4,"item":"Uncut Diamond"}]},
  {"name":"Bronze Bar","min":50,"max":54,"cat":"AVANÇADOS AOC","era":2,"ingredients":[{"qty":20,"item":"Cooper Ore"},{"qty":10,"item":"Tin Ore"},{"qty":5,"item":"Arsenic"}]},
  {"name":"Onyx Composite","min":52,"max":57,"cat":"AVANÇADOS AOC","era":2,"ingredients":[{"qty":5,"item":"Onyx"},{"qty":30,"item":"Kronyx"},{"qty":10,"item":"Vanadium"},{"qty":5,"item":"Carbon"}]},
  {"name":"Chromium Metal Bar","min":46,"max":51,"cat":"AVANÇADOS AOC","era":3,"ingredients":[{"qty":12,"item":"Carbon"},{"qty":10,"item":"Cobalt Ore"},{"qty":25,"item":"Aluminium"}]},
  {"name":"Titanium Alloy","min":21,"max":24,"cat":"AVANÇADOS AOC","era":4,"ingredients":[{"qty":6,"item":"Vanadium"},{"qty":9,"item":"Aluminium"},{"qty":3,"item":"Titanium"}]},
  {"name":"Skyan Metal Bar","min":13283,"max":14611,"cat":"AVANÇADOS AOC","era":6,"ingredients":[{"qty":2,"item":"Onyxite"},{"qty":1,"item":"Amethyst"},{"qty":5,"item":"Onyx Composite"},{"qty":30,"item":"Quartz"}]},
  {"name":"Xarium Metal Bar","min":25905,"max":28496,"cat":"AVANÇADOS AOC","era":6,"ingredients":[{"qty":2,"item":"Elarinite"},{"qty":10,"item":"Onyx Composite"},{"qty":35,"item":"Vanadium"},{"qty":1,"item":"Diamond"}]},
  {"name":"Onyxite","min":5826,"max":6409,"cat":"FORJAS AOC","era":6,"ingredients":[{"qty":100,"item":"Onyx"},{"qty":1,"item":"Essence Of Binding"},{"qty":5,"item":"Ruby"},{"qty":25,"item":"Fragment of Fury"}]},
  {"name":"Elarinite","min":11320,"max":12453,"cat":"FORJAS AOC","era":6,"ingredients":[{"qty":1,"item":"Onyxite"},{"qty":100,"item":"Unstable Substance"},{"qty":5,"item":"Emerald"},{"qty":1,"item":"Plague Crystal"}]},
  {"name":"Kronyxium","min":12093,"max":13303,"cat":"FORJAS AOC","era":6,"ingredients":[{"qty":1,"item":"Onyxite"},{"qty":100,"item":"Kronyx"},{"qty":5,"item":"Sapphire"},{"qty":1,"item":"Runic Enchantment"}]},
  {"name":"Minério de Ferro","min":0.3,"max":0.3,"cat":"MINÉRIOS","era":1,"ingredients":[]},
  {"name":"Rocha Prateada","min":7,"max":9,"cat":"MINÉRIOS","era":2,"ingredients":[]},
  {"name":"Rocha Dourada","min":9,"max":13,"cat":"MINÉRIOS","era":2,"ingredients":[]},
  {"name":"Obsidiana","min":0.3,"max":0.5,"cat":"MINÉRIOS","era":5,"ingredients":[]},
  {"name":"Minério de Metal das Estrelas","min":6,"max":7,"cat":"MINÉRIOS","era":4,"ingredients":[]}
];
