dataByProfession.treinador = [
  {"name":"Sela Leve","min":247,"max":296,"cat":"SELA DE CAVALO","era":1,"ingredients":[{"qty":20,"item":"Barbante"},{"qty":68,"item":"Barra de Ferro"},{"qty":75,"item":"Couro"}]},
  {"name":"Fur Layered Saddle","min":233,"max":279,"cat":"SELA DE CAVALO","era":1,"ingredients":[{"qty":20,"item":"Barbante"},{"qty":25,"item":"Pelos"},{"qty":50,"item":"Couro Reforçado"}]},
  {"name":"Selas Básicas","min":268,"max":321,"cat":"SELA DE CAVALO","era":1,"ingredients":[{"qty":20,"item":"Barbante"},{"qty":25,"item":"Seda"},{"qty":50,"item":"Couro Reforçado"}]},
  {"name":"The Traveler Saddle","min":1000,"max":1200,"cat":"SELA DE CAVALO","era":2,"ingredients":[{"qty":2,"item":"Sela Leve"},{"qty":190,"item":"Barra de Ferro"},{"qty":90,"item":"Couro"}]},
  {"name":"The Traveler Horse","min":1333,"max":1599,"cat":"SELA DE CAVALO","era":2,"ingredients":[{"qty":2,"item":"Cavalo Marrom"},{"qty":1,"item":"Poção de Dote"}]},
  {"name":"Sela Média","min":707,"max":848,"cat":"SELA DE CAVALO","era":2,"ingredients":[{"qty":20,"item":"Barbante"},{"qty":52,"item":"Couro Reforçado"},{"qty":68,"item":"Barra de Aço"}]},
  {"name":"Sela de Guerra","min":1152,"max":1383,"cat":"SELA DE CAVALO","era":3,"ingredients":[{"qty":20,"item":"Barbante"},{"qty":75,"item":"Barra de Aço Enrijecido"},{"qty":15,"item":"Reforço de Aço"}]},
  {"name":"Sela de Batedor","min":1400,"max":1679,"cat":"SELA DE CAVALO","era":3,"ingredients":[{"qty":20,"item":"Barbante"},{"qty":27,"item":"Seda em Camada"},{"qty":64,"item":"Couro Reforçado"}]},
  {"name":"Sela de Cavalaria","min":4699,"max":5639,"cat":"SELA DE CAVALO","era":3,"ingredients":[{"qty":20,"item":"Barbante"},{"qty":60,"item":"Couro Enrijecido"},{"qty":15,"item":"Reforço de Aço"}]},
  {"name":"10 Anos","min":0,"max":0,"cat":"TABELA DE TEMPO            PROGRESSÃO PET","era":1,"ingredients":[]},
  {"name":"20 Anos","min":0,"max":0,"cat":"TABELA DE TEMPO            PROGRESSÃO PET","era":2,"ingredients":[]},
  {"name":"30 Anos","min":0,"max":0,"cat":"TABELA DE TEMPO            PROGRESSÃO PET","era":3,"ingredients":[]},
  {"name":"40 Anos","min":0,"max":0,"cat":"TABELA DE TEMPO            PROGRESSÃO PET","era":4,"ingredients":[]},
  {"name":"50 Anos+","min":0,"max":0,"cat":"TABELA DE TEMPO            PROGRESSÃO PET","era":5,"ingredients":[]},
  {"name":"ITEM","min":0,"max":0,"cat":"TABELA DE TEMPO            PROGRESSÃO PET","era":"","ingredients":[]},
  {"name":"Pluma","min":1,"max":2,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Esterco","min":0.3,"max":0.5,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Ovo","min":0.5,"max":1,"cat":"BÁSICO","era":1,"ingredients":[]},
  {"name":"Sela Leve","min":182,"max":218,"cat":"SELA DE RINOCERONTE","era":2,"ingredients":[{"qty":20,"item":"Barbante"},{"qty":68,"item":"Barra de Ferro"},{"qty":50,"item":"Couro"}]},
  {"name":"Sela Média","min":380,"max":456,"cat":"SELA DE RINOCERONTE","era":2,"ingredients":[{"qty":20,"item":"Barbante"},{"qty":68,"item":"Seda"},{"qty":50,"item":"Couro Reforçado"}]},
  {"name":"Sela Pesada","min":1400,"max":1679,"cat":"SELA DE RINOCERONTE","era":3,"ingredients":[{"qty":20,"item":"Barbante"},{"qty":27,"item":"Seda em Camada"},{"qty":64,"item":"Couro Reforçado"}]},
  {"name":"Sela de Cavalaria","min":4699,"max":5639,"cat":"SELA DE RINOCERONTE","era":3,"ingredients":[{"qty":20,"item":"Barbante"},{"qty":60,"item":"Couro Enrijecido"},{"qty":15,"item":"Reforço de Aço"}]},
  {"name":"Sela de Guerra","min":1152,"max":1383,"cat":"SELA DE RINOCERONTE","era":3,"ingredients":[{"qty":20,"item":"Barbante"},{"qty":75,"item":"Barra de Aço Enrijecida"},{"qty":15,"item":"Reforço de Aço"}]},
  {"name":"Tier 1","min":500,"max":750,"cat":"ANIMAIS","era":1,"ingredients":[{"qty":0,"item":"Cavalo"}]},
  {"name":"Tier 2","min":1000,"max":1500,"cat":"ANIMAIS","era":2,"ingredients":[{"qty":0,"item":"Elefante"}]},
  {"name":"Tier 3","min":2500,"max":3000,"cat":"ANIMAIS","era":3,"ingredients":[{"qty":0,"item":"Yeti"}]},
  {"name":"Tier 4","min":4500,"max":4500,"cat":"ANIMAIS","era":4,"ingredients":[{"qty":0,"item":"Yeti Preto"}]},
  {"name":"Pigeon (os dois tipos)","min":600,"max":0,"cat":"PÁSSAROS","era":1,"ingredients":[{"qty":1,"item":"Ovo"},{"qty":10,"item":"Sementes"},{"qty":3,"item":"Sementes de arbusto-frutífero das Terras Altas"}]},
  {"name":"Crow (os dois tipos)","min":750,"max":0,"cat":"PÁSSAROS","era":1,"ingredients":[{"qty":1,"item":"Ovo"},{"qty":10,"item":"Sementes"},{"qty":3,"item":"Sementes de Tremoceiro"}]},
  {"name":"Sparrow (os dois tipos)","min":500,"max":0,"cat":"PÁSSAROS","era":1,"ingredients":[{"qty":1,"item":"Ovo"},{"qty":10,"item":"Sementes"},{"qty":3,"item":"Sementes de Mandrágora Falsa"}]},
  {"name":"Owl","min":1000,"max":0,"cat":"PÁSSAROS","era":1,"ingredients":[{"qty":1,"item":"Ovo"},{"qty":10,"item":"Sementes"},{"qty":3,"item":"Sementes da Flor Azul da Meia Noite"}]},
  {"name":"Macaw","min":600,"max":0,"cat":"PÁSSAROS","era":1,"ingredients":[{"qty":1,"item":"Ovo"},{"qty":10,"item":"Sementes"},{"qty":3,"item":"Sementes de Lótus Púrpura"}]},
  {"name":"Hawk","min":1000,"max":0,"cat":"PÁSSAROS","era":1,"ingredients":[{"qty":1,"item":"Ovo"},{"qty":10,"item":"Sementes"},{"qty":3,"item":"Sementes de Lótus Gélida"}]},
  {"name":"Eagle","min":1000,"max":0,"cat":"PÁSSAROS","era":1,"ingredients":[{"qty":1,"item":"Ovo"},{"qty":10,"item":"Sementes"},{"qty":3,"item":"Sementes de Lótus Dourada"}]},
  {"name":"Raven","min":750,"max":0,"cat":"PÁSSAROS","era":1,"ingredients":[{"qty":1,"item":"Ovo"},{"qty":10,"item":"Sementes"},{"qty":3,"item":"Sementes de Lótus Negra"}]},
  {"name":"Seagull","min":500,"max":0,"cat":"PÁSSAROS","era":1,"ingredients":[{"qty":1,"item":"Ovo"},{"qty":10,"item":"Sementes"},{"qty":3,"item":"Corte de Ficobilina Laranja"}]},
  {"name":"Chicken","min":500,"max":0,"cat":"PÁSSAROS","era":1,"ingredients":[{"qty":1,"item":"Ovo"},{"qty":20,"item":"Sementes"}]},
  {"name":"Duck","min":500,"max":0,"cat":"PÁSSAROS","era":1,"ingredients":[{"qty":1,"item":"Ovo"},{"qty":20,"item":"Sementes"}]},
  {"name":"Harpy Eagle","min":1000,"max":0,"cat":"PÁSSAROS","era":1,"ingredients":[{"qty":1,"item":"Ovo"},{"qty":10,"item":"Sementes"},{"qty":3,"item":"Sementes de Lótus Dourada"}]},
  {"name":"Parakeet","min":500,"max":0,"cat":"PÁSSAROS","era":1,"ingredients":[{"qty":1,"item":"Ovo"},{"qty":10,"item":"Sementes"},{"qty":3,"item":"Sementes de Tremoceiro"}]},
  {"name":"Robin","min":500,"max":0,"cat":"PÁSSAROS","era":1,"ingredients":[{"qty":1,"item":"Ovo"},{"qty":10,"item":"Sementes"},{"qty":3,"item":"Sementes de arbusto-frutífero das Terras Altas"}]},
  {"name":"Toucan","min":500,"max":0,"cat":"PÁSSAROS","era":1,"ingredients":[{"qty":1,"item":"Ovo"},{"qty":10,"item":"Sementes"},{"qty":3,"item":"Sementes de Lúpulo"}]},
  {"name":"Bald Eagle","min":1000,"max":0,"cat":"PÁSSAROS","era":1,"ingredients":[{"qty":1,"item":"Ovo"},{"qty":10,"item":"Sementes"},{"qty":3,"item":"Sementes de Lótus Dourada"}]},
  {"name":"Vulture","min":500,"max":0,"cat":"PÁSSAROS","era":1,"ingredients":[{"qty":1,"item":"Ovo"},{"qty":10,"item":"Sementes"},{"qty":10,"item":"Carne de feras"}]},
  {"name":"Tier 1","min":400,"max":500,"cat":"ANIMAIS SIPTAH (VERSÃO COMUM)","era":1,"ingredients":[]},
  {"name":"Tier 2","min":800,"max":1000,"cat":"ANIMAIS SIPTAH (VERSÃO COMUM)","era":2,"ingredients":[]},
  {"name":"Tier 3","min":3000,"max":4000,"cat":"ANIMAIS SIPTAH (VERSÃO COMUM)","era":3,"ingredients":[]},
  {"name":"Tier 1","min":600,"max":700,"cat":"ANIMAIS SIPTAH (VERSÃO ENORME)","era":1,"ingredients":[]},
  {"name":"Tier 2","min":1400,"max":1600,"cat":"ANIMAIS SIPTAH (VERSÃO ENORME)","era":2,"ingredients":[]},
  {"name":"Tier 3","min":3500,"max":4000,"cat":"ANIMAIS SIPTAH (VERSÃO ENORME)","era":3,"ingredients":[]},
  {"name":"Tier 4","min":4500,"max":5000,"cat":"ANIMAIS SIPTAH (VERSÃO ENORME)","era":4,"ingredients":[]},
  {"name":"Tier 5","min":9172,"max":11006,"cat":"ANIMAIS AOC","era":5,"ingredients":[{"qty":0,"item":"Unstable Substance"},{"qty":300,"item":"Scourge Mammoth Head"},{"qty":1,"item":"Amethyst (1)"}]},
  {"name":"Tier 6","min":82970,"max":99564,"cat":"ANIMAIS AOC","era":6,"ingredients":[{"qty":0,"item":"1"},{"qty":0,"item":"1"},{"qty":0,"item":"250"}]},
  {"name":"Tier 1","min":300,"max":500,"cat":"LCDA","era":1,"ingredients":[{"qty":1,"item":"Chicken Red"}]},
  {"name":"Tier 1","min":1500,"max":2000,"cat":"LCDA","era":1,"ingredients":[{"qty":1,"item":"Perlino"}]},
  {"name":"10 Anos","min":0,"max":0,"cat":"TABELA DE TEMPO            PROGRESSÃO LACAIO","era":1,"ingredients":[]},
  {"name":"20 Anos","min":0,"max":0,"cat":"TABELA DE TEMPO            PROGRESSÃO LACAIO","era":2,"ingredients":[]},
  {"name":"30 Anos","min":0,"max":0,"cat":"TABELA DE TEMPO            PROGRESSÃO LACAIO","era":3,"ingredients":[]},
  {"name":"40 Anos","min":0,"max":0,"cat":"TABELA DE TEMPO            PROGRESSÃO LACAIO","era":4,"ingredients":[]},
  {"name":"50 Anos+","min":0,"max":0,"cat":"TABELA DE TEMPO            PROGRESSÃO LACAIO","era":5,"ingredients":[]},
  {"name":"10 ANOS","min":300,"max":400,"cat":"LACAIOS","era":1,"ingredients":[{"qty":0,"item":"Qualquer Natureza"}]},
  {"name":"20 ANOS","min":0,"max":0,"cat":"LACAIOS","era":2,"ingredients":[{"qty":0,"item":"Qualquer Natureza"}]},
  {"name":"30 ANOS","min":0,"max":0,"cat":"LACAIOS","era":3,"ingredients":[{"qty":0,"item":"Qualquer Natureza"}]},
  {"name":"40 ANOS","min":0,"max":0,"cat":"LACAIOS","era":4,"ingredients":[{"qty":0,"item":"Qualquer Natureza"}]},
  {"name":"20 ANOS","min":0,"max":0,"cat":"LACAIOS AOC","era":2,"ingredients":[{"qty":0,"item":"StormHold"}]},
  {"name":"30 ANOS","min":0,"max":0,"cat":"LACAIOS AOC","era":3,"ingredients":[{"qty":0,"item":"StormHold"}]},
  {"name":"40 ANOS","min":0,"max":0,"cat":"LACAIOS AOC","era":4,"ingredients":[{"qty":0,"item":"StormHold"},{"qty":0,"item":"Cold Embrance"}]},
  {"name":"50 ANOS","min":0,"max":0,"cat":"LACAIOS AOC","era":5,"ingredients":[{"qty":0,"item":"Qualquer Natureza / Facção"}]},
  {"name":"60 ANOS","min":0,"max":0,"cat":"LACAIOS AOC","era":6,"ingredients":[{"qty":0,"item":"StormHold"}]},
  {"name":"70 ANOS","min":0,"max":0,"cat":"LACAIOS AOC","era":6,"ingredients":[{"qty":0,"item":"StormHold"}]}
];
